### ISSUE TITLE
能编译下吗

### ISSUE THREAD

**Issue by ashi876** [zhongyang219/MusicPlayer2#1]
能偶尔更新win下的编译版么

**Comment by zhongyang219** [comment]
你是想要编译编译好的exe文件吗，由于GitHub在上传项目文件时会忽略exe文件而无法上传，如果你想要编译好的exe文件，可从这里下载：https://pan.baidu.com/s/1i5QNwFF

**Comment by ashi876** [comment]
谢谢。好人一生平安

**Comment by ashi876** [comment]
你上传的时候可以打包的。百度盘收下了，想学编程为aimp弄个歌词插件，太需要这个了

**Comment by happy886rr** [comment]
写的非常不错，难得的认真作品。

**Comment by Crystal-RainSlide** [comment]
https://github.com/zhongyang219/MusicPlayer2/releases

**Comment by saberlily12345** [comment]
你好，我想问下我在VS2017下进行编译，应该用x32还是x64呢。。。，或者用别的编译环境？

**Comment by zhongyang219** [comment]
@saberlily12345 必须在x86下编译，因为播放音乐的bass音频库是32位的，在x64下会编译不通过。
