### ISSUE TITLE
为什么只有这个软件读不出来这首音乐的专辑封面？

### ISSUE THREAD

**Issue by YandLiu** [zhongyang219/MusicPlayer2#100]
试了Foobar、MPC-HC、Potplayer，都可以正常加载出来封面啊
https://wwa.lanzous.com/iKi39gif5pe

**Comment by zhongyang219** [comment]
请稍安勿躁，新版本即将发布，在新版本中使用第三方库taglib来获取音频文件的标签信息的专辑封面，彻底解决了之前版本中标签信息、专辑封面无法读取的问题，同时，新增了十几种音频格式的标签/专辑封面的读写功能，你可以[点击这里](https://github.com/zhongyang219/MusicPlayer2/wiki/%E6%94%AF%E6%8C%81%E7%9A%84%E9%9F%B3%E9%A2%91%E6%A0%BC%E5%BC%8F)查看即将发布的版本中支持的格式，敬请期待！

**Comment by zhongyang219** [comment]
问题已解决，请更新到2.71版
