### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hudi13477063465** [zhongyang219/MusicPlayer2#105]
非常喜欢,用来学英语的,如果能做个lrc全屏就好了,目前这个效果也不错,不过上面的空间就有点浪费了
![image](https://user-images.githubusercontent.com/45613372/93062061-01e55700-f6a7-11ea-8b06-34e9618a587d.png)

**Comment by zhongyang219** [comment]
很高兴MusicPlayer2能够为你学习英语提供帮助，关于歌词全屏的功能，会考虑在后续版本中增加

**Comment by zhongyang219** [comment]
最新版本中新增了界面3，应该能满足你的需求
