### ISSUE TITLE
请问能否增加单曲播放模式，或者不要记忆播放列表？

### ISSUE THREAD

**Issue by shimakotodo** [zhongyang219/MusicPlayer2#107]
非常喜欢这款软件，一直用V2.69到现在，今天意外的发现竟然更新了好几个版本。

请问以后能否增加单曲播放模式？现在每播放一个音频，都会自动记忆到当前默认播放列表中，且只能设置最少记忆一天。每次不管播放什么都要自动播放列表里的全部。
但我的习惯，多数时候是一个一个的点开听，听完后希望能够停止，不要自动播放之前听过的。所以不得不时常手动点删除-清空播放列表。

能否考虑以后增加个单曲播放模式，放完当前的这一首后就自动停止播放？
（如果不方便的话，也或者增加一个不要记忆最近播放的选项）

再次感谢作者制作。

**Comment by zhongyang219** [comment]
感谢建议，单曲播放模式的功能会在下个版本中增加。

**Comment by shimakotodo** [comment]
> 感谢建议，单曲播放模式的功能会在下个版本中增加。

实在太感谢了，强烈期待中
