### ISSUE TITLE
建议：请问能否在日文歌词的汉字上显示振假名

### ISSUE THREAD

**Issue by tonyzzz321** [zhongyang219/MusicPlayer2#110]
对不起还是我。
本人在学习日语。一个我在LyricsX (https://github.com/ddddxxx/LyricsX) 上比较喜欢的功能是自动在日文歌词的汉字上标上振假名 (https://zh.wikipedia.org/zh-cn/%E6%8C%AF%E5%81%87%E5%90%8D) 。LyricsX上的效果如下图。如果能加上这个功能就好了。
<img width="349" alt="89122664-a480b680-d4fb-11ea-93df-2728ce062489" src="https://user-images.githubusercontent.com/16433546/93694666-6f3c2200-fac3-11ea-9918-886196966b71.png">

**Comment by zhengwulin** [comment]
我记得有好几款字体 能实现你所想要的 
附上我曾经看到过的字体 url
https://www.deviantart.com/
如果在上述网址找不到,只能说明我记错了来源,十分抱歉

**Comment by HashLiver** [comment]
你真的是学日语的吗？
众所周知，日语汉字包括音读和训读，想靠自动标记振假名或者字体之类的绝对会引入歧途；
比如：
「空」字，什么时候读sora，什么时候读ku（空気）？
「人」字，什么时候读jin（人類），什么时候读rin（人間），什么时候又读hito？
软件/字体能判别吗？
要是出现日本人名，呵呵——那又是一种完全不同的读法了

**Comment by zhengwulin** [comment]
既然说了 不是简单的音标问题并且 软件同等无法准确翻译在结合目前已知各大音乐播放器显示的注音歌词都是来源人力提交
那么不同等与直接爬趴取下载歌曲对应 源/翻译/音译.注音歌词文件
最简单的办法下载歌词页面添加注音歌词方法或者自己手动去对应音乐播放器获取的歌词下载下来,那么MusicPlayer2歌词页面不就正确显示了
可惜出来的结果就是歌词页面 显示双行 一行词 一行振假名   而不是单行词上面显示振假名

**Comment by zhongyang219** [comment]
抱歉，这个功能暂时做不到
