### ISSUE TITLE
系统切换默认播放设备后，仍然使用原来的设备播放

### ISSUE THREAD

**Issue by Youxikong** [zhongyang219/MusicPlayer2#112]
Musicplayer2的播放设置，播放设备选项是默认播放设备。当通过系统的托盘切换默认播放设备后，Music Player仍然使用原来设备播放。
系统版本是2004，笔记本和台式电脑都是如此。

**Comment by subframe7536** [comment]
2.72也是这样

**Comment by lrisora** [comment]
https://github.com/zhongyang219/MusicPlayer2/issues/144

https://github.com/zhongyang219/MusicPlayer2/issues/89#issuecomment-679023999

**Comment by Youxikong** [comment]
现在是根据系统默认设备切换了，关闭了。
