### ISSUE TITLE
求分享代码技术栈，以及如何学习上手呢？

### ISSUE THREAD

**Issue by Korleone7** [zhongyang219/MusicPlayer2#114]
代码风格非常赞，可以分享下这份代码的技术栈么？  C++ QT？

主要是不知道如何入手，想在您的基础上做一些增量开发。

非常感谢

**Comment by zhongyang219** [comment]
技术栈就是C++ MFC，除此之外好像确实没有用到其他技术了。并没有使用到QT（虽然如果使用QT的话很多功能实现起来会方便得多），整个软件就是使用纯C++和MFC开发的，软件的主界面是使用GDI绘图实现的，桌面歌词部分使用到了GDI+。MFC确实是一个很老的技术了，话说现在还在使用MFC开发软件的人确实比较少。不过我的代码中也用到了很多C++11的新特性。
这个软件是开源的，你可以在我的基础上进行开发，但是在使用我的源代码的时候要注意遵守开源协议。

**Comment by nightson** [comment]
> 
> 
> 技术栈就是C++ MFC，除此之外好像确实没有用到其他技术了。并没有使用到QT（虽然如果使用QT的话很多功能实现起来会方便得多），整个软件就是使用纯C++和MFC开发的，软件的主界面是使用GDI绘图实现的，桌面歌词部分使用到了GDI+。MFC确实是一个很老的技术了，话说现在还在使用MFC开发软件的人确实比较少。不过我的代码中也用到了很多C++11的新特性。
> 这个软件是开源的，你可以在我的基础上进行开发，但是在使用我的源代码的时候要注意遵守开源协议。

比QT的优势在哪儿？性能和资源占用更低吗

**Comment by zhongyang219** [comment]
> > 技术栈就是C++ MFC，除此之外好像确实没有用到其他技术了。并没有使用到QT（虽然如果使用QT的话很多功能实现起来会方便得多），整个软件就是使用纯C++和MFC开发的，软件的主界面是使用GDI绘图实现的，桌面歌词部分使用到了GDI+。MFC确实是一个很老的技术了，话说现在还在使用MFC开发软件的人确实比较少。不过我的代码中也用到了很多C++11的新特性。
> > 这个软件是开源的，你可以在我的基础上进行开发，但是在使用我的源代码的时候要注意遵守开源协议。
> 
> 比QT的优势在哪儿？性能和资源占用更低吗

MFC只是对Windows API的一个比较浅的封装，性能上可能会比QT好一些，除此之外相比QT并没有什么优势。如果你问我为什么没有使用QT，那仅仅是因为我在一开始写MusicPlayer2的时候还不会用QT，后来虽然学了QT，也曾经想用QT重写，但由于工作量太大就放弃了。
