### ISSUE TITLE
关于曲目名称排序优化的反馈

### ISSUE THREAD

**Issue by vlcheng** [zhongyang219/MusicPlayer2#115]
在2.71版本中，当导入名称包含序号前缀的曲目时（曲目中不含有音轨序号），自动排序无法正确识别序号的位数，仅能按照首字母顺序来进行排列。希望未来的版本能对文件名排序加以优化。

**Comment by zhongyang219** [comment]
这个要优化起来有点困难，如果要实现你的需求，我需要将名称前面的数字截取出来，再转换成数字，再根据数字进行排序。倒不是说这个功能不好实现，而是如果我这么做了的话，可能会带来很大的性能问题，导致播放列表加载速度变慢，如果播放列表中有几千甚至上万条项目的时候可能会出现明显的卡顿。

**Comment by vlcheng** [comment]
确实，对文件名进行逐位排序相比现有的排序时间损耗会是乘数级别，最坏情况下倍数就等于文件名的长度，如果每次启动或者刷新都进行一次排序确实不太能接受。
不过能否将排序结果储存起来，平时直接读取，每次新加入曲目的时候再对当前列表的曲目文件名进行逐位对比，以此来减少
