### ISSUE TITLE
请问下歌词检索的机制是什么？

### ISSUE THREAD

**Issue by zhoulukuan** [zhongyang219/MusicPlayer2#118]
从同一个网站下载的歌曲，有的可以识别歌手和歌词，有的无法识别，想请问下机制原理是什么，为什么会出现这种情况？

**Comment by zhongyang219** [comment]
请详细描述你的问题，并最好附上有问题的音频文件，否则我无法为你解答问题

**Comment by zhoulukuan** [comment]
@zhongyang219 您好，我的问题是，我的音频文件都是从同一个网站上下载的。但是下载后，只有部分歌曲可以自动识别出歌手专辑等信息，并自动下载歌词文件，另一部分歌曲则不可以。如下图所示：
![3](https://user-images.githubusercontent.com/16110591/97805489-6f6a3880-1c91-11eb-94ca-af5478ab195b.png)
在播放主页面，也是同样的，只有部分歌曲可以展示歌词，另一部分相关信息都是未知。
![1](https://user-images.githubusercontent.com/16110591/97805491-7002cf00-1c91-11eb-9e72-a73462d16f45.png)
![2](https://user-images.githubusercontent.com/16110591/97805493-71cc9280-1c91-11eb-80d4-90fd1b1c4480.png)
我想请问为什么会出现这一现象？是否和音频命名有关系？相关歌词文件是从哪儿下载的呢？

**Comment by zhongyang219** [comment]
你好，有的网站下载的音频文件没有包含标签信息或者标签信息不全，例如图中的红框里的文件。MusicPlayer2下载歌词使用的是网易云音乐的接口，它将根据歌曲的标签信息调用网易云音乐的接口下载歌词，如果歌曲没有标签信息就无法自动下载。当然，你也可以手动下载歌词，选择主菜单的歌词-下载歌词进行手动下载。另外对于标签信息显示为未知的音频文件，你也可以在播放列表右键菜单中选择属性，手动编辑标签信息。

**Comment by zhoulukuan** [comment]
> 你好，有的网站下载的音频文件没有包含标签信息或者标签信息不全，例如图中的红框里的文件。MusicPlayer2下载歌词使用的是网易云音乐的接口，它将根据歌曲的标签信息调用网易云音乐的接口下载歌词，如果歌曲没有标签信息就无法自动下载。当然，你也可以手动下载歌词，选择主菜单的歌词-下载歌词进行手动下载。另外对于标签信息显示为未知的音频文件，你也可以在播放列表右键菜单中选择属性，手动编辑标签信息。

尝试下果然可以，感谢~
