### ISSUE TITLE
搜索框歌词显示与windows浅色模式兼容问题

### ISSUE THREAD

**Issue by omoidesu** [zhongyang219/MusicPlayer2#12]
设置里个性化→颜色 如果选择是浅色，搜索框显示歌词的地方是全白的，如果选择深色不会出现问题。同样的问题在深色并开启translucentTB时一样存在。

系统：win10 pro insider review  18917.1000

**Comment by zhongyang219** [comment]
你好，这个问题我已经发现了，并且在代码中作了一些处理。作为临时的解决方案，请打开config.ini，在[other]下面添加下面一行配置：
cortana_opaque = false
再次启动后搜索框就会变得不透明。如果需要恢复原状，重启资源管理器即可。
