### ISSUE TITLE
进度条会后退到一分处 / m3u8不支持相对路径

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#121]
- 进度条方向键左键后退在一次更新后出了问题，防止后退到负数的时候会回到一分钟处
如图，撤销图中更改后恢复，同时655xx.x这个无符号数下溢变成负数

<img width="1744" alt="屏幕截图 2020-11-11 201246" src="https://user-images.githubusercontent.com/43085437/99138665-2f318f80-266d-11eb-82a5-8976baafff34.png">

 - m3u8标准是有相对路径的，如图

<img width="701" alt="屏幕截图 2020-11-10 214848" src="https://user-images.githubusercontent.com/43085437/99138751-e1695700-266d-11eb-929a-41ac6c9717cc.png">

有没有必要加一个是否把m3u8存储为playlist文件的选项？

**Comment by zhongyang219** [comment]
感谢反馈，进度条的问题已经解决。

**Comment by lrisora** [comment]
问题已解决
