### ISSUE TITLE
桌面歌词的卡拉OK模式

### ISSUE THREAD

**Issue by sbwfnhn** [zhongyang219/MusicPlayer2#122]
软件里面有去掉卡拉OK样式，但是桌面歌词没有，希望添加桌面歌词的去掉卡拉OK样式功能，很多歌词时间显示不是很精确，很影响查看歌词，特别是不熟悉的新歌。

**Comment by Tim-Paik** [comment]
其实可以直接设置文字和高亮一个颜色的？
变相解决问题？
（还是说我理解有误qwq）

**Comment by zhongyang219** [comment]
桌面歌词不跟随“歌词卡拉OK样式显示”的设置其实是一个bug，现在已经修正，请等待下个版本更新。
