### ISSUE TITLE
关于启动之后开小窗模式它会默认窗口置顶

### ISSUE THREAD

**Issue by 1097477383** [zhongyang219/MusicPlayer2#125]
因为没有默认小窗模式开机启动，所以我把小窗开启的快捷方式计算机启动项了，之后又随之发现一个问题，那就是启动之后会默认的小窗总是置顶，希望这个能不让他默认总是置顶，谢谢

**Comment by zhongyang219** [comment]
最新版本已经可以取消迷你模式置顶功能。
