### ISSUE TITLE
按钮无效

### ISSUE THREAD

**Issue by GhostNoc** [zhongyang219/MusicPlayer2#13]
![$D3 O_M3JF{Y%VSFPK00IJ](https://user-images.githubusercontent.com/29757779/60478314-d7cb9300-9cb4-11e9-8914-2f0cae063403.png)
预览窗口的按钮无效

**Comment by zhongyang219** [comment]
抱歉我没有遇到过这个问题，你说的按钮无效是点击没有反应吗？按钮是一开始就无效还是某个时候出现的？什么情况下出现的这个问题呢？

**Comment by GhostNoc** [comment]
是一开始就没有反应，点了没有用
