### ISSUE TITLE
能否支持last.fm的同步？

### ISSUE THREAD

**Issue by Lethargyclub** [zhongyang219/MusicPlayer2#132]
简直是梦中情软（？），小巧功能全，还连接了网易的歌词库，太感谢作者了。唯一觉得有点遗憾的就是不能同步last.fm的收听记录，真的真的，如果有机会增加这个功能的话，真的太感谢了。
last.fm是一个能根据收听记录推荐艺人和歌曲的服务，这是api：https://www.last.fm/api

**Comment by Lethargyclub** [comment]
突然发现tak不支持文件

**Comment by Lethargyclub** [comment]
发现不支持tak格式，有机会支持的话就太好了

**Comment by zhongyang219** [comment]
感谢你喜欢MusicPlayer2。
* 目前没有做除了下载歌词和专辑封面之外的在线功能的计划。
* MusicPlayer2使用了BASS音频库播放音乐，但是BASS官方网站没有提供支持tak格式的插件，好在目前找到了用于可以用于BASS的第三方tak插件，会在下个版本中添加对tak格式的支持。但是由于tak解码器没有提供64位的版本，因此tak格式的支持只能添加到MusicPlayer2的32位版本中。
