### ISSUE TITLE
关于歌词

### ISSUE THREAD

**Issue by scggdani** [zhongyang219/MusicPlayer2#133]
歌词的显示和人声不同步，人声一直是提前出现，歌词延后

**Comment by Aqua-Chen** [comment]
作者调用的是网易云音乐歌词API，网易的歌词大部分都是ktv模式的，可能是作者为了与时俱进临时加了一个歌词进度跟进，但应该还没有来得及优化，等作者后续更新吧

**Comment by Aqua-Chen** [comment]
> 歌词的显示和人声不同步，人声一直是提前出现，歌词延后

作者调用的是网易云音乐歌词API，网易的歌词大部分都是ktv模式的，可能是作者为了与时俱进临时加了一个歌词进度跟进，但应该还没有来得及优化，等作者后续更新吧

**Comment by zhongyang219** [comment]
如果你遇到了这个问题，可以通过主菜单“歌词”下面的“歌词提前0.5秒”或“歌词延后0.5秒”来调整歌词同步，或者使用键盘快捷键Ctrl+PageUp/Ctrl+PageDown。调整完成后按Ctrl+S保存歌词更改。

**Comment by Aqua-Chen** [comment]
额，他说的是这个播放器的歌词是按照每行歌词的时间进度来显示的，而平时大多数歌曲对于每个字所用的时间是不一样的，再加上双语歌词就更会出现这个问题
