### ISSUE TITLE
.m4a格式的文件类型不应显示为“Apple Lossless Audio Codec”

### ISSUE THREAD

**Issue by rjys365** [zhongyang219/MusicPlayer2#135]
如题，m4a指的是MPEG-4格式的音频（一般使用AAC编码，在MPC-BE中文件类型显示为“Apple audio with iTunes info”，在VLC中显示为“MPEG AAC Audio (mp4a)“），而ALAC音频的文件扩展名为.alac，希望作者能加以修改。

**Comment by zhongyang219** [comment]
m4a文件类型显示来自bass插件bassalac.dll，无法在代码中更改
