### ISSUE TITLE
软件UI的建议

### ISSUE THREAD

**Issue by Aqua-Chen** [zhongyang219/MusicPlayer2#138]
感觉很多音乐播放器都有自己的界面框架，如果作者有时间的话可不可以做一个，我有强迫症，看不太惯系统框架，谢谢

**Comment by xivi1839** [comment]
这样已经不错了，作者哪有精力去做，要不然你来做

**Comment by PPX-LuBing** [comment]
如果你能做你可以自己做了给开发者借鉴，开发者未必有时间去干这种事啊，而且设计ui并不是说做就能做的，不然为啥有专业的ui设计师。。。
