### ISSUE TITLE
建议拖入文件或文件夹的时候，不要覆盖播放列表，而是追加到播放列表尾部

### ISSUE THREAD

**Issue by eden214** [zhongyang219/MusicPlayer2#14]
给个可选项也行

**Comment by zhongyang219** [comment]
由于目前版本的逻辑是以文件夹为单位管理歌曲的，所以每次只能打开同一个文件夹内的歌曲，当拖放另一个文件夹的文件的时候，必定会覆盖当前播放列表。
下一个版本会增加新建播放列表功能，拖动文件时会追加到当前播放列表。

**Comment by zhongyang219** [comment]
在播放列表模式下，拖放文件可以追加到播放列表末尾，但是拖放一个文件夹时，会切换到文件夹模式，请可以选择播放列表上面的菜单中的“添加”命令向播放列表中添加文件。
