### ISSUE TITLE
[询问] 两个小小的问题（歌词界面和获取相关）

### ISSUE THREAD

**Issue by myheartorz** [zhongyang219/MusicPlayer2#146]
非常感谢作者的MusicPlayer2！是神器！！（向亲友派安利
还非常低调，我都忘了是从哪个不知名的论坛挖到的OTZ
用了三天，完全满足需求！也很容易上手！

就是有两个小问题想问一下
①现在歌词和封面，在线是只支持从网易云音乐获取吗？没有QQ音乐之类的别的API是吗，还是有哪里可以选的我没看到qwq（单纯询问w 网易云音乐已经很够用了~）
②这个界面2，在歌词没有翻译只有原文时，它就会左上一句右下一句，这里是无法单独调整歌词显示格式的是吗w？因为在没翻译时也想单行显示或滚动显示但界面像这样一样小，不过如果实现有难度也没关系的！现在用户体验也超不错了！
![image](https://user-images.githubusercontent.com/63791468/108207064-32538480-7162-11eb-8586-b69d3f1b117d.png)

总之非常感谢！

**Comment by zhongyang219** [comment]
1. 目前只支持使用网易云的API，后面会考虑允许选择其他音乐网站的API（因为网易云的曲库不够全）
2. 关于歌词显示的问题请参见这里的说明：https://github.com/zhongyang219/MusicPlayer2/wiki/%E4%B8%BB%E7%95%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D

**Comment by myheartorz** [comment]
非常感谢！通过调整主界面窗口大小就成功了！实在是太好用啦！
另外想请问滚动播放歌词时，空白段落要怎么实现啊，我歌词长这样，播放时是全部连在一起的
![image](https://user-images.githubusercontent.com/63791468/108524909-80a38780-730a-11eb-9be4-c15730ec0d80.png)
![image](https://user-images.githubusercontent.com/63791468/108525361-f576c180-730a-11eb-8570-b1e7e154b22d.png)

**Comment by zhongyang219** [comment]
你需要为空白行添加时间标签：
![image](https://user-images.githubusercontent.com/30562462/108622483-1c043c00-7474-11eb-9793-770d92b87344.png)

**Comment by myheartorz** [comment]
收到！非常感谢(^^ゞ，新年快乐~
