### ISSUE TITLE
关于音乐标签和图片

### ISSUE THREAD

**Issue by cpf2333** [zhongyang219/MusicPlayer2#15]
大佬，我的音乐标签是用Android上的音乐标签编辑器https://www.coolapk.com/apk/com.xjcheng.musictageditor 写入的，几乎所有的标题和艺术家信息都无法识别，部分图片也无法识别，但在手机及其他pc音乐播放器，如Groove、极光音乐上则识别正常。请问可能是什么原因？我该怎么做才能让它们正确显示？
![屏幕截图(29)](https://user-images.githubusercontent.com/39972632/60663324-7b719a80-9e91-11e9-9d80-148a6f3775d0.png)
![屏幕截图(30)](https://user-images.githubusercontent.com/39972632/60663326-7b719a80-9e91-11e9-8786-e964f097aa9d.png)  
另外，音乐内嵌图片后，下载专辑封面按钮是灰色的，这有些不方便😂

**Comment by zhongyang219** [comment]
你好，可能是我的代码里获取音频标签的处理有问题。请把你的一个无法显示标签的音频文件通过电子邮件发给我，以帮助我确定无法获取音频标签的原因。邮件发送到 zhongyang219@hotmail.com。
另外，如果你可以在“选项”——“外观设置”中去掉“优先使用内嵌封面”的勾选，这样它就不会使用内嵌封面，只会加载外部专辑图片，下载专辑封面的命令就可以使用了。
