### ISSUE TITLE
同时播放两首音乐的bug

### ISSUE THREAD

**Issue by Futurescope** [zhongyang219/MusicPlayer2#151]
反馈一个严重的bug。当前版本**2.72 windows x64**
复现方法：音乐播放模式单曲循环，在播放音乐过程中调整歌词进度，在这首音乐播放完毕时窗口会暂时卡住，并弹窗提示“歌词已更改，是否保存”。此时在文件夹内双击音乐文件使用此软件打开，就会复现此bug，表现为**提示弹窗需要关闭两次**，并且**会有两首歌同时播放**，**新打开的歌曲无法暂停**，**界面中显示的歌曲与后台播放的不同等问题**。

**Comment by zhongyang219** [comment]
反馈已收到，谢谢，等有时间的时候会尝试解决这个问题

**Comment by zhongyang219** [comment]
问题已经解决，请等待下个版本更新
