### ISSUE TITLE
建议加入“禁止删除磁盘文件”和“隐藏音乐信息”两个选项

### ISSUE THREAD

**Issue by Fans1681** [zhongyang219/MusicPlayer2#152]
建议加入“禁止删除磁盘文件”和“隐藏音乐信息”两个选项

非常喜欢这个播放器，已经成为我的默认（也是唯一）的音乐播放器。

建议加入选项“禁止删除磁盘文件”，这是《千千静听》内置的，勾选后，所有“删除磁盘文件”菜单项成为灰色（不可选），从而避免误删文件。这是因为，众所周知的原因，现在下载歌曲越来越困难了（尤其是无损、高音质），一旦误删，想找回来就很难了。真想删除的话，我们自己进入资源管理器删除即可，删错了也与人无尤。

另外，当鼠标移到播放列表上任何歌曲时，会显示“标题/艺术家/唱片集/比特率”，建议加入选项，可以隐藏（不显示）这些信息，或者放在“状态栏”显示。主要是，这些信息弹出来，会干扰鼠标操作，比如遮盖右键菜单，反而造成不便。通常我们喜欢的歌曲也是自己熟悉的，这些信息并非那么重要，也不必每次鼠标掠过都要显示这些信息。

个人浅见，供参考，再次感谢你提供这么优秀的软件！

**Comment by zhongyang219** [comment]
已收到你的建议，会考虑在下个版本中增加这些选项

**Comment by zhongyang219** [comment]
功能已添加。
