### ISSUE TITLE
失去焦点页面暂停

### ISSUE THREAD

**Issue by subframe7536** [zhongyang219/MusicPlayer2#156]
rt，失去焦点后进度条、频谱和歌词都不会动，没有在更新中看到相关功能，请问作者大大这个问题怎么解决？

**Comment by lrisora** [comment]
需要失去焦点并且此时有其他程序在全屏/最大化状态，在另一个屏幕全屏也算
窗口会停止更新，本意是看不见时省些cpu
如果可能的话希望设置里可以选择一直绘制
在台式机等场合功耗不是太大的问题，还有被最大化的半透明编辑器窗口挡住时停下来很难受
我目前通过手动调整窗口大小（不使用最大化窗口）规避这个问题，不是很方便

**Comment by subframe7536** [comment]
> 需要失去焦点并且此时有其他程序在全屏/最大化状态，在另一个屏幕全屏也算
> 窗口会停止更新，本意是看不见时省些cpu
> 如果可能的话希望设置里可以选择一直绘制
> 在台式机等场合功耗不是太大的问题，还有被最大化的半透明编辑器窗口挡住时停下来很难受
> 我目前通过手动调整窗口大小（不使用最大化窗口）规避这个问题，不是很方便

感谢解答！另外还有些问题想请教一下
- 圆角按钮 这个选项勾选之后好像没有看到效果
- 播放列表可以选择把 曲目 列分为 标题 和 作者 两列吗
- 默认播放设备 似乎并不会跟随系统的改变二改变

**Comment by lrisora** [comment]
![屏幕截图 2021-03-20 133918](https://user-images.githubusercontent.com/43085437/111860322-baa39000-8981-11eb-994b-897aba1bddd9.png)
这些按钮变圆角

播放列表没有设置可以分成两列不过为什么需要？

#144

**Comment by subframe7536** [comment]
从功能上来说可能是没有必要，但是据我所知很多播放器都是将作者和标题分开的，合在一起看起来比较乱，分开可能观感好一点==

**Comment by lrisora** [comment]
我不是作者，以下是推测
感觉播放列表窗口或者说整个软件窗口都有针对下图的长条窗口特别改进过布局
此时如果横向分成两列那么空间利用显然不够合理，会出现某项的空间只够显示几个字同时大量出现空白
横向拆分`曲目`改为`艺术家`与`标题`几乎必然需要占用足够的横向空间才能达到比较好的效果
手机等竖屏同时显示基本上都会使用两行来显示`艺术家`与`标题`
但与手机不同，这个播放列表并没有太多变化注重实用，两行更加浪费空间
本来软件设计播放列表使用窗口右半部分就是让播放列表形成纵向条状，宽度不会超过半个屏幕
使用横向列表的软件布局基本上都有让播放列表拥有超过半个屏幕或整个屏幕的倾向

![屏幕截图 2021-03-20 142401](https://user-images.githubusercontent.com/43085437/111861335-533d0e80-8988-11eb-8a72-ae5d5580262f.png)

**Comment by zhongyang219** [comment]
目前的逻辑是当正在激活的窗口处于最大化状态时，界面会暂停刷新，目的是为了降低CPU利用率。但是目前可能没有处理多显示器的问题，当然原因是我并没有多台显示器用来测试。
