### ISSUE TITLE
更新设置

### ISSUE THREAD

**Issue by VNGVNGVNG** [zhongyang219/MusicPlayer2#157]
请问能不能搞成那种更新能直接整合到原始文件夹中的，而不是更新一次就要手动替换之前的exe文件。
拖了俩月之后更新了V2.72版本，但是替换exe文件后打开应用不能播放音乐，只能点击音乐文件来播放。
所以只能删掉之前的文件夹再安装新版本。

**Comment by zhongyang219** [comment]
更新之后不仅仅需要替换exe，压缩包里其他文件也应该替换。

**Comment by VNGVNGVNG** [comment]
> 更新之后不仅仅需要替换exe，压缩包里其他文件也应该替换。

我看着 除了playlists貌似其他的都没有变啊，还想保留时长统计等数据，
ps 居然忘记导出了

**Comment by zhongyang219** [comment]
时长等数据保存在song_data.dat文件中
