### ISSUE TITLE
搜不到歌词

### ISSUE THREAD

**Issue by zousizhe** [zhongyang219/MusicPlayer2#159]
没法搜在线歌词，也加载不了嵌入文件的歌词，不兼容千千静听嵌入的歌词，现在只能全用本地歌词了

**Comment by zhongyang219** [comment]
请附上无法读取歌词的音频文件，以便我调查你的问题，谢谢

**Comment by zhongyang219** [comment]
在千千静听中打开任意一个文件的文件属性，在写入类型中选择“ID3V2”，ID3编码类型选择“UTF16”，这样写入的歌词就能被MusicPlayer2正常读取了。
![image](https://user-images.githubusercontent.com/30562462/113548168-a74f2080-9621-11eb-8fd0-6c06d372129b.png)

**Comment by zhongyang219** [comment]
请详细描述一下你的关于“没法搜在线歌词”的问题，以便我调查你的问题。

**Comment by zousizhe** [comment]
> 请详细描述一下你的关于“没法搜在线歌词”的问题，刹车我调查你的问题。

发现问题了，是与我路由器的网易云音乐解锁插件有冲突，希望能增加个QQ音乐的歌词库

**Comment by xivi1839** [comment]
如果也加入可以自己手动搜索歌词就好了

**Comment by zhongyang219** [comment]
> 如果也加入可以自己手动搜索歌词就好了

@xivi1839 可以手动搜索啊，主菜单中“歌词”——“下载歌词”或者右键菜单中的“下载歌词”

**Comment by xivi1839** [comment]
> > 如果也加入可以自己手动搜索歌词就好了
> 
> @xivi1839 可以手动搜索啊，主菜单中“歌词”——“下载歌词”或者右键菜单中的“下载歌词”

谢谢老大

**Comment by rybzhh** [comment]
所有搜索都是显示没有网络，“在线查看”显示“网络连接失败或超时”；“下载专辑封面”“下载歌词”显示“搜索失败，请检查你的网络连接！”，这是什么原因？
