### ISSUE TITLE
cue多FILE标签支持 / 转换为mp3时写入标签异常

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#164]
不支持一个cue内多个FILE标签的情况，实际上这种情况并不少见，独立的音频文件没有标签，标签信息依赖cue提供

![屏幕截图 2021-04-11 173758](https://user-images.githubusercontent.com/43085437/114299787-c5b88e80-9aef-11eb-8f17-8cb769eec94d.png)

格式转换当目标格式为mp3时写入标签无法处理 `・` 字符会变成问号，转换为其他格式不会
经测试与字符来源无关（一般文件或cue）
手工编辑mp3可行，只是转换为mp3自动写入标签时标签内容会变问号
文件名正常，具体如图

![屏幕截图 2021-04-11 164000](https://user-images.githubusercontent.com/43085437/114299790-cbae6f80-9aef-11eb-8b09-2bc01e8b9409.png)

---

不重要的部分

浮动播放列表窗口不接受拖动添加歌曲但是会鼠标会变成添加歌曲的图标
希望浮动播放列表可以通过按ctrl+K关闭

在已有的播放列表添加文件夹选择osu!的Songs文件夹并没有像预想的一样增量添加歌曲（设置里选择了禁止添加相同曲目）而是提示歌曲已存在，允许添加相同曲目也无效，对空白播放列表也如此。

**Comment by zhongyang219** [comment]
完的成MP3之后`・`字符变成问题的问题是因为转换格时是通过LAME编码器将标签写入MP3文件的，它对Unicode的支持不好，这个比较容易解决，在转换时不使用LAME编码器，而是通过taglib写入标签即可解决。
