### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by SplitGemini** [zhongyang219/MusicPlayer2#173]
## 作为MusicPlayer2的忠实用户，提出一些改进建议如下：

* 添加媒体库目录可选包含子文件夹。同时媒体库文件夹和媒体库目录感觉有点重复，一个在设置里改，一个在媒体库里改，作用有点不明确。
建议给媒体库文件夹合并媒体库目录的功能（比如启动时自动更新），然后去掉媒体库目录设置。
![image](https://user-images.githubusercontent.com/34861918/116819018-cac5a680-aba0-11eb-8d57-c91e4650cb85.png)
![image](https://user-images.githubusercontent.com/34861918/116819041-dfa23a00-aba0-11eb-9b7d-1662c7305435.png)

* 添加重新加载媒体库数据功能或者自动识别已修改文件并更新数据。原因：比如修改了一些文件meta但是显示的数据不会自动更新。修改建议是把最新的文件的修改时间加进数据库，启动时更新比数据库修改时间更晚的文件。
* 补充媒体库点击列表分类栏排序。比如曲目数排序。修改建议：应该只是补充一些已有代码吧。
![image](https://user-images.githubusercontent.com/34861918/116819432-aec30480-aba2-11eb-8723-aedbb291de15.png)

**Comment by lrisora** [comment]
媒体库文件夹和媒体库目录不是同样的概念，功能不重复

你说的媒体库文件夹不是媒体库下属的文件夹而是是文件夹播放模式，是与播放列表对等的概念
用来表示一个特定的实际用来播放的集合，可以与播放列表在一定程度上互相代替
但是媒体库目录完全不同，有点类似windows中“库”的概念
媒体库目录用来告知软件软件需要负责的歌曲范围，用户应当把希望软件保存各种信息的歌曲存储位置全部加进来
清理媒体库时可以据此去除不想要的部分

**Comment by SplitGemini** [comment]
> 媒体库文件夹和媒体库目录不是同样的概念，功能不重复
> 
> 你说的媒体库文件夹不是媒体库下属的文件夹而是是文件夹播放模式，是与播放列表对等的概念
> 用来表示一个特定的实际用来播放的集合，可以与播放列表在一定程度上互相代替
> 但是媒体库目录完全不同，有点类似windows中“库”的概念
> 媒体库目录用来告知软件软件需要负责的歌曲范围，用户应当把希望软件保存各种信息的歌曲存储位置全部加进来
> 清理媒体库时可以据此去除不想要的部分

但是目前媒体库文件夹的表现除了没有自动更新文件以外是和媒体库目录一样的

**Comment by lrisora** [comment]
> 
> 
> > 媒体库文件夹和媒体库目录不是同样的概念，功能不重复
> > 你说的媒体库文件夹不是媒体库下属的文件夹而是是文件夹播放模式，是与播放列表对等的概念
> > 用来表示一个特定的实际用来播放的集合，可以与播放列表在一定程度上互相代替
> > 但是媒体库目录完全不同，有点类似windows中“库”的概念
> > 媒体库目录用来告知软件软件需要负责的歌曲范围，用户应当把希望软件保存各种信息的歌曲存储位置全部加进来
> > 清理媒体库时可以据此去除不想要的部分
> 
> 但是目前媒体库文件夹的表现除了没有自动更新文件以外是和媒体库目录一样的

这两个不一样
媒体库文件夹还是改叫文件夹播放模式吧，减少误解
媒体库是比较大的概念，整个“媒体库”窗口的所有标签页只不过是它的各种视图而已
现在软件为了易于使用没有把这个特性做得很明显，对于歌曲信息默认打开过就加入并且只增不减需要手动移除
这样照顾了完全不理解什么是媒体库也用不到的大多数用户
实际上如果检测到媒体库内歌曲不在媒体库目录列表就移除歌曲信息信息也不奇怪
只有在媒体库目录列表内的歌曲，软件才需要负责存储/更新信息
文件夹播放模式只是一种特殊的播放列表指示软件把哪些歌曲放一起播放，是外在的视图，理所应当不负责歌曲信息更新

要解释媒体库还是离不开windows 7开始出现的“库”
简单的说“库”是除了传统的目录树之外的另一种文件管理方案
不过当时windows对文件标签支持极差，基本上全部标签都读不出来或者乱码，这个功能推出就注定失败
普通用户不关心，有需求的用户都转向更专业的软件
一篇当时的旧文<https://www.iplaysoft.com/win7-library-introduce-pdf.html>
加上这个<https://www.zhihu.com/question/20125138>
MusicPlayer2实现的与“库”还是有区别的
这里的媒体库直接对应song_data.dat文件内的保存的歌曲信息
添加方法是打开新文件/启动时扫描更新媒体库目录
移除是清理媒体库手动移除

**Comment by SplitGemini** [comment]
我知道媒体库的含义，目前我是在想要媒体库能够包含子目录的时候发现，文件夹视图很累赘，不会自动更新，不如给播放列表添加从文件夹添加列表的功能。
同时添加文件夹也能在媒体库视图看到添加的所有文件信息，这难道不是和添加媒体库一样吗
同时现在也没有一个媒体库播放列表，就是包含媒体库所有媒体且会自动和媒体库同步的播放列表
总之是我其实就是想要媒体库能够包含子目录，衍生出的都是我可能我理解不到的功能

**Comment by zhongyang219** [comment]
* 通过外部修改了文件标签信息后媒体库中不会刷新的问题已经计划在下个版本中解决了。
* 关于你的第一个建议，你似乎没有理解媒体库中的文件夹和媒体库目录的含义，其实它们是完全不同的两个概念。
  * 媒体库中的”文件夹“里列出的是你最近在”文件夹模式“下播放过的文件，你可以快速地打开你最近播放过的文件夹，这里是可以包含子目录的，而且如果文件夹里的文件有更新的话，软件打开此文件时会自动更新里的文件的，因为在文件夹模式下，并没有保存文件的列表，而是在每次加载文件夹时自动扫描里面的文件。
  * 媒体库设置中的”媒体库目录“目前有两个作用：一个是在勾选了”启动时自动更新媒体库“时会在程序启动自动扫描设置的媒体库目录下的所有音频文件，获取其标签信息，并缓存到数据文件。另一个作用是用于设置”媒体库“——”文件夹浏览“中可以浏览的目录。
如果你不了解文件夹模式和播放列表模式的不同，可以[点击这里](https://github.com/zhongyang219/MusicPlayer2/wiki/%E6%96%87%E4%BB%B6%E5%A4%B9%E6%A8%A1%E5%BC%8F%E5%92%8C%E6%92%AD%E6%94%BE%E5%88%97%E8%A1%A8%E6%A8%A1%E5%BC%8F)查看它们的区别，你还可以[点击这里](https://github.com/zhongyang219/MusicPlayer2/wiki/%E5%AA%92%E4%BD%93%E5%BA%93)查看关于媒体库的说明。
* 如果你想要从文件夹创建播放列表，可以在”媒体库“——”文件夹浏览“中的左侧树中找到对应的文件夹，在右键菜单中选择”添加到新播放列表并播放“。如图所示：
![image](https://user-images.githubusercontent.com/30562462/116871473-e2f00100-ac46-11eb-80c5-6e9f286c6411.png)

**Comment by lrisora** [comment]
> 
> 
> 我知道媒体库的含义，目前我是在想要媒体库能够包含子目录的时候发现，文件夹视图很累赘，不会自动更新，不如给播放列表添加从文件夹添加列表的功能。
> 同时添加文件夹也能在媒体库视图看到添加的所有文件信息，这难道不是和添加媒体库一样吗
> 同时现在也没有一个媒体库播放列表，就是包含媒体库所有媒体且会自动和媒体库同步的播放列表
> 总之是我其实就是想要媒体库能够包含子目录，衍生出的可能都是我理解不了或者不会使用的问题

我推测是不是这样，

所有直接用来播放的列表都没有主动自动更新的能力（比如更新曲目数）
仅有的“媒体库->文件夹”也仅在手动打开时更新（实质是打开时建立）
唯一真正能够自动更新子文件夹的就只有“文件夹浏览”即媒体库目录，却不够方便，需要手动操作才能播放

如果以上猜测正确那么希望的功能大概是
1.  媒体库->文件夹 这里打开时显示列表里的文件夹自从上次打开后是否有更新，增加减少了多少歌
旁边的播放列表不点开也不会自动更新
2.  或者实现播放列表绑定文件夹（可以选择是否包含子文件夹）自动更新

一可以考虑，二不合适实现，播放列表绑定文件夹自动更新等于放弃播放列表编辑能力，不能编辑的列表有“文件夹”就够了

**Comment by SplitGemini** [comment]
@zhongyang219 @lrisora 感谢两位的解释，文件夹确实会自动更新新添加的文件，我想我大概知道他们的作用了
