### ISSUE TITLE
歌词下载失败

### ISSUE THREAD

**Issue by GhostNoc** [zhongyang219/MusicPlayer2#18]
## 版本
v2.66

## 错误
所有歌词无法下载，提示网络连接失败

**Comment by zhongyang219** [comment]
可能是软件发送http请求过于频繁导致的，我也出现过这个情况，过一段时间就好了，或者换一个IP，比如用手机开热点。为了避免这个问题，建议在选项设置——常规设置中关闭自动下载歌词和专辑封面的选项。
