### ISSUE TITLE
添加到播放列表

### ISSUE THREAD

**Issue by Kevinzgithub** [zhongyang219/MusicPlayer2#182]
添加到播放列表后，所选的歌曲并没有添加进去，试了很多次都不行，请问是我操作有问题吗？期待您的帮助，先谢谢您！

**Comment by lrisora** [comment]
> 
> 
> 添加到播放列表后，所选的歌曲并没有添加进去，试了很多次都不行，请问是我操作有问题吗？期待您的帮助，先谢谢您！


没发现问题，提问至少要描述到完全不了解的人能复现才够吧

参见[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

虽然没遇到描述的情况，不过还是猜一下，test里面正常有歌曲但是左边的时长以及总时间是上次关闭此列表时的，不会自动更新

![屏幕截图 2021-05-18 161408](https://user-images.githubusercontent.com/43085437/118616255-1b214300-b7f4-11eb-9b78-fa44a681f822.png)

**Comment by Kevinzgithub** [comment]
![01](https://user-images.githubusercontent.com/84002159/118636398-406b7c80-b807-11eb-81bf-7a606dea2266.PNG)
![02](https://user-images.githubusercontent.com/84002159/118636409-42cdd680-b807-11eb-8bd5-0fad3e71fa59.PNG)

**Comment by Kevinzgithub** [comment]
从上面这两张图，应该能说明白：在添加了“读你”这首歌到“我喜欢的音乐”这个播放列表后，“我喜欢的音乐”里面什么歌曲也没有。

**Comment by Kevinzgithub** [comment]
顺便说一下，歌曲都是在Z盘上，也就是在局域网里。另外我播放的是cue文件。我是想从cue文件里挑自己喜欢的歌曲，放到“我喜欢的音乐”播放列表里，但没能成功，期望得到帮助，谢谢

**Comment by lrisora** [comment]
抱歉，没想到是上个问题，这些是软件没有把Z盘当作合法目录导致的
已改正的版本 2ed63ee277500f12079a93ed3f93cbb7a3da0ff2 ，解压替换对应exe文件，可以试一试
[MusicPlayer2_2ed63e.zip](https://github.com/zhongyang219/MusicPlayer2/files/6500698/MusicPlayer2_2ed63e.zip)

**Comment by Kevinzgithub** [comment]
非常感谢！
