### ISSUE TITLE
“添加文件”这个按钮被锁住了

### ISSUE THREAD

**Issue by Kevinzgithub** [zhongyang219/MusicPlayer2#183]
![捕获](https://user-images.githubusercontent.com/84002159/118824299-530bb180-b8ec-11eb-8145-8116ab3f5178.PNG)

悬浮窗播放列表上面的“添加文件”这个按钮被锁住了，没办法往里添加歌曲

**Comment by lrisora** [comment]
文件夹模式根据选定文件夹建立自动播放列表，此列表与文件夹内容同步，无法编辑
能够编辑的是播放列表，播放列表可以添加处于不同目录的歌曲但是不会自动更新，所有更改手工进行

**Comment by Kevinzgithub** [comment]
现在明白了。我说怎么回事呢，我记得前天还可以添加，怎么突然就不能添加了，原来我是在文件夹模式。非常感谢！


     On Wednesday, May 19, 2021, 10:51:57 PM GMT+8, lrisora ***@***.***> wrote:  
 
 


文件夹模式根据选定文件夹建立自动播放列表，此列表与文件夹内容同步，无法编辑
能够编辑的是播放列表，播放列表可以添加处于不同目录的歌曲但是不会自动更新，所有更改手工进行
