### ISSUE TITLE
翻译的中文歌词没显示出来

### ISSUE THREAD

**Issue by Kevinzgithub** [zhongyang219/MusicPlayer2#185]
下面这种格式的歌词里，翻译的中文在动态歌词里没有显示出来：

[00:30.42]different faces different names / 有着不同的面庞和姓名

期望在下个版本里得到解决，先谢谢您啦

**Comment by lrisora** [comment]
不知道出处是哪里，随便用一首测试了一下，格式正确显示正常，没发现问题

![屏幕截图 2021-05-21 141923](https://user-images.githubusercontent.com/43085437/119091487-bc500980-ba3f-11eb-8e71-948d5f4679fb.png)

在MusicPlayer2里歌词中的`<空格><半角斜杠><空格>`是特别的，用来分割歌词和与之对应的翻译
翻译部分由是否显示歌词翻译选项独立控制
不想触发这个特性可以用不会识别的全角斜杠替换`／`，或者去掉空格

![屏幕截图 2021-05-21 143102](https://user-images.githubusercontent.com/43085437/119092944-a5aab200-ba41-11eb-9249-a9bc9ccb3711.png)


如果问题不在这里那么需要能复现问题的文件

**Comment by Kevinzgithub** [comment]
谢谢您的回复！我找一首能正常显示的歌，对比一下，看看是什么问题

     On Friday, May 21, 2021, 02:36:30 PM GMT+8, lrisora ***@***.***> wrote:  
 
 


不知道出处是哪里，随便用一首测试了一下，格式正确显示正常，没发现问题



在MusicPlayer2里歌词中的<空格><半角斜杠><空格>是特别的，用来分割歌词和与之对应的翻译
翻译部分由是否显示歌词翻译选项独立控制
不想触发这个特性可以用不会识别的全角斜杠替换／，或者去掉空格



如果问题不在这里那么需要能复现问题的文件

**Comment by Kevinzgithub** [comment]
终于搞明白了，是“显示歌词翻译”那个选项让我不小心去掉了。重新点选上，就可以正常显示了。耽误您时间了
