### ISSUE TITLE
播放列表总时长

### ISSUE THREAD

**Issue by Kevinzgithub** [zhongyang219/MusicPlayer2#186]
如果播放列表能加一个总时长计算就好了，希望采纳，谢谢

**Comment by zhongyang219** [comment]
这不是有总时长吗：
![image](https://user-images.githubusercontent.com/30562462/119166347-14632c00-ba91-11eb-9804-cb6ae09e68cb.png)

**Comment by Kevinzgithub** [comment]
我说的是歌单里所有歌曲加起来的时间，这样就知道一个歌单要播多长时间了。不知道这个功能可不可以实现。先谢谢了

**Comment by Kevinzgithub** [comment]
我明白了，非常感谢！

**Comment by Kevinzgithub** [comment]
wav文件太大了，上传不了。我看下有没有别的办法上传。

 

    On Saturday, May 22, 2021, 12:03:53 AM GMT+8, zhongyang219 ***@***.***> wrote:  
 
 


这不是有总时长吗：
