### ISSUE TITLE
歌词颜色

### ISSUE THREAD

**Issue by Kevinzgithub** [zhongyang219/MusicPlayer2#195]
我把歌词背景设置成黑色，歌词设置成白色，但歌词的颜色总是有点灰蒙蒙的，不是纯白色。而且歌词的分辨率不是很高。这个有办法解决吗？先谢谢您！

**Comment by lrisora** [comment]
桌面歌词的颜色没问题，设置什么就是什么，如果你指的是字体边缘的阴影，参见 #62 .
桌面歌词是透明窗口为了保证文字显示效果有必要加阴影。
歌词分辨率我这里就是一般windows程序的水准，没什么异常，windows的字体渲染本来就不怎么样系统程序的字也很糊，如果分辨率异常低的话发张截图看看。

**Comment by Kevinzgithub** [comment]
明白了，谢谢您的回复

**Comment by zhongyang219** [comment]
截图发上来看看

**Comment by Kevinzgithub** [comment]
![捕获](https://user-images.githubusercontent.com/84002159/120418152-95c09580-c392-11eb-9d95-d23ad20f6ae5.PNG)

**Comment by lrisora** [comment]
我有所误解，原来指的是深色模式，这里本来就设计为并非将亮度降为0，设计上除了OLED上为了省电外基本上是不会使用纯黑色的。各种夜间模式（oled除外）都不会使用纯黑色而是深灰色。
非要做的话可以关闭使用歌曲封面做背景并自定义一张黑色图片。
字的颜色是根据主题色调节亮度生成的一组颜色，在软件各处都有使用。
至于分辨率放大后看起来和标题栏上的字差不多 ~可能这就是windows的风格~。
有个叫[MacType](https://www.mactype.net/)的软件可以接替系统的字体渲染实现更好的效果，多年前折腾过。
<https://www.zhihu.com/question/49223658>
