### ISSUE TITLE
关于歌词格式处理的建议

### ISSUE THREAD

**Issue by Ai-desu-2333** [zhongyang219/MusicPlayer2#196]
怎么找到本软件，怎么激动就略过了。。。
本人保存在本地的歌曲，其标签全部使用[MusicTag](https://www.cnblogs.com/vinlxc/p/11347744.html)将网易云音乐作为源进行过处理，歌词，专辑图片也如此；
有些带翻译的外文歌词，其保存格式如下：

> [00:00.95]眠らない夜空に星散りばめて
> [00:00.95]不眠的夜空中镶嵌着星光
> [00:04.49]くるくる目が回るまで踊ろう
> [00:04.49]咕噜咕噜天旋地转的起舞
> [00:08.18]いたずらに世界を変えてしまうの
> [00:08.18]恶作剧得将世界改变吧
> [00:12.01]今夜だけは私たち二人で
> [00:12.01]今晚只有我们两个人唷

![image](https://user-images.githubusercontent.com/61218958/120519484-3d76ab80-c405-11eb-8648-42a2646fed93.png)

原文与翻译为同一时间的两行内容，因为不符合 _[原文] / [翻译]_ 的格式，导致软件无法正常识别为带翻译的歌词，显示上就会出现一些问题（跳行），希望本软件能增加对这种格式歌词的识别，互转/转换 功能。

PS：MusicTag可以设置保存歌词格式，之前一直使用其他播放器播放，歌词使用上述格式保存会显示双行歌词，使用连接符方式保存会让歌词单行显示（不美观）；现在已经更改MusicTag的保存格式，但是之前处理过的歌曲想要使用MusicTag再次处理较为麻烦（需要重新匹配，某些匹配不准确项目还需要再次手动处理）所以才希望本软件可以增加对此种歌词格式的支持。
![image](https://user-images.githubusercontent.com/61218958/120520699-b0cced00-c406-11eb-84d7-0dc586695260.png)

另外，本人在多显示器环境下全屏使用本软件，也遇到了与[#109](https://github.com/zhongyang219/MusicPlayer2/issues/109)相同的问题，不知道开发者大大能否修复一下

**Comment by zhongyang219** [comment]
你好，你的这个问题其实我早就考虑到了，在“编辑歌词”对话框的菜单栏中选择“编辑”-“合并时间标签相同的歌词”，就能转换成MusicPlayer2能正常识别的翻译格式了。详细说明可以参见[wiki页面-编辑歌词](https://github.com/zhongyang219/MusicPlayer2/wiki/编辑歌词)。

**Comment by zhongyang219** [comment]
后面我再想想怎么支持原文与翻译为同一时间的两行歌词的识别吧

**Comment by Ai-desu-2333** [comment]
> 你好，你的这个问题其实是我编辑的考虑到了，在“歌词”的菜单选择“编辑”——“合并时间标签”的歌词一样，可以正常转化成MusicPlayer2能识别的翻译格式了。详细说明可以参见[wiki页面-编辑歌词](https://github.com/zhongyang219/MusicPlayer2/wiki/%E7%BC%96%E8%BE%91%E6%AD%8C%E8%AF%8D)。

已找到，感谢

**Comment by zhongyang219** [comment]
你好，这个问题现在已经解决，使用这个版本替换即可：
[MusicPlayer2.zip](https://github.com/zhongyang219/MusicPlayer2/files/6599723/MusicPlayer2.zip)

**Comment by Ai-desu-2333** [comment]
> 你好，这个问题现在已经解决，使用这个版本替换即可：
> [MusicPlayer2.zip](https://github.com/zhongyang219/MusicPlayer2/files/6599723/MusicPlayer2.zip)

Nice!
