### ISSUE TITLE
可否独立出歌词下载器？

### ISSUE THREAD

**Issue by Crystal-RainSlide** [zhongyang219/MusicPlayer2#2]
比如，MP3 播放器上只需要歌词下载器（和已经满大街的格式转换软件、MP3 tag 编辑…）
本来有 https://github.com/GameBelial/ZonyLrcTools ，但这玩意版本混乱中，最新版编译失败，又没有官方 Release。
看下来，歌词下载器的代码和主模块牵扯得比较多，而我也没有时间和水平动刀了…

**Comment by zhongyang219** [comment]
如果要把歌词下载功能独立出来，就算对我来说，也是一项比较繁琐的工作的。确实，歌词下载的代码跟主模块联系比较紧密，主要在于，歌词下载需要先获取歌曲的标签信息，而获取标签信息则需要用到BASS音频库的API（虽然BASS音频库的API只是告诉你标签信息是从哪里开始的，然后返回一个指针，而具体获取标签仍然需要自己通过代码实现）。
这个等我有空的时候再去做一个吧。其实我想找一个第三方的获取音频文件标签信息的库，因为我自己写的获取音频文件标签的代码（主要是获取MP3 ID3V2标签部分）不够完善。

**Comment by Crystal-RainSlide** [comment]
这样的话，要是像快点做出来就只能…暂时不做自动获取标签的功能 :face_with_head_bandage: 
Tag 的库… https://www.mp3tag.de/en/ 除 tak decoder 以外是没有可见的库的。得看看别的。

**Comment by Crystal-RainSlide** [comment]
https://www.xdlab.ru/en/ 使用了 Bass

**Comment by Crystal-RainSlide** [comment]
http://id3.org/Developer%20Information http://www.cdtag.com/ :
http://www.idsharp.com/

**Comment by Crystal-RainSlide** [comment]
Other stuff on GitHub:
https://github.com/larsbs/id3v2lib
https://github.com/squell/id3

**Comment by Crystal-RainSlide** [comment]
https://mediaarea.net/en/MediaInfo/Download/Windows
Mediainfo 也有 dll
……还是蛮少的。

**Comment by zhongyang219** [comment]
我最近更新了新的版本，改进了获取MP3标签的代码。
我后来想了一下还是决定不做单独的歌词下载软件了。一个是我觉得没必要，另一个是我希望你们能看到这个播放器其他好用的地方，而不希望你们仅仅关注它的歌词下载功能，甚至还想精简掉“无用的”音乐播放功能，只保留歌词下载功能。
