### ISSUE TITLE
关于媒体库只扫描选中文件夹根目录而不扫描其子文件夹的问题

### ISSUE THREAD

**Issue by MurasameYukiya** [zhongyang219/MusicPlayer2#204]
如题，因个人喜好将所有歌曲文件按”歌手/专辑/歌曲“的方式保存，但是MusicPlayer2只扫描选中的文件夹根目录里的内容，并不扫描其子文件夹里的内容，那么要使用MusicPlayer2我就要把歌曲文件全部放在一个文件夹的根目录内。希望可以增加一个对单个文件夹及其子文件夹的内容一起扫描的选项。

**Comment by lrisora** [comment]
媒体库左侧的“文件夹”视图可选是否包含子文件夹。
![圖片](https://user-images.githubusercontent.com/43085437/122763311-c3816600-d2d0-11eb-863a-5808f638412f.png)

右侧的文件夹浏览默认包含子文件夹。

**Comment by MurasameYukiya** [comment]
> 媒体库左侧的“文件夹”视图可选是否包含子文件夹。
> ![圖片](https://user-images.githubusercontent.com/43085437/122763311-c3816600-d2d0-11eb-863a-5808f638412f.png)
> 
> 右侧的文件夹浏览默认包含子文件夹。

看见了，我是瞎子🤣
