### ISSUE TITLE
标签编辑无法保存

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#205]
[test.zip](https://github.com/zhongyang219/MusicPlayer2/files/6686702/test.zip)
[test1.zip](https://github.com/zhongyang219/MusicPlayer2/files/6686711/test1.zip)
这个功能少用，折腾编码时发现的，Mp3Tag正常编辑。
用Mp3Tag保存一次后标签编辑就会恢复正常（流派还是非标准或未知）。
本地绝大部分网易下的都能复现。
和流派无关，过去只编辑过那些编码有问题的歌，正常可用。
这些网易下的都有问题。

**Comment by zhongyang219** [comment]
我知道问题出在哪了，因为文件被设置成了只读属性，把只读去掉就好了。
![image](https://user-images.githubusercontent.com/30562462/123108240-d5980b80-d46c-11eb-91a0-6cd57dfa4303.png)

**Comment by lrisora** [comment]
了解
