### ISSUE TITLE
搜索框不显示歌词

### ISSUE THREAD

**Issue by AcquireKnown** [zhongyang219/MusicPlayer2#22]
![image](https://user-images.githubusercontent.com/32730772/71257807-a1232b00-236f-11ea-8c24-3bb7ae9621a9.png)

**Comment by zhongyang219** [comment]
你需要在”选项设置“——”歌词设置“中将”允许在Cortana搜索框中显示播放信息“才能显示：
![无标题](https://user-images.githubusercontent.com/30562462/71302242-f436c580-23e3-11ea-9f0a-d41b4fd78318.png)
