### ISSUE TITLE
文件夹模式下播放cue文件，退出后再次打开无法记住上次播放的曲目

### ISSUE THREAD

**Issue by zhongyang219** [zhongyang219/MusicPlayer2#221]
如下图所示，在播放第8首曲目时退出程序，再次启动时m_index_emp的值为7。
![image](https://user-images.githubusercontent.com/30562462/125154995-93bad500-e18f-11eb-8d7c-4e97c6c6038f.png)
![image](https://user-images.githubusercontent.com/30562462/125154980-8271c880-e18f-11eb-9f0a-0277d0cf16b0.png)
执行CAudioCommon::GetCueTracks后m_index_emp的值变成了26？
![image](https://user-images.githubusercontent.com/30562462/125155029-d4b2e980-e18f-11eb-971a-2de21e040338.png)
而播放列表里曲目总数只有20个。
@lrisora 这个问题是在 https://github.com/zhongyang219/MusicPlayer2/pull/191 之后引入的。

**Comment by lrisora** [comment]
写的时候没考虑这个情况，因为部分资源有这样的文件结构，误以为不会出现文件夹模式开cue。
我这样想不对，毕竟还有文件夹浏览。
![圖片](https://user-images.githubusercontent.com/43085437/125162198-21f78100-e1b9-11eb-82f4-b93bde46d80f.png)

目前GetCueTracks认为m_index_tmp指向的是m_playlist中解析前想要播放的曲目，并在解析前后维持其不变。
文件夹模式m_index_tmp指向的是m_playlist解析后其中想要播放的曲目。
不需要在重新解析时改动m_index_tmp。因为m_index_tmp本就对应解析后的m_playlist。

我没用过文件夹模式，不是很熟。
上面传来m_index_tmp表示当前播放，信息量可能有些不足。
如果文件夹内容变化或者播放列表在软件外发生编辑都可能错位。
传一个SongInfo也不够（目前播放列表有可能允许重复）。

现在这样在不考虑外部编辑的情况下正常运行。
GetCueTracks的复杂性大部分来自对播放列表允许重复的支持如果可以取消会简单很多。

**Comment by zhongyang219** [comment]
好的，明白了，也就是说上次的改动仅针对播放列表模式，文件夹模式不需要在函数内修改m_index_tmp的值
