### ISSUE TITLE
Windows11闪退

### ISSUE THREAD

**Issue by wukong999** [zhongyang219/MusicPlayer2#235]
Windows可以打开软件，但是一点击播放之后就会卡死，然后闪退。

**Comment by zhongyang219** [comment]
这个问题应该是由于你开启了“允许在任务栏搜索框中显示播放信息”导致的，如图：
![image](https://user-images.githubusercontent.com/30562462/130229661-67075864-1b04-4109-a059-c7eab6e1fdc9.png)
在Windows11中，微软已经把任务栏搜索框砍掉了，因此这个功能在Windows11中已经无法使用，在播放前去掉这个勾选可以解决问题。闪退的问题会在Windows11正式发布后解决。

**Comment by wukong999** [comment]
果然取消了这个选项就好了，谢谢

**Comment by zhongyang219** [comment]
问题已经解决。
