### ISSUE TITLE
想问下大佬有没有改善下日语歌词匹配的想法

### ISSUE THREAD

**Issue by aumk** [zhongyang219/MusicPlayer2#24]
一连串没有匹配也太惨了
1600首匹配到了37个歌词，惨😂

**Comment by zhongyang219** [comment]
歌词匹配调用的网易云音乐的接口，如果网易云音乐上没有这首歌或者已下架，就匹配不到歌词。

**Comment by aumk** [comment]
> 歌词匹配调用的网易云音乐的接口，如果网易云音乐上没有这首歌或者已下架，就匹配不到歌词。

歌曲确实都是从网易云音乐直接下载的，而且前两天刚下载的，下架的我也没法下载😂
1600首匹配到37首还是有点不对劲，我用的Android上的一个软件也是这种情况，永远匹配不到对的歌词。我怀疑是不是网易的接口有什么问题

**Comment by aumk** [comment]
> 歌词匹配调用的网易云音乐的接口，如果网易云音乐上没有这首歌或者已下架，就匹配不到歌词。

抱歉大佬，刚刚重新试了下，好像又好了，不知道为什么😂明明也没升级软件
