### ISSUE TITLE
关于Win10浅色模式图标底色问题

### ISSUE THREAD

**Issue by YuI2333** [zhongyang219/MusicPlayer2#242]
如图，在 Win10 21H1 下，固定到开始屏幕的图标底色是黑色，不知有啥解决方案吗
![53_31](https://user-images.githubusercontent.com/26202875/130863131-d23967c0-d914-4b5c-b560-e6c6f95d9976.png)

**Comment by zhongyang219** [comment]
请从release页面重新下载Musicplayer2发行版的压缩包，你应该缺少了如楼上图中所示的文件。
