### ISSUE TITLE
建议：主窗口设置透明度时能够选择保持专辑封面依旧不透明

### ISSUE THREAD

**Issue by OriBeta19** [zhongyang219/MusicPlayer2#247]
主窗口的其他部分都是符号/文字，加上透明效果之后影响相对较小。
但是专辑封面本身就是图片，在透明度不太低时与下层界面叠加起来感觉不太好看？
个人审美观点，仅作建议~

**Comment by lrisora** [comment]
确实如此，不过这个窗口透明是windows提供的功能，仅能够窗口整体调整，自己实现部分透明复杂度太大并非必须，目前大概不会实现。

**Comment by OriBeta19** [comment]
> 确实如此，不过这个窗口透明是windows提供的功能，仅能够窗口整体调整，自己实现部分透明复杂度太大并非必须，目前大概不会实现。

了解了，感谢回复！
