### ISSUE TITLE
转换格式勾选采样频率时报错“bassmix.dll丢失或损坏”

### ISSUE THREAD

**Issue by OriBeta19** [zhongyang219/MusicPlayer2#250]
然后我去dll-files.com上找了最新的bassmix.dll放在了MusicPlayer2/Encoder/里，重启了软件，依然没有用

**Comment by zhongyang219** [comment]
请到release页面重新下载Musicplayer2的发行版压缩包。从网上下载的dll应该是32位的，如果你用的是64位的Musicplayer2是不能使用的。
