### ISSUE TITLE
双击软件界面大部分地方会在剪贴板中写入 UI Static

### ISSUE THREAD

**Issue by vvyoko** [zhongyang219/MusicPlayer2#263]
如图所示
![1](https://user-images.githubusercontent.com/2145741/135224901-5ad29adc-ceb5-4f23-97d0-303723dc9ab1.jpg)

另外希望播放列表有专门的 媒体库 列表
这个列表不能自定义增减，会显示媒体库中的所有文件（代表只要在代码中显示媒体库中所有文件就行）
用途是播放列表会跟随媒体库更新自动增减文件
目前没找到好办法播放媒体库所有文件
每次媒体库更新时去所有曲目中选中所有文件然后添加到播放列表也太不优雅了

播放列表有个文件夹模式会自动增减文件，但是这个并不能代表媒体库所有文件。

另外这个地方可能会给人误导性？
这个地方只是用于提示当前的播放列表，并不能用于切换或操作播放列表
为什么不直接显示为 文本
现在这样显示为 “编辑框” 又不能操作感觉比较奇怪
只能选中，然后只能复制，这有什么特殊作用吗。
![2](https://user-images.githubusercontent.com/2145741/135226838-51bb4598-0ace-4788-b9cd-7733a91186c8.jpg)

**Comment by zhongyang219** [comment]
感谢反馈，这个问题确实存在，正在调查中
