### ISSUE TITLE
关闭后开启会变为初始状态，应该怎么解决

### ISSUE THREAD

**Issue by 2-Sakura** [zhongyang219/MusicPlayer2#278]

**Comment by 2-Sakura** [comment]
![image](https://user-images.githubusercontent.com/83262960/143872598-2061159d-dbb4-47f8-bf25-3b29ab4de8eb.png)

**Comment by sbwfnhn** [comment]
安装路径权限不够？还是用户权限不够。

**Comment by 2-Sakura** [comment]
> 安装路径权限不够？ 还是用户权限不够。

尝试换一个安装路径，解决了，谢谢
