### ISSUE TITLE
会使用热键失效

### ISSUE THREAD

**Issue by sbwfnhn** [zhongyang219/MusicPlayer2#279]
我用的是微软自带的五笔，没有禁用shift+space功能，也就是五笔无法禁用全角半角快捷键，微软拼音可以，所以我用AutoHotkey写了个禁用热键。脚本如下：
```
<+Space::Send, {Shift}
```
功能使用一直都正常。

但是每次打开musicPlayer2，都会让我的这个禁用热键失效，必需重启autoHotkey脚本才能重新生效。
用OpenArk64.exe查看当前系统热键，也没有发现冲突。

热键截图如下：
```
https://raw.githubusercontent.com/sbwfnhn/logs/main/1111.png
```
这是什么原因导制的。

**Comment by sbwfnhn** [comment]
经检测验证，是由 “启用全局多媒体快捷键”这个功能引起的，只要打勾，就会故障重现。

**Comment by sbwfnhn** [comment]
不知道这个“启用全局多媒体快捷键”具体作用是什么，关闭“启用全局多媒体快捷键”，键盘上的多媒体快捷键还是能用。

**Comment by zhongyang219** [comment]
“启用全局多媒体快捷键”使用了SetWindowsHookEx函数截获了多媒体按键消息，应该是这个功能导致了这个问题，现在已经改用系统多媒体控制接口来实现使用多媒体按键控制音乐播放的功能，这个问题已经不会出现了，请等待下个版本更新

**Comment by sbwfnhn** [comment]
新版本已正常
