### ISSUE TITLE
1自动检测修复工具箱。2快速文件优化，快速监控、添加、删除。

### ISSUE THREAD

**Issue by Chilled-ops** [zhongyang219/MusicPlayer2#28]
1自动修复工具箱，对常用问题，自动检测并修复。

2快速文件优化，快速监控，快速添加（随时自动快速更新文件夹内和软件内的改动），快速删除，包括希望文件整理能更快，添加全局热键我绑定鼠标手势用。

补充：磁盘删除音乐文件到回收站，而不是直接彻底删除。这样随时删除优化音乐库，而不是越来越臃肿。

**Comment by zhongyang219** [comment]
目前并没有计划增加诸如“自动修复工具箱”之类的功能。
媒体库中选中一个曲目可以在右键菜单中选择“从磁盘删除”，文件会被移动到回收站。
按Ctrl + Shift + Del键可以将正在播放的文件删除到回收站。
