### ISSUE TITLE
对蓝牙耳机按键无响应

### ISSUE THREAD

**Issue by Gokou-Ruri** [zhongyang219/MusicPlayer2#289]
MusicPlayer2似乎不支持蓝牙耳机的按键？例如播放/暂停、上/下曲等等。
Windows 10本身是支持的，例如自带的音乐播放器、UWP版QQ音乐等播放器均可以正确响应。

**Comment by zhongyang219** [comment]
目前已经增加了系统多媒体控制接口的支持，请等待下个版本更新

**Comment by zhongyang219** [comment]
新版本已支持。
