### ISSUE TITLE
一首歌一个文件：封面略大于歌词，一切内置。

### ISSUE THREAD

**Issue by Chilled-ops** [zhongyang219/MusicPlayer2#29]
软件自带的下载音乐封面是内置到音乐文件里面的吗？封面的优先级略大于歌词，没有人关心歌词，只关心好不好听，音乐就是好不好听，就像玩游戏好不好玩一样，看封面的时间比看歌词多，而且经常一打开就看到封面。

不想要太多文件，一首歌一个文件足以，如果都能内置到一个文件就好了。

**Comment by liucin** [comment]
> 软件自带的下载音乐封面是内置到音乐文件里面的吗？封面的优先级略大于歌词，没有人关心歌词，只关心好不好听，音乐就是好不好听，就像玩游戏好不好玩一样，看封面的时间比看歌词多，而且经常一打开就看到封面。
> 
> 不想要太多文件，一首歌一个文件足以，如果都能内置到一个文件就好了。

这个应该可以通过往歌里边添加标签实现的，内置不内置应该有个可选项更合理

**Comment by zhongyang219** [comment]
最新版本中增加了标签和专辑封面编辑的功能，可以把专辑封面嵌入到音频文件。

**Comment by SamToki** [comment]
个人推荐使用「Mp3tag」管理音乐库，可以嵌入专辑图至音频文件（众多功能之一）。LRC歌词是无法嵌入音频文件的，所以鄙人习惯一首曲目1或2个文件。
