### ISSUE TITLE
歌词提前0.5s时可能发生的奇怪情况

### ISSUE THREAD

**Issue by lifegpc** [zhongyang219/MusicPlayer2#296]
```lyric
[00:00.00]Test
[00:00.52]Test2
[00:03.54]Test3
```
上述测试歌词，提前0.5s后会变为
```lyric
[00:00.52]Test
[00:00.02]Test2
[00:03.04]Test3
```

**Comment by lrisora** [comment]
没错，我计划过使用毫秒值替换当前歌词时间系统，同时处理这个问题。不过目前还没写 （写了一半发现太复杂删了）

2022年1月24日(月) 11:21 lifegpc ***@***.***>:

**Comment by lifegpc** [comment]
看上去是Time类无法处理负数的时间

**Comment by lrisora** [comment]
不过问题比看上去复杂，需要引入两个时间值，一个ms一个Time，来避免调反了往回退时发生信息损失

2022年1月24日(月) 11:32 lifegpc ***@***.***>:

**Comment by lifegpc** [comment]
貌似要大改代码
ffmpeg和MPC-HC内部都是存`int64_t`(单位都是1s对应10000000)，然后再要用到多少s之类的时候才会调用对应的函数
![image](https://user-images.githubusercontent.com/41434272/150714425-95d535e0-b98b-4b33-b366-50d76b08d5a6.png)
![image](https://user-images.githubusercontent.com/41434272/150714511-e565a57d-2f81-4fd4-a833-55aac51a1348.png)
这个是mpc-hc使用的转换函数，DVD_HMSF_TIMECODE是Windows头文件里定义的

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/150715025-967bb1f9-cc02-4db1-a94c-82fedc2a6fdc.png)
是负数的问题

**Comment by lifegpc** [comment]
我先把负数给支持了，这问题至少修复了
