### ISSUE TITLE
对视频文件的音乐播放支持

### ISSUE THREAD

**Issue by ErrorPower2001** [zhongyang219/MusicPlayer2#298]
一些网络歌曲只有可下载的视频版本，能否制作对常用流行视频文件的音乐播放支持？

**Comment by lifegpc** [comment]
这个我觉得有2种方式可以实现。
* 一种方式是写一个[DirectShow](https://docs.microsoft.com/en-us/windows/win32/directshow/directshow)内核(与MCI类似，但是提供了更多的接口)，存在的问题就是Windows本身的解码器不够多，很多格式需要安装开源的[LAVFilters](https://github.com/Nevcairiel/LAVFilters) (LAVFilters 大多数格式是调用ffmpeg来解码) 
这样会导致支持的文件格式会随着用户的安装情况而发生变化。
* 第二种方式就是自己调用ffmpeg解码，然后调用渲染器。这样可以编译一个较为简洁的ffmpeg来提供常见格式的支持

**Comment by lifegpc** [comment]
大致看了一下DirectShow的文档和MPC-HC的实现
还是第二种方式可以做到类似bass core的效果

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/151907750-15b9c41e-4624-4028-9fa1-c6ab19c0f1ac.png)
看上去可以

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/151932821-9c901ff9-3ac6-4d49-8640-a7a1d66a7c1d.png)
实现了

**Comment by ErrorPower2001** [comment]
> ![image](https://user-images.githubusercontent.com/41434272/151932821-9c901ff9-3ac6-4d49-8640-a7a1d66a7c1d.png) 实现了

感谢采纳提议
