### ISSUE TITLE
自定义界面A-B重复按钮出现在桌面歌词按钮上部

### ISSUE THREAD

**Issue by lifegpc** [zhongyang219/MusicPlayer2#303]
版本： 85f9c2e (master分支)
XML
![image](https://user-images.githubusercontent.com/41434272/151682208-ca4696c0-e5b0-49d3-867d-acda2a842080.png)
界面
![image](https://user-images.githubusercontent.com/41434272/151682214-b6485853-6cfd-4f90-b3c1-adab6b75ea9f.png)
![image](https://user-images.githubusercontent.com/41434272/151682220-88223653-6630-4de1-8084-ac6df7f46eeb.png)

**Comment by lifegpc** [comment]
发现问题了
switch case 漏了一个break;

**Comment by zhongyang219** [comment]
感谢反馈，这个问题确实存在，正在调查中

**Comment by lifegpc** [comment]
就是漏了break;的问题
![image](https://user-images.githubusercontent.com/41434272/151683503-85689027-8927-4949-867c-1949352b14fd.png)
加上去就好了

**Comment by lifegpc** [comment]
@zhongyang219 
我发现最近（向上）的一个text元素会影响到button元素的文本大小
例如text元素的font_size为9时
![image](https://user-images.githubusercontent.com/41434272/151684103-071bac77-2d1a-42c5-90aa-d92349e427c6.png)
![image](https://user-images.githubusercontent.com/41434272/151684156-1777fe08-a7a5-4c38-999d-00f83a06a390.png)
改为10之后
![image](https://user-images.githubusercontent.com/41434272/151684172-e5202e65-64a4-4ddf-9aa6-124132fc196a.png)
![image](https://user-images.githubusercontent.com/41434272/151684169-22bc8563-f587-4c25-aa71-57910a86fb3c.png)

**Comment by zhongyang219** [comment]
> @zhongyang219 我发现最近（向上）的一个text元素会影响到button元素的文本大小 例如text元素的font_size为9时 ![image](https://user-images.githubusercontent.com/41434272/151684103-071bac77-2d1a-42c5-90aa-d92349e427c6.png) ![image](https://user-images.githubusercontent.com/41434272/151684156-1777fe08-a7a5-4c38-999d-00f83a06a390.png) 改为10之后 ![image](https://user-images.githubusercontent.com/41434272/151684172-e5202e65-64a4-4ddf-9aa6-124132fc196a.png) ![image](https://user-images.githubusercontent.com/41434272/151684169-22bc8563-f587-4c25-aa71-57910a86fb3c.png)

感谢反馈，由于设置完字体后没有恢复成原来的字体导致的，问题已修正。
