### ISSUE TITLE
播放太多后崩溃

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#308]
通过双击播放列表项目 / N键 / 多媒体键（等效）切换1000次播放左右就会崩溃
先是背景加载不出来（黑色），再下一曲几首就直接卡停不动
不动时任务管理器中MusicPlayer2已经消失，窗口还会存在一会
![屏幕截图 2022-02-03 195739](https://user-images.githubusercontent.com/43085437/152341079-2b9c0302-d6f2-4918-9f62-e51b8e6a0080.png)

注：程序刚启动时的内存占用是91M，随着下一曲逐渐增加

注意左下角，

下面是正常情况

![屏幕截图 2022-02-03 194921](https://user-images.githubusercontent.com/43085437/152341354-3c33881e-3e81-4535-9f66-9fab5af12707.png)

**Comment by zhongyang219** [comment]
感谢反馈，看起来是GDI句柄泄漏的问题。从任务管理器中可以看出每切换一次歌曲GDI句柄就会增加：
![image](https://user-images.githubusercontent.com/30562462/152463442-dc475906-15f6-4736-a1b6-723f5b1a751d.png)
GDI句柄增加到一定程度后就会崩溃。目前正在调查中

**Comment by zhongyang219** [comment]
目前可以确认2021年8月12号发布的2.73版本是没有这个问题的，现在只能从提交历史记录中查找可能的问题了

**Comment by zhongyang219** [comment]
我找到问题在哪了，看来是反复向菜单设置图标会导致GDI句柄泄漏，注释掉图中红框那行代码就没有问题了，但是这样下拉菜单中就没有图标了。目前正在想办法解决。
![image](https://user-images.githubusercontent.com/30562462/152472998-a49b67f9-b0c3-4485-994e-fef759bf5a5d.png)

**Comment by lrisora** [comment]
这个下拉菜单不会即时同步媒体库中移除的播放列表与文件夹
选项处于不可用状态但仍然存在
重启应用后会移除

**Comment by zhongyang219** [comment]
现在问题应该解决了
