### ISSUE TITLE
groove风格界面问题

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#316]
好像是频谱分析的那行高度计算有问题

![圖片](https://user-images.githubusercontent.com/43085437/153838642-da7f5754-813e-4938-b336-e5e9b33eefe3.png)

**Comment by lrisora** [comment]
我的理解是这里更外层的vercalLayoutyd应当得知其内部rectangle内子元素已达最小高度开始挤压lyrics高度
```xml
<verticalLayout>
	<rectangle no_corner_radius="true">
		<horizontalLayout>
			<albumCover square="true" margin="8" width="30%"/>
			<verticalLayout margin="8">
				<text type="title" style="scroll" height="38" font_size="12"/>
				<text type="artist" style="scroll" height="24" font_size="10"/>
				<text type="album" style="scroll" height="24" font_size="10"/>
				<spectrum draw_reflex="true" fixed_width="true" margin-top="8"/>
				<text type="format" style="scroll" height="24"/>
			</verticalLayout>
		</horizontalLayout>
	</rectangle>
	<lyrics margin="8"/>
</verticalLayout>
```

**Comment by zhongyang219** [comment]
你的建议确实有道理，不过实现起来似乎有些困难

**Comment by lrisora** [comment]
还有个方便但不太优雅的方案，添加rectangle或verticalLayout最小高度属性，手工实现，不用程序递归子元素

**Comment by lrisora** [comment]
限定只有布局容器和矩形可以拥有子元素并且矩形只能拥有0-1个子元素时实现复杂度可接受
不过又想了想，这个复杂的方案并不合理，可以简单的被设定高度的矩形简单覆盖效果，实际影响显示的情况也极少

目前的界面相当于只支持子元素设定固定宽高（定值或百分比），未设定项拥有1*的尺寸等分剩余空间
未来可考虑未设定项可设置按设定比例分剩余空间比如一个为1*一个为2*（不着急可以先放放）

对布局容器作为子元素时添加最大最小尺寸比较合理，搭配百分比可实现的效果会多很多

**Comment by zhongyang219** [comment]
目前所有的元素都可以自由嵌套，并没有做任何限制，我觉得这样设计并没有什么不合理之处。
我的想法和你差不多，要解决这个issue的问题，首先得实现元素的最大/最小宽度和高度

**Comment by lrisora** [comment]
左侧按钮列需要再隐藏一个按钮，设置按钮和下方仍有重叠，打开状态栏时明显

**Comment by zhongyang219** [comment]
> 左侧按钮列需要再隐藏一个按钮，设置按钮和下方仍有重叠，打开状态栏时明显

问题已修正。

> 另外频谱分析不显示时对元素完全隐藏导致需要一个placeHolder保持原本的界面阻止居中

这个我觉得没什么问题
