### ISSUE TITLE
请问无序播放和随机播放有什么区别？

### ISSUE THREAD

**Issue by snowoneyebrow** [zhongyang219/MusicPlayer2#319]
请问无序播放和随机播放有什么区别？

**Comment by lrisora** [comment]
#89 
简单的说
无序播放是对一个内部随机排序产生的播放列表的列表循环
随机播放一直随机选择下一曲，上一曲使用历史记录
无序播放避免连续播放相同曲目，随机播放不会
最大的差别在手动播放后的上一曲行为

**Comment by snowoneyebrow** [comment]
明白了，感谢！

**Comment by TrevorGrey** [comment]
懂了
