### ISSUE TITLE
一些疑惑和建议

### ISSUE THREAD

**Issue by ziqitsai** [zhongyang219/MusicPlayer2#32]
您好！首先，我发现这款软件不能读取歌曲内置的歌词？（我看见了设置中有一项是关于内置歌词的，但是打开了好像也没什么变化。）其次，我设置了在搜索框显示专辑封面和模糊化，但是如截图所见，并不是按照设置的结果那样显示的，而且我还无法重新设置了（我也不知道我怎么设置成这个样子的）总之，我很看好您的这款软件，加油鸭！
<img width="960" alt="批注 2020-01-20 233440" src="https://user-images.githubusercontent.com/32975206/72738887-84337f00-3bdd-11ea-9b76-46c28d4caf8c.png">

**Comment by zhongyang219** [comment]
1. 目前暂时不支持读取内置歌词，会在后续版优化。
2. “使用兼容模式显示歌词”是在搜索框信息显示不正常时的一个替代的显示歌词的方案，一般情况下建议保持不勾选。而“使搜索框不透明”是在白色任务栏时搜索框信息无法显示时勾选的。

**Comment by SplitGemini** [comment]
想内置歌词+1

**Comment by zhongyang219** [comment]
最新版本已经支持内嵌歌词
