### ISSUE TITLE
这是少了什么？

### ISSUE THREAD

**Issue by yjcjdfh** [zhongyang219/MusicPlayer2#322]
![IMG_20220223_100005](https://user-images.githubusercontent.com/90547519/155260018-23fa4675-76c7-44e1-a308-abd89d061909.jpg)

**Comment by lifegpc** [comment]
看 https://github.com/zhongyang219/MusicPlayer2/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by yjcjdfh** [comment]
> 看[https://github.com/zhongyang219/MusicPlayer2/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B8%B8%E8%A7 %81%E9%97%AE%E9%A2%98](https://github.com/zhongyang219/MusicPlayer2/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

没用的弄了之后有提示少某个东西

**Comment by yjcjdfh** [comment]
没什么用，弄完之后又提示少别的东西

**Comment by lifegpc** [comment]
那看来只能移除SMTC编译一个了

**Comment by zhongyang219** [comment]
> 没什么用，弄完之后又提示少别的东西

还少什么文件？把截图发上来看看。
我在Win7虚拟机里测试过，把[常见问题](https://github.com/zhongyang219/MusicPlayer2/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)提供的dll文件放到程序所在目录下就可以正常打开了。

**Comment by yjcjdfh** [comment]
![IMG_20220224_085825](https://user-images.githubusercontent.com/90547519/155436726-b866a178-3b8b-454d-834b-a163f4f505d0.jpg)

**Comment by lifegpc** [comment]
…
去 https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 下载一个安装

**Comment by yjcjdfh** [comment]
![IMG_20220224_090357](https://user-images.githubusercontent.com/90547519/155437328-05716033-9649-4c76-8416-f985106a948b.jpg)
![IMG_20220224_090237](https://user-images.githubusercontent.com/90547519/155437337-807d57e7-6213-4de2-8cd7-2beb7347f4b2.jpg)

**Comment by yjcjdfh** [comment]
![Uploading IMG_20220224_090516.jpg…]()

**Comment by yjcjdfh** [comment]
![Uploading IMG_20220224_090516.jpg…]()

**Comment by yjcjdfh** [comment]
![IMG_20220224_090613](https://user-images.githubusercontent.com/90547519/155437655-784be6bf-e9d2-4bb8-bf27-72ac5cac1241.jpg)

**Comment by yjcjdfh** [comment]
![IMG_20220224_090516](https://user-images.githubusercontent.com/90547519/155437693-2905436a-a864-4a08-b2d8-3c3a27429922.jpg)

**Comment by yjcjdfh** [comment]
已解决问题
