### ISSUE TITLE
读取aif 文件出错

### ISSUE THREAD

**Issue by FeiBam** [zhongyang219/MusicPlayer2#325]

**Comment by FeiBam** [comment]
![image](https://user-images.githubusercontent.com/56884041/155846306-5b65b7fe-8104-4f0d-a4b7-85efdc2ab476.png)

**Comment by FeiBam** [comment]
![image](https://user-images.githubusercontent.com/56884041/155846323-734430ec-34c0-45bd-8671-60d981c55c2f.png)

**Comment by FeiBam** [comment]
读取Itnues 专用文件格式时候 tag.dll 库无法正确读取 歌曲信息
导致 歌曲信息为空指针  移除 aif文件后 恢复正常

**Comment by zhongyang219** [comment]
请把出现问题的aif文件发上来以便我调查这个问题

**Comment by FeiBam** [comment]
歌曲文件 ：https://feibam.club/music/01%20Seize%20The%20Day.aif

**Comment by zhongyang219** [comment]
我用你提供的文件并没有复现你说的问题
![image](https://user-images.githubusercontent.com/30562462/155874996-4b9e6a55-3b5b-401b-8145-7a3b9a8200fc.png)

**Comment by FeiBam** [comment]
我本地仓库版本过低了 从新拉取仓库后解决
