### ISSUE TITLE
mini模式与浮动播放列表逻辑

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#328]
依次按ctrl+k，ctrl+m，ctrl+k，窗口消失
此时可以通过显示播放器全局快捷键显示主窗口但无法操作

进入mini模式时没必要隐藏浮动播放列表吧

**Comment by lrisora** [comment]
ctrl+k，ctrl+m，ctrl+l，窗口也会消失
或许mini模式下ctrl+l可以改成显示隐藏mini模式的播放列表

自动隐藏浮动播放列表可以接受，不过应当保持在mini模式再次打开浮动播放列表的能力，比较方便

**Comment by zhongyang219** [comment]
感谢反馈，正在尝试解决这个问题

**Comment by zhongyang219** [comment]
问题应该已经解决了，看看还有没有其他的问题

**Comment by lrisora** [comment]
mini模式的播放列表展开时的ctrl+k，mini模式浮动播放列表打开时的ctrl+l
与主窗口的行为不一致
~虽然我不觉得是问题~

**Comment by lrisora** [comment]
我认为迷你模式隐藏播放列表应当是在mini模式窗口类使用变量记录而不是主窗口
由mini窗口进行浮动播放列表的隐藏与显示（不太清楚可行性）以实现下面的逻辑

进入mini模式时自动隐藏播放列表后，
如果在迷你模式中打开又关闭过浮动播放列表则退出mini模式时不必恢复浮动播放列表
这样比较合理的感觉

**Comment by zhongyang219** [comment]
> 我认为迷你模式隐藏播放列表应当是在mini模式窗口类使用变量记录而不是主窗口
> 由mini窗口进行浮动播放列表的隐藏与显示（不太清楚可行性）以实现下面的逻辑
> 
> 进入mini模式时自动隐藏播放列表后，
> 如果在迷你模式中打开又关闭过浮动播放列表则退出mini模式时不必恢复显示浮动播放列表
> 这样比较合理的感觉

我觉得目前的逻辑是合理的，进入迷你模式后，浮动播放列表自动隐藏，虽然可以通过Ctrl+K显示，但是退出迷你模式后浮动播放列表保持进入迷你模式前的状态。
这个问题不打算改了，否则会使逻辑变得越来越复杂。

**Comment by lrisora** [comment]
现在也没有bug了
也算可以了
