### ISSUE TITLE
.m3u文件编码问题

### ISSUE THREAD

**Issue by SheepChef** [zhongyang219/MusicPlayer2#329]
如图，在使用记事本访问由MusicPlyer2.74版本保存的播放列表(.m3u文件)时，其中文字符使用了不常见的编码规范(非UTF-8和Unicode)导致无法正常显示汉字内容。
![image](https://user-images.githubusercontent.com/50871867/156555005-535d2740-69ad-472f-9ab6-aa2ae25e5448.png)
同理(如图)，尝试向MusicPlayer2.74版本中添加来自其他离线播放器所生成的使用UTF-8编码的m3u文件时，其中文编码无法正常显示。
![image](https://user-images.githubusercontent.com/50871867/156555239-2316e3de-ac0c-4df6-bda7-95047db02590.png)
希望m3u文件的编码能够统一为UTF-8，方便修改和互相导入。另外，还请开发者告知一下2.74版本使用的编码策略。

**Comment by lifegpc** [comment]
出问题了就建议加上BOM

**Comment by SheepChef** [comment]
> 出问题了就建议加上BOM

![image](https://user-images.githubusercontent.com/50871867/156555830-d320305f-8cec-46d0-9bc8-9ff2a021df17.png)
如图，Windows记事本识别到文件编码为UTF-8 BOM,但尝试将其他播放列表的文件格式改为UTF-8 BOM后再导入，问题依旧。

**Comment by SheepChef** [comment]
> 出问题了就建议加上BOM

![image](https://user-images.githubusercontent.com/50871867/156556497-f81b38a2-193c-4ba8-96fa-e0a4bedb7b90.png)
且通过对比不难发现，同样为UTF8-BOM格式的文件，在记事本中却一个可以显示中文，另一个不能显示。
显然，MusicPlayer使用了非标准的文件编码来保存m3u文件。

**Comment by SheepChef** [comment]
通过查看相关源代码，编码改为ANSI后问题消失。
仍然建议m3u使用UTF-8编码方式。
![image](https://user-images.githubusercontent.com/50871867/156558311-004a9f51-4557-4f2c-bcc2-b36fd882d1b9.png)

**Comment by lrisora** [comment]
m3u规范是Windows-1252，导出时选m3u8就好了
