### ISSUE TITLE
请问Bass支持播放列表文件（.m3u,.m3u8）吗

### ISSUE THREAD

**Issue by 1357310795** [zhongyang219/MusicPlayer2#33]
今天用bass库写程序发现它不支持m3u文件，特地过来看了看作者这个比较完善的软件。
结果……没有结果。。
![QQ截图20200128211117](https://user-images.githubusercontent.com/35869804/73267001-0a217c80-4213-11ea-9a15-f3b94652f21d.png)

**Comment by zhongyang219** [comment]
好像是不支持的，bass主要负责音频解码，播放列表文件还是需要我们手动解析的。播放列表文件终究还是文本文件，解析起来应该不是难，后续版本会考虑增加播放列表文件的支持。
