### ISSUE TITLE
TAK音频格式还支持吗？

### ISSUE THREAD

**Issue by Little-Data** [zhongyang219/MusicPlayer2#330]
记得之前的版本还可以播放TAK格式文件，在软件的“帮助”-“支持的格式”里是有支持这个格式的。更新后没有了，也无法播放。

**Comment by lrisora** [comment]
只有32位的程序支持BASS核心播放tak，需要tak_deco_lib.dll

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/156747089-8b4660e7-b4d0-47ef-8f8a-c735fd8a63d1.png)
FFMPEG倒是支持解码（

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/156748909-5d254695-08e6-4014-9bbc-15eccef6bbc4.png)
但是没法获取TAG信息

**Comment by Little-Data** [comment]
请问如何配置FFMPEG？我从actions里下载到最新的版本，从ffmpeg官网下载了Windows的exe可执行文件版本。并且添加到系统的全局变量，甚至把可执行文件放到MusicPlayer2的目录里o(╥﹏╥)o，然而FFMPEG按钮仍然是灰色的(￣ェ￣;)

**Comment by lrisora** [comment]
https://github.com/zhongyang219/MusicPlayer2/pull/307#issuecomment-1046134300
下载放到程序目录
x64的bass核心从未支持过tak，既然你说用过说明之前用的是x86，32位版
FFMPEG支持的格式应该特别多

**Comment by Little-Data** [comment]
是的，之前是下错了32位版本就将就着用，后来升级换回64位版本。<br/>**OneDrive**是真的服，换好几种科学上网工具也打不开。能不能换个分享方式？（拒绝百度云）<br/>（今日不再回复）

**Comment by lifegpc** [comment]
> 是的，之前是下错了32位版本就将就着用，后来升级换回64位版本。**OneDrive**是真的服，换好几种科学上网工具也打不开。能不能换个分享方式？（拒绝百度云）（今日不再回复）

https://github.com/lifegpc/ffmpeg_core/releases/tag/v1.0.0.0
去这里吧

**Comment by Little-Data** [comment]
不知道是不是系统（Win11稳定版，笔记本）或其它什么杂七杂八的问题，我这里用ffmpeg无法播放tak文件。但是却能显示标签信息。用tak官方提供的转换器转换成WAV文件就可以播放了（没有标签是因为转换器会清除标签）。还有用ffmpeg内核进行播放时，再打开另外的文件会显示正在播放该文件，实际上上一首音乐还在继续播放，需要到播放列表手动切换下一首（使用MusicPlayer2[最新构建版](https://github.com/zhongyang219/MusicPlayer2/actions/runs/1934120299)）。
<br/>不过这是在测试的版本，相信MusicPlayer2会越来越完善，这是我用过的最好的本地播放器了，支持你们！Thanks♪(･ω･)ﾉ
### 下面是测试的文件，希望对你们有用

![1](https://user-images.githubusercontent.com/53138165/156876607-1574e0b5-b15d-4abb-ae12-b1e13c710b97.png)
![2](https://user-images.githubusercontent.com/53138165/156876610-94443b7c-ae8a-410c-874c-af55259a20d8.png)

[(tak)- brilliant azure [ver. short].txt](https://github.com/zhongyang219/MusicPlayer2/files/8190337/tak.-.brilliant.azure.ver.short.txt)
[(wav)- brilliant azure [ver. short].txt](https://github.com/zhongyang219/MusicPlayer2/files/8190338/wav.-.brilliant.azure.ver.short.txt)
[ffplay命令输出.txt](https://github.com/zhongyang219/MusicPlayer2/files/8190339/ffplay.txt)

### Sample样本
[(tak格式音频)brilliant azure [ver. short].tak](https://github.com/Little-Data/Sample/blob/main/Audio/.tak/%E5%A4%9C%E6%98%8E%E3%81%91%E5%89%8D%E3%82%88%E3%82%8A%E7%91%A0%E7%92%83%E8%89%B2%E3%81%AA%20-Brighter%20than%20dawning%20blue-/01%20-%20brilliant%20azure%20%5Bver.%20short%5D.tak)
[(wav格式音频)brilliant azure [ver. short].wav](https://github.com/Little-Data/Sample/blob/main/Audio/.wav/%E5%A4%9C%E6%98%8E%E3%81%91%E5%89%8D%E3%82%88%E3%82%8A%E7%91%A0%E7%92%83%E8%89%B2%E3%81%AA%20-Brighter%20than%20dawning%20blue-/01%20-%20brilliant%20azure%20%5Bver.%20short%5D.wav)

**Comment by zhongyang219** [comment]
> 还有用ffmpeg内核进行播放时，再打开另外的文件会显示正在播放该文件，实际上上一首音乐还在继续播放，需要到播放列表手动切换下一首（使用MusicPlayer2[最新构建版](https://github.com/zhongyang219/MusicPlayer2/actions/runs/1934120299)）。

这个问题现在已经解决了，请到[Actions页面](https://github.com/zhongyang219/MusicPlayer2/actions)下载最新构建版本

**Comment by lifegpc** [comment]
无法播放是因为ffmpeg现在还没写相关功能吧。
```
TAK codec type 0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented
```
日志上是这么说的

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/156947044-cbb95876-a95f-49fc-be19-f72a22bb7b9f.png)
我这里倒是给出不同的错误
