### ISSUE TITLE
有点大的问题及建议

### ISSUE THREAD

**Issue by liucin** [zhongyang219/MusicPlayer2#35]
_m4a文件的信息读取不完整，只能读取到作者，**标题、专辑、音轨序号**以及不管带不带时间轴的**内置歌词跟封面**信息没有读出来，希望后续慢慢完善_

**Comment by zhongyang219** [comment]
感谢你的反馈，目前读取内置歌词的专辑封面都只支持MP3格式，m4a格式是可以读取到标题、艺术家、唱片集、年份、音轨序号、流派的，可能由于我本地的音频文件样本太少导致部分m4a文件标签识别有问题。请把你遇到的信息读取不完整的m4a文件通过电子邮件发给我，以帮助我确认问题所在，邮件发送到 zhongyang219@hotmail.com。

**Comment by zhongyang219** [comment]
你好，已经收到你的邮件，确实存在你说的问题，目前m4a文件信息读取不完整的问题已经解决，我临时编译了一个版本，你可以再测试一下。
[MusicPlayer2_2.6.8.1_beta(x64).zip](https://github.com/zhongyang219/MusicPlayer2/files/4240629/MusicPlayer2_2.6.8.1_beta.x64.zip)

**Comment by SplitGemini** [comment]
目前的最新版本音轨号不能显示正确，看commit下一版本已经修复了读封面问题，但是音轨貌似没修复。提供一个m4a音乐供测试
[The Minions - Papa Mama Loca Pipa.zip](https://github.com/zhongyang219/MusicPlayer2/files/5100770/The.Minions.-.Papa.Mama.Loca.Pipa.zip)

**Comment by liucin** [comment]
好的，等会试试，感谢。



---原始邮件---
发件人: "Guo"<notifications@github.com&gt;
发送时间: 2020年8月20日(周四) 中午1:02
收件人: "zhongyang219/MusicPlayer2"<MusicPlayer2@noreply.github.com&gt;;
抄送: "liucin"<1647489141@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhongyang219/MusicPlayer2] 有点大的问题及建议 (#35)




 
目前的最新版本音轨号不能显示正确，看commit下一版本已经修复了读封面问题，但是音轨貌似没修复。提供一个m4a音乐供测试
 The Minions - Papa Mama Loca Pipa.zip

**Comment by SplitGemini** [comment]
封面读取仍有部分音乐无法读取，感觉能否读出来很随机，读不出的比例不小
提供测试用音乐，两个png一个jpg
[musics_m4a.zip](https://github.com/zhongyang219/MusicPlayer2/files/5134162/musics_m4a.zip)

这个看起来比较棘手，辛苦开发大佬了
我不是很懂c++，但是有点奇怪为什么不用[Taglib](https://github.com/taglib)？

**Comment by zhongyang219** [comment]
你好，感谢你的反馈，目前m4a专辑封面的获取还不完善，确实有部分m4a文件读不出来。
目前读取音频标签部分是我自己实现的，确实还有比较多问题，后续版本会尝试使用Tablib。

发送自 Windows 10 版邮件应用

发件人: Guo
发送时间: 2020年8月27日 13:11
收件人: zhongyang219/MusicPlayer2
抄送: zhongyang219; Comment
主题: Re: [zhongyang219/MusicPlayer2] 有点大的问题及建议 (#35)

封面读取仍有部分音乐无法读取，感觉能否读出来很随机，读不出的比例不小
提供测试用音乐，两个png一个jpg
musics_m4a.zip
这个看起来比较棘手，辛苦开发大佬了
我不是很懂c++，但是有点奇怪为什么不用Taglib？

**Comment by zhongyang219** [comment]
@SplitGemini 我这边从github下载大文件有点问题，可以使用国内网盘分享一下吗

**Comment by SplitGemini** [comment]
> @SplitGemini 我这边从 github 下载大文件有点问题，可以使用国内网盘分享一下吗

[https://guoh27.lanzous.com/iq0YRg3ytvi](https://guoh27.lanzous.com/iq0YRg3ytvi)

**Comment by zhongyang219** [comment]
问题已解决，请更新到2.71版。
