### ISSUE TITLE
System Media Transport Controls 专辑封面显示异常

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [zhongyang219/MusicPlayer2#360]
RT，同一个文件，在Groove音乐下显示没问题，在MP2下显示是有问题的（p1）

同时，在MP2 App内显示没问题，显示到SMTC就有问题（p2）

仅部分文件有问题（p3）

---

附图：

![image](https://user-images.githubusercontent.com/25266280/169072908-4e3a95df-eb19-4937-8884-752bca6d341e.png)

![image](https://user-images.githubusercontent.com/25266280/169072966-d1cc7a25-cf2b-4c4f-a291-8b8f090b426d.png)

![image](https://user-images.githubusercontent.com/25266280/169072997-e5a3370c-b704-45e4-8a4e-d37cd1b2d36d.png)

**Comment by PeanutMelonSeedBigAlmond** [comment]
似乎是图片本身的问题，我用PS重新保存了图片之后正常了

**Comment by lifegpc** [comment]
> 目前Windows 10自带的控制界面没问题，但是 ModernFlyouts 的那个就没法显示

大概是yuvj420p不支持的问题

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 目前Windows 10自带的控制界面没问题，但是 ModernFlyouts 的那个就没法显示

好，感谢
