### ISSUE TITLE
【BUG】播放无声音+更新源版本获取问题

### ISSUE THREAD

**Issue by Paleozoic** [zhongyang219/MusicPlayer2#366]
1. 播放无声音
操作系统：win11
现象描述：软件刚安装是有声音的，一段时间后突然没有声音了。音乐显示正在播放。其他软件的声音正常，证明喇叭没问题。
已做尝试：
（1）删除软件目录并且重新下载软件覆盖。
（2）重启软件、重启电脑
（3）反复静音+取消静音电脑，反复暂停+播放MP2音乐等常规软件操作

软件版本：
![软件版本](https://user-images.githubusercontent.com/5664223/170394831-31e7a287-7535-44c9-b801-640fc5b90669.png)
播放状态：
![播放状态](https://user-images.githubusercontent.com/5664223/170394982-0747bdbb-58ee-4e1e-a23f-fc8690098417.png)
音量状态：
![系统音量状态](https://user-images.githubusercontent.com/5664223/170395460-9fb7c3f5-0fc2-4b55-bd7a-28212cab436e.png)
![音量状态](https://user-images.githubusercontent.com/5664223/170395045-e6f46ac9-b97e-408b-9161-484f4364ce01.png)

2. 自动更新默认是gitee源，但是获取版本信息是从github获取。
![更新源](https://user-images.githubusercontent.com/5664223/170395958-f467c257-1287-4fba-bc4f-92eaca555a66.png)
错误日志如下：
`2022/05/26 09:07:00.952 http get https://github.com/zhongyang219/MusicPlayer2/blob/master/version.infoerror. Error code: 12002`

**Comment by lifegpc** [comment]
关于第一个问题，进度条会继续动吗？
现在已知BASS、SDL2(WASAPI)、OpenAL(WASAPI)的实现都有问题，在其他程序解除独占模式后，依旧无法正常播放。
如果有其他软件开启了独占模式，也会导致无法播放。

**Comment by Paleozoic** [comment]
进度条会动，看起来一切都是正常的。就是没有声音。
尝试解除系统扬声器独占，问题依旧。
是否有其他软件独占，无法确认。下载了foobar2000，aimp播放器测试，播放正常。
![image](https://user-images.githubusercontent.com/5664223/170417363-acf96d63-12a4-489b-ade4-961085f5a25e.png)

**Comment by lifegpc** [comment]
看来应该跟独占模式无关。

**Comment by lifegpc** [comment]
可以尝试切换成别的内核试一下吗？
MCI内核或者dev版新增的FFMPEG内核都行
这看上去应该是BASS内核的问题

**Comment by Paleozoic** [comment]
@lifegpc 
切换内核，问题依旧。其实前几天还可以正常播放的= =
![image](https://user-images.githubusercontent.com/5664223/170418610-7bb866ab-16b9-4918-9794-397b3c39d2b9.png)

**Comment by Paleozoic** [comment]
而且貌似切换为MCI内核，启动慢了好多……

**Comment by Paleozoic** [comment]
dev版新增的FFMPEG内核木有找到，dev版本的下载链接是？

**Comment by lifegpc** [comment]
从[这里](https://github.com/zhongyang219/MusicPlayer2/actions/runs/2326944017#artifacts=)下载最新的开发版本。
然后去[这里](https://github.com/lifegpc/ffmpeg_core/releases)下载，将所有dll解压到MusicPlayer2的目录下。
然后播放设置->播放内核 选择 FFMPEG

**Comment by lifegpc** [comment]
这些是由GitHub Action自动生成的。
很多版本可以在 https://github.com/zhongyang219/MusicPlayer2/actions 看到

**Comment by Paleozoic** [comment]
@lifegpc 多得在下也是码农= =还需要将bass.dll放进去。已经尝试了FFMPEG，问题依旧。。。
不过刚刚我找到了MP2存放配置的文件夹，清除之后重启竟然可以了。。。不知道是配置的那里导致了程序异常。。。

**Comment by Paleozoic** [comment]
通常程序默认应用数据储存路径为：`C:\Users\xxx\AppData\Roaming\MusicPlayer2`
供遇到相同问题的小伙伴参考。

**Comment by zhongyang219** [comment]
你不会是不小心滚动了鼠标滚轮，做后把软件设置成了静音了吧。软件可以通过鼠标滚轮调节音量，向下滚动鼠标滚轮可以减小音量，持续向下滚动鼠标滚轮最后会变成静音状态。从截图上看你用的界面4，而界面4没有音量图标，你可以切换到界面1、界面2、界面5、界面6看看当前是不是静音状态。

**Comment by Paleozoic** [comment]
经过检查……的确如此。鼠标滚轮导致软件静音了。。。表现和上面截图一致。看音量看不出问题，软件是静音的。乌龙了。。。
![1653878217(1)](https://user-images.githubusercontent.com/5664223/170907206-29682e9c-0b8b-473d-a510-f8a9d267082d.png)

**Comment by pandipper** [comment]
> 你不会是不小心滚动了鼠标滚轮，做后把软件设置成了静音了吧。软件可以通过鼠标滚轮调节音量，向下滚动鼠标滚轮可以减小音量，持续向下滚动鼠标滚轮最后会变成静音状态。从截图上看你用的界面4，而界面4没有音量图标，你可以切换到界面1、界面2、界面5、界面6看看当前是不是静音状态。

刚刚我也遇到了这个情况，解决了大问题哈哈，多谢
