### ISSUE TITLE
请问FFMPEG播放内核和Bass有什么区别呢？

### ISSUE THREAD

**Issue by snowoneyebrow** [zhongyang219/MusicPlayer2#372]
如题

**Comment by zhongyang219** [comment]
对于一般用户来说可能不太能感觉到区别，目前主要的区别在于：
* 支持的格式不同。尽管bass内核已经能够支持绝大部分常见的音频格式，但是ffmpeg支持的格式更多。如果遇到bass内核不支持的音频格式可以尝试切换到ffmpeg内核，但是ffmpeg无法播放midi音乐。
* “均衡器”——“混响”功能在ffmpeg内核下暂时无法使用。
* 转换格式功能在ffmpeg内核下暂时无法使用。
* 在bass内核下使用“播放控制”菜单下的“加速”、“减速”功能时会导致音调发生变化，而ffmpeg内核下就不会。
* 频谱分析的显示效果略有区别

**Comment by snowoneyebrow** [comment]
明白了，感谢！
