### ISSUE TITLE
[feature request] 桌面歌词置顶，不被任务栏遮挡

### ISSUE THREAD

**Issue by tchxyc** [zhongyang219/MusicPlayer2#375]
个人喜欢把歌词放到任务栏，但是每次点击任务栏之后，歌词就会被任务栏遮挡，希望能增加一个桌面歌词置顶功能

**Comment by lrisora** [comment]
除了任务管理器外应该没有（也不应有）能够固定在任务栏上层显示的窗口，
普通窗口设置置顶后是和任务栏本身是平级的，

如果只是需要任务栏显示的话建议用现有的任务栏搜索框歌词显示替代桌面歌词

**Comment by Zojekin** [comment]
有无办法能够使任务栏覆盖歌词后自动刷新置顶呢？
