### ISSUE TITLE
cue文件曲目错位

### ISSUE THREAD

**Issue by ditb3** [zhongyang219/MusicPlayer2#386]
如题，cue文件播放时，TOC位置错误，也就是分割曲目的位置错误
这个问题在其他设备上也出现了，我认为这不是我的硬件问题
这个问题在其他能播放cue的软件上没有出错，我认为这不是cue文件的错误
我附上了截图，具体文件太大了没有办法传输
![issue](https://user-images.githubusercontent.com/109351520/179215442-4888be36-58cb-4aae-944f-4c3bb13ce547.PNG)
![issue2](https://user-images.githubusercontent.com/109351520/179215465-4454b33f-bf87-42a4-af61-7ac10d53b547.PNG)

**Comment by lrisora** [comment]
能把cue文件发出来吗，不用带音频文件

**Comment by ditb3** [comment]
[Yes . 1997 . Keys To Ascension 2 . Disc 01.txt](https://github.com/zhongyang219/MusicPlayer2/files/9125257/Yes.1997.Keys.To.Ascension.2.Disc.01.txt)
github发不了cue，我就转成txt了，应该是一样的吧
