### ISSUE TITLE
【BUG】媒体库文件夹的下拉菜单处，只能显示20个文件夹

### ISSUE THREAD

**Issue by wurarara** [zhongyang219/MusicPlayer2#388]
![1](https://user-images.githubusercontent.com/73343292/179446103-2e9d3fe2-7278-4f7d-8970-d1b26d4be0b0.jpg)
问题出在图中箭头指向的区域。
出于个人习惯，会在本地进行歌曲归类，所以文件夹较多。但是此处未提供**滚动条**，导致20个文件夹以外的文件夹无法被显示，希望您能解决，谢谢。

**Comment by lifegpc** [comment]
> ![1](https://user-images.githubusercontent.com/73343292/179446103-2e9d3fe2-7278-4f7d-8970-d1b26d4be0b0.jpg) 问题出在图中箭头指向的区域。 出于个人习惯，会在本地进行歌曲归类，所以文件夹较多。但是此处未提供**滚动条**，导致20个文件夹以外的文件夹无法被显示，希望您能解决，谢谢。

这里只显示最近播放过的，如果需要显示更多的，请使用媒体库

**Comment by wurarara** [comment]
> > ![1](https://user-images.githubusercontent.com/73343292/179446103-2e9d3fe2-7278-4f7d-8970-d1b26d4be0b0.jpg)出于个人习惯，出在箭头被指向的区域**问题**。希望您能解决，谢谢。
> 
> 这里只显示最近播放过的，如果需要显示更多的，请使用媒体库
好的谢谢，找到了
