### ISSUE TITLE
自绘标题栏自定义按钮显示变化后未更新点击区域

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#395]
只更新了鼠标提示，点击区域在设置应用后没有立即更新

DEV分支合并master时（在合并提交中）的修改：
```diff
 IDR_MENU1 MENU
     POPUP "&View"
         POPUP "Switch &UI"
-            MENUITEM "Switch &UI\tCtrl+U",          ID_SWITCH_UI
+            MENUITEM "Switch &UI\\",                ID_SWITCH_UI
(更正Switch &UI\\ -> Switch &UI)
```
中文显示设置"在标题栏中显示的按钮（仅当未勾选“使用系统标准标题栏”时有效）："

如果目前的5个pull requests都没什么问题的话建议直接合并DEV到master，冲突合并太困难

如果目前不打算合并pull requests（比如放到下一个版本）至少先合并 #382 ，冲突解决方式是使用master一侧文件。
之后DEV合并master会轻松很多

@zhongyang219

**Comment by lrisora** [comment]
另一个问题，使用FFMPEG内核时
频谱的复位只进行左边一半（比如按停止时）

**Comment by zhongyang219** [comment]
我无法合并 #382 ，于是我重新添加了`.gitattributes`文件并提交，但是我试图用TortoiseGit合并 #356 时MusicPlayer2.rc仍然全部变成乱码了
![捕获](https://user-images.githubusercontent.com/30562462/181924732-9a1c8ab0-cba4-4ecc-be92-b8d727ff9eff.JPG)

**Comment by lrisora** [comment]
忘了这个问题了，我当时是把合并前的Musicplayer2.rc复制出来，在进入合并冲突解决状态后直接替换覆盖这个乱码文件

重新提交应该是等效的，记得重启一下git客户端以重新载入 .gitattributes (至少我用的Sublime Merge需要)

DEV分支是重新在VS里又做了一遍操作，以后的再有Musicplayer2.rc冲突问题会变得更复杂，暂且先不要改资源文件了

**Comment by lrisora** [comment]
master合并#382导致资源文件被git认为修改过了，没办法干净合并，还是用替换文件的方法合并DEV吧，
实在是没力气合并#356等等了

我合并好以后重新用DEV开pr

**Comment by lrisora** [comment]
打开自绘菜单栏的显示时自绘标题栏的菜单按钮消失，鼠标提示区域没有消失
