### ISSUE TITLE
无法正确分割名称包含“/”的艺术家和专辑名

### ISSUE THREAD

**Issue by rinscr3003** [zhongyang219/MusicPlayer2#399]
有一个艺术家名称为“22/7”，在自动拆分艺术家时出现了这样的故障：
![image](https://user-images.githubusercontent.com/50514886/183038521-8942eb89-6168-435e-b53a-ee6abe922bfe.png)
能否设置白名单以对特定的艺术家名称中的“/”不拆分？

**Comment by rinscr3003** [comment]
![image](https://user-images.githubusercontent.com/50514886/183038776-17fc4bfa-e8b8-4b12-80fc-ec9ae09cb3fc.png)
文件例

**Comment by SheepChef** [comment]
在程序本身不做出改变的前提下，建议阁下使用如下替代解决方案：
使用Unicode符号\u2571(制表正斜杠), 即 "╱"  , 代替 "/"
使用Unicode符号\u2044(分数正斜杠), 即 " ⁄ " , 代替 “/”
使用Unicode符号\u2215(除法正斜杠), 即 " ∕ " , 代替 "/"

**Comment by zhongyang219** [comment]
确实存在这个问题，不过有一点让我疑惑的是，网易云音乐下载的歌曲含有多个艺术家时，多个艺术家是使用“/”分隔的，资源管理器能够正确识别成多个艺术家：
![image](https://user-images.githubusercontent.com/30562462/183898631-ffbc03d0-9e4b-4df3-ad31-c2bd463a4dea.png)
![image](https://user-images.githubusercontent.com/30562462/183898555-776a329e-5b00-48fe-aa4f-2e9c08ca5e21.png)
但是为什么对于“22/7”，资源管理器就认为是一个艺术家呢？

**Comment by lrisora** [comment]
是flac的原因，windows资源管理器无法（不会）分割flac的多艺术家

我的想法是把一首歌的艺术家作为一个整体出现在媒体库艺术家列表不进行主动拆分
但是如过其中的一个艺术家也有单曲则也把这首多艺术家的也添加进去

例如22/7不会主动分割为22和7，但是如果存在其他艺术家为22的歌曲则
左侧列表里有 22；22/7 且都含有这首歌

**Comment by rinscr3003** [comment]
> 在程序本身不做出改变的前提下，建议阁下使用如下替代解决方案： 使用Unicode符号\u2571(制表正斜杠), 即 "╱" , 代替 "/" 使用Unicode符号\u2044(分数正斜杠), 即 " ⁄ " , 代替 “/” 使用Unicode符号\u2215(除法正斜杠), 即 " ∕ " , 代替 "/"

由于我的个人音乐库全部使用这一份副本，而且购买的数字正版也是以“/”（半角ASCII斜杠）进行分割。贸然更改这个斜杠不仅不利于美观，也可能引起不可确定的问题。

**Comment by rinscr3003** [comment]
> 是flac的原因，windows资源管理器无法（不会）分割flac的多艺术家
> 
> ~更新：可能是要设置flac多艺术家应当使用分号分割而不是"/"~
> 
> 我的想法是把一首歌的艺术家作为一个整体出现在媒体库艺术家列表不进行主动拆分 但是如过其中的一个艺术家也有单曲则也把这首多艺术家的也添加进去
> 
> 例如22/7不会主动分割为22和7，但是如果存在其他艺术家为22的歌曲则 左侧列表里有 22；22/7 且都含有这首歌

这显然是一个针对特例的做法，并且不如添加白名单（PowerAmp的做法，默认添加了“AC/DC”和“+/-”）简单。  
但是如果近期的迭代中能够修复该问题，我很乐意看到PotPlayer的继任者出现在我i的电脑上。

**Comment by lrisora** [comment]
关于举例，按我上述做法程序会正常工作，这个方案代价是
可能会有识别不出的（会和其他艺术家组合出现），不会有不存在的
就是说假设真的同时存在“22/7”与“22”并不会导致“7”单独出现

关于白名单，由于没有用过不太清楚，这里说的是一个程序全局的字符串列表吗？
如果是的话，这也是一个针对特例的处理，是在赌下述情况不会出现
比如对“22/7”设置不拆分并且真的存在艺术家“22”与“7”就会出问题，只是可能性很低

我觉得全局白名单的方案更好一些

**Comment by TaicEart** [comment]
路过，考虑到“AC/DC”是个著名乐队，那么其它播放器是如何正确处理的？已知PowerAmp的做法。

**Comment by lrisora** [comment]
咕了一年的更新 
我这里出问题的艺术家如下
"AC/DC","+/-","22/7","ave;new","ハロー、ハッピーワールド!","リリィ、さよなら。","MYTH & ROID","Meghan & Lucas"
实际上使用‘/’，‘;’，‘&’以及‘、’4个字符分割
