### ISSUE TITLE
下载在哪？

### ISSUE THREAD

**Issue by mingzhi2018** [zhongyang219/MusicPlayer2#4]
在哪下载这个播放器？感觉可以替代已经不正常的好多年的千千静听了。不会用GitHub，给个下载传送门

**Comment by mingzhi2018** [comment]
找到了，原来是要在网址后面加“/releases”就出现下载页了。
但是使用中有个问题，播放器似乎不支持DSD音频的DFF格式，也无法转换DSD为其他格式。
另外好像不能把不同文件夹的某个歌曲综合到播放列表里，不知道是不是我不会操作。

**Comment by zhongyang219** [comment]
[bassdsd.zip](https://github.com/zhongyang219/MusicPlayer2/files/2296416/bassdsd.zip)
你把附件解压出来，将bassdsd.dll放到程序所在目录下的Plugins目录下，重启软件试试，应该就可以播放DSD音频了。
目前这个播放器组织音频文件的方式是基于文件夹，目前只能打开一个文件夹中的歌曲，后续版本会增加播放列表功能。

**Comment by zhongyang219** [comment]
这个播放使用的播放引擎是BASS音频库，只要BASS引擎有支持相应格式的插件，它就能播放该格式，也支持该格式的转换。如果你发现有音频格式无法播放，你可以到BASS官网http://www.un4seen.com/下载对应格式的插件，然后将下载zip包解压出来，将里面的bassxxx.dll放到程序所在目录的Plugins下面，播放器就能播放对应格式的音频了。
