### ISSUE TITLE
启用last.fm功能后，如果艺术家为空，会反复发送http请求

### ISSUE THREAD

**Issue by zhongyang219** [zhongyang219/MusicPlayer2#404]
在艺术家为空的情况下，程序运行到以下代码时会进入continue，`i`仍然为0，无法进入第427行的while循环，缓存中的一条记录永远无法清除，程序就会一直发送http请求。
![image](https://user-images.githubusercontent.com/30562462/183681355-f692091e-1ce1-4a05-9c60-3c6a41221418.png)
![image](https://user-images.githubusercontent.com/30562462/183681666-fd999537-732c-4a8f-9633-4b05e8bee99d.png)

**Comment by zhongyang219** [comment]
@lifegpc

**Comment by lrisora** [comment]
另一个疑问，MusicPlayer2存储osu!目录音乐时把id存入了音轨号，
实测没有观察到影响识别（可能被last.fm修正了），这里可能发送音轨号0比较好。
![圖片](https://user-images.githubusercontent.com/43085437/183697327-11f756d2-7bf7-438c-a774-f21ab1c19f1c.png)

**Comment by lifegpc** [comment]
> @lifegpc

有时间会修

**Comment by lifegpc** [comment]
> 另一个疑问，MusicPlayer2存储osu!目录音乐时把id存入了音轨号， 实测没有观察到影响识别（可能被last.fm修正了），这里可能发送音轨号0比较好。 ![圖片](https://user-images.githubusercontent.com/43085437/183697327-11f756d2-7bf7-438c-a774-f21ab1c19f1c.png)
> 
> 可能需要的是一开始就忽略信息不全的歌曲

只有artist 和 title 是必要的。音轨号不影响识别，影响识别的有artist, title, album, album_artist

**Comment by zhongyang219** [comment]
@lifegpc @lrisora 顺便说一下，以后如果要在选项对话框中添加Static、CheckBox等控件时，可以不用为对应的控件添加`CStatic`或`CButton`类型的控件变量，Static控件可以使用`SetDlgItemText`和`GetDlgItemText`函数设置和获取文本，CheckBox控件可以使用`CheckDlgButton`和`IsDlgButtonChecked`设置和获取勾选状态，这样可以让代码更简洁。
也不要使用`((CButton*)GetDlgItem(IDC_SAVE_TO_ALBUM_FOLDER2))->SetCheck(FALSE);`这种写法。
另外，选项设置子对话框的基类`CTabDlg`中还添加了`EnableDlgCtrl`函数用来设置控件的启用/禁用状态，`ShowDlgCtrl`函数用来设置控件的显示/隐藏。`CBaseDialog`中也有`ShowDlgCtrl`函数，如果需要`EnableDlgCtrl`也可以自己添加。
