### ISSUE TITLE
搜索框问题

### ISSUE THREAD

**Issue by lifegpc** [zhongyang219/MusicPlayer2#408]
![pic](https://user-images.githubusercontent.com/41434272/184461081-ea27ba34-a4bd-44ee-acb1-460aeb352e0b.png)
在搜索框直接输入英文时，会触发快捷键，例如输入s会暂停。

**Comment by lrisora** [comment]
原来的代码是搜索框拥有焦点时所有Accelerator快捷键均不响应
我觉得这样不好就去掉了，当时没注意到这个问题

目前想到的解决方法如下(注释的代码是原代码逻辑)：
```c++
    if (WM_KEYFIRST <= pMsg->message && pMsg->message <= WM_KEYLAST/* && pMsg->hwnd != m_search_edit.GetSafeHwnd()*/)
    {
        // 搜索框拥有焦点时跳过可以构成输入的快捷键按键消息
        if (pMsg->hwnd == m_search_edit.GetSafeHwnd() && !(GetKeyState(VK_CONTROL) & 0x80) && pMsg->wParam >= 'A' && pMsg->wParam <= 'Z')
            return TRUE;
        //响应Accelerator中设置的快捷键
        if (m_hAccel && ::TranslateAccelerator(m_hWnd, m_hAccel, pMsg))
            return TRUE;
    }
```
不过这只能算是临时解决方案无法正式使用，以后迟早会出问题，例如无法解决shift+s这种既可以是快捷键又可以是输入的情况
理想解决方法是修改m_search_edit控件将所有构成输入的消息`return TRUE;`不过我不会
不行的话还是倒回原有逻辑在搜索框拥有焦点时禁用Accelerator快捷键

**Comment by lifegpc** [comment]
我倒是记得之前只要在搜索框点过一次，焦点就会留在那，就会导致快捷键完全失效。
按照一般的逻辑，点一下别的地方，会取消搜索框的焦点，但目前这点做不到。感觉把这个弄好，然后把上面的代码复原就差不多了

**Comment by lrisora** [comment]
当时允许搜索框焦点时响应快捷键也有部分原因是这个
好像是只有点击可以拥有焦点的控件才能抢走搜索框的焦点
整个左侧界面都画在一个控件上，所有消息都是自行处理，
点击消息不会落到CMusicPlayerDlg上
目前自绘标题栏的鼠标按键处理都是在上面进行的，好像在那里才能判断点击位置在哪个按钮或区域
主窗口接不到消息也是去掉大小边框的障碍
我觉得自绘标题栏的标题栏特殊处理还是迁移到CMusicPlayerDlg或CMainDialogBase更好（可能很困难）
左侧的控件可能需要允许消息发到主窗口，将来去掉边框也需要这个
我不太懂这里控件间的消息处理（还没学）仅参考

**Comment by zhongyang219** [comment]
我认为原来的逻辑没有问题，当搜索框没有焦点时，按快捷键F可以让键框获取焦点，此时可以在键框内输入，不再响应Accelerator中的快捷键，按下Esc键可以让搜索框失去焦点，此时Accelerator中的快捷键恢复响应。建议还是改回去吧。

**Comment by lrisora** [comment]
> 我认为原来的逻辑没有问题，当搜索框没有焦点时，按快捷键F可以让键框获取焦点，此时可以在键框内输入，不再响应Accelerator中的快捷键，按下Esc键可以让搜索框失去焦点，此时Accelerator中的快捷键恢复响应。建议还是改回去吧。

改回去问题主要是无意中使搜索框拥有焦点会阻挡所有快捷键
之前按F不会自动展开播放列表，不小心按到F=禁用除esc外所有快捷键
现在会展开播放列表了，但是收起播放列表后不会使搜索框放弃焦点，快捷键仍不可用
改回去的话点击左半部分使主窗口获得焦点，搜索框放弃焦点是必要的

**Comment by zhongyang219** [comment]
> > 我认为原来的逻辑没有问题，当搜索框没有焦点时，按快捷键F可以让键框获取焦点，此时可以在键框内输入，不再响应Accelerator中的快捷键，按下Esc键可以让搜索框失去焦点，此时Accelerator中的快捷键恢复响应。建议还是改回去吧。
> 
> 改回去问题主要是无意中使搜索框拥有焦点会阻挡所有快捷键 之前按F不会自动展开播放列表，不小心按到F=禁用除esc外所有快捷键 ~现在会展开播放列表了，但是收起播放列表后不会使搜索框放弃焦点，快捷键仍不可用~ 改回去的话点击左半部分使主窗口获得焦点，搜索框放弃焦点是必要的

现在增加点击左半部分使主窗口获得焦点的处理，并修正了在播放列表未显示时按F键会使快捷键不可用的问题，现在应该没什么问题了。

**Comment by lrisora** [comment]
这样很好，没问题
