### ISSUE TITLE
添加新播放列表时，文件夹/播放列表右侧下拉菜单不会更新

### ISSUE THREAD

**Issue by VictoriousRaptor** [zhongyang219/MusicPlayer2#414]
如题，不过看代码，这个下拉菜单叫做`CRecentFolderAndPlaylist`所以应该是符合设计的？但是似乎有点违反用户的直觉。

另外，从播放列表界面，歌曲-添加到新播放列表后，媒体库-播放列表中新列表的曲目数一开始为0，要选择该播放列表才会更正
![图片](https://user-images.githubusercontent.com/10308169/185555450-bb0e404a-b35a-4072-be69-8e0345ececba.png)

**Comment by lrisora** [comment]
这个列表是按上次播放时间排序的最近播放的播放列表列表的，很难改成播放列表列表
涉及到有大量播放列表时的处理等复杂问题，如果要改需要一个合理方案

新播放列表没有被加入是由于其最近播放时间为0

和直觉不一样，获取播放列表的总时长并不总能快速完成，有可能会花费难以忍受的超长时长
媒体库窗口无法等待其更新完成后再开启，所有是使用的上次留下的信息并且不进行更新
这里显示的上次播放，曲目数，总时长是上次离开此列表时存储的信息

添加到新播放列表菜单确实没有在播放列表的增减时同步，不过下面的“更多播放列表”是实时的

**Comment by zhongyang219** [comment]
确实有这个问题，没有打开过的播放列表不会显示曲目数和总播放时间，需要播放一次才会统计曲目数和播放时间。

**Comment by lrisora** [comment]
> 像添加到播放列表那里一样,搞一个"更多播放列表"可行吗

这样是能够做到的，只是好像偏离了快速切换的本意，这个下拉菜单本来是为了方便添加的，
能够接受这样的操作复杂度为什么不使用可以更加快速且方便切换的媒体库窗口

播放列表/文件夹 的“上次播放/曲目数/总时长”保持更新时点一致比较好，只更新其中一项很怪，更加难以理解
MusicPlayer2的播放列表是兼容m3u8的，容许外部编辑，
也就是说新播放列表不一定需要由程序生成，即使是“新播放列表”也可能含有媒体库不存在的歌曲
另外有的播放列表可能部分歌曲指向移动硬盘等一时无法访问的位置，更新反而不好
这里保持现状显示上次退出时状态虽然是个妥协不过综合考虑也算最佳方案了

**Comment by zhongyang219** [comment]
下拉列表显示的最近播放过的文件夹或播放列表，它的作用的快速打开最近播放过的文件夹或播放列表。新建的播放列表由于没有播放过，所有不会出现在这里。

**Comment by zhongyang219** [comment]
> 像添加到播放列表那里一样,搞一个"更多播放列表"可行吗

这个是可以做到的，但是我觉得没有必要，因为你可以通过点击旁边的“媒体库”按钮来查看更多播放列表。

**Comment by zhongyang219** [comment]
> 以及歌曲-添加到新播放列表菜单，会出现已经被删除的播放列表（~猜测是“最近的播放列表”在播放列表被删除时没有及时更新~列表更新了，是菜单选项没有更新，找不到在哪改）

这个问题可以改进
