### ISSUE TITLE
两点建议

### ISSUE THREAD

**Issue by KimigaiiWuyi** [zhongyang219/MusicPlayer2#42]
一是迷你模式下，没法完全吸附底端，会留有一条横线，具体见图
https://sm.ms/image/RpnuOdDJotkzcVZ

二是正常模式下，win10绘制的标题栏破坏了一体性，具体见图
https://sm.ms/image/rntZiA7PVRsDpJE

不错的应用！

**Comment by zhongyang219** [comment]
1. 你说的是专辑封面和窗口边缘的有一定的间距是吗？这个是我本来就是这么设计的。
2. 目前不打算对系统标题栏动刀，去掉系统标题栏会带来一系列的问题，影响用户体验。

**Comment by KimigaiiWuyi** [comment]
> 1. 你说的是专辑封面和窗口边缘的有一定的间距是吗？这个是我本来就是这么设计的。
> 2. 目前不打算对系统标题栏动刀，去掉系统标题栏会带来一系列的问题，影响用户体验。

1.你理解错了,我又截了一张图,希望可以下载下来看
http://yanxuan.nosdn.127.net/1b13a051b8c35515ef9f2a472182637b.png

2.如果问题比较多的话倒确实不需要动刀

这段时间用的最舒服的本地音乐播放器，希望继续努力！
Ps：另外有关内嵌歌词的读取tag问题希望能早日解决，这个比较重要！

**Comment by zhongyang219** [comment]
你好，第1个问题已经解决了，我很快会发布新版本，敬请期待
