### ISSUE TITLE
MusicPlayer2 转换格式报错

### ISSUE THREAD

**Issue by dr5hx** [zhongyang219/MusicPlayer2#425]
问题描述：在选择转换格式后，选择转换采样频率报错
版本：2.75x_64
![Snipaste_2022-08-29_16-17-34](https://user-images.githubusercontent.com/19305471/187157273-3af02700-60b2-4dd2-b75e-cd83075cf8a8.png)

**Comment by zhongyang219** [comment]
抱歉，可能是我在releaase的压缩包里忘了放bassmix.dll了，请[点击此处下载](https://github.com/zhongyang219/MusicPlayer2/files/9483712/bassmix.zip)，解压后根据对应的版本把bassmix.dll放到程序所在目录的Encoder目录下。

**Comment by dr5hx** [comment]
好的，谢谢。
