### ISSUE TITLE
能否支持优先显示内嵌歌词

### ISSUE THREAD

**Issue by KimigaiiWuyi** [zhongyang219/MusicPlayer2#43]
能否支持优先显示内嵌歌词，发现网易云自动匹配的歌词有错误之后手动用修改标签的方式修改歌词，但是却没有自动更新，经过检查发现并不是读取内嵌歌词而是自动网易云匹配，这样错误率感觉比较高

**Comment by KimigaiiWuyi** [comment]
http://yanxuan.nosdn.127.net/e1ea1436f3891ca071be3ddddb199182.png

**Comment by KimigaiiWuyi** [comment]
希望能加上 歌词显示真的挺重要的
感谢

**Comment by SplitGemini** [comment]
+1 ，不会从内嵌歌词（UNSYNCED LYRICS），大部分本地音乐软件都从这个tag读歌词，但是这个软件貌似不会

**Comment by zhongyang219** [comment]
最新版本已解决
