### ISSUE TITLE
”浮动播放列表“不能随软件启动

### ISSUE THREAD

**Issue by HibaraAi** [zhongyang219/MusicPlayer2#430]
软件启动的时候，并不会一起打开“浮动播放列表”（使用的是界面2），每次都要手动点开，挺麻烦的。如果可以的话，优化一下呗。

**Comment by HibaraAi** [comment]
> 我这边会一起打开啊

啊？我用的最新版，不会自动打开啊，是浮动在主窗口右边的播放列表哦

**Comment by lrisora** [comment]
![圖片](https://user-images.githubusercontent.com/43085437/190896847-7e242d15-335e-404b-aa3e-b0333db7a3da.png)
右键播放列表按钮有一个设置，关于使用哪个播放列表作为默认播放列表
软件记忆播放列表是否处于打开状态，具体是哪个由这个设置决定

**Comment by HibaraAi** [comment]
> 

ok了，牛

**Comment by HibaraAi** [comment]
> ![圖片](https://user-images.githubusercontent.com/43085437/190896847-7e242d15-335e-404b-aa3e-b0333db7a3da.png) 右键播放列表按钮有一个设置，关于使用哪个播放列表作为默认播放列表 软件记忆播放列表是否处于打开状态，具体是哪个由这个设置决定

OK了
