### ISSUE TITLE
播放歌曲 提示播放失败

### ISSUE THREAD

**Issue by niushuai233** [zhongyang219/MusicPlayer2#44]
![image](https://user-images.githubusercontent.com/38598775/76928935-d9f68000-691d-11ea-889a-159159437bd4.png)

**Comment by zhongyang219** [comment]
你好，请问是只是你电脑中部分歌曲播放失败还是所有歌曲都失败呢？如果是部分歌曲播放失败，请附上有问题的音频文件，以便我调查你的问题。同时也请附上程序所在目录下的配置文件（config.ini）和日志文件（error.log）。

**Comment by chengpopeye** [comment]
我暂时没有使用这款软件了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhongyang219"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 下午5:39
收件人: "zhongyang219/MusicPlayer2"<MusicPlayer2@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [zhongyang219/MusicPlayer2] 播放歌曲 提示播放失败 (#44)





 
你好，请问是只是你电脑中部分歌曲播放失败还是所有歌曲都失败呢？如果是部分歌曲播放失败，请附上有问题的音频文件，以便我调查你的问题。同时也请附上程序所在目录下的配置文件（config.ini）和日志文件（error.log）。

**Comment by diguaganer** [comment]
是所有歌曲都播放失败, 是在公司电脑上，等下周我会把相关文件再附上


niushuai951101@gmail.com
 
发件人： zhongyang219
发送时间： 2020-03-21 17:39
收件人： zhongyang219/MusicPlayer2
抄送： diguaganer; Author
主题： Re: [zhongyang219/MusicPlayer2] 播放歌曲 提示播放失败 (#44)
你好，请问是只是你电脑中部分歌曲播放失败还是所有歌曲都失败呢？如果是部分歌曲播放失败，请附上有问题的音频文件，以便我调查你的问题。同时也请附上程序所在目录下的配置文件（config.ini）和日志文件（error.log）。
