### ISSUE TITLE
DSD无法解析，能否支持一下

### ISSUE THREAD

**Issue by gangxiaoji** [zhongyang219/MusicPlayer2#46]
dsf格式没办法使用musicplayer播放

**Comment by zhongyang219** [comment]
你好，MusicPlayer2支持BASS插件，你可以[点击这里](http://www.un4seen.com/files/bassdsd24.zip
)下载DSD插件，然后把压缩包里的bassdsd.dll放到MusicPlayer2程序所在目录的Plugins目录下，然后重新启动MusicPlayer2即可。注意，如果是64位的MusicPlayer2，应该使用压缩包中x64下面的bassdsd.dll。

**Comment by zhongyang219** [comment]
新版2.69已经将bassdsd.dll放到压缩包里了，目前已经可以支持DSD音频了
