### ISSUE TITLE
部分歌曲的艺术家信息识别错误

### ISSUE THREAD

**Issue by xkww3n** [zhongyang219/MusicPlayer2#48]
目前发现在我的音乐库里的部分艺术家的名字最后会多出一个字符，而且没有出现的规律。但我确认这些歌曲的标签信息是正常的。以下是出现问题的其中三首音乐的播放器识别出的信息和Windows资源管理器识别的信息的截图：
![image](https://user-images.githubusercontent.com/30206355/78421514-ddfaff80-768a-11ea-9f2c-a5700adc3c61.png)

![image](https://user-images.githubusercontent.com/30206355/78421534-fbc86480-768a-11ea-9b0f-cae61c77893c.png)

![image](https://user-images.githubusercontent.com/30206355/78421551-10a4f800-768b-11ea-8b36-e313001cd682.png)

**Comment by zhongyang219** [comment]
你好，你把你出现问题的音频传上来，或者发送到我的邮箱：zhongyang219@hotmail.com，以便我调试问题。

**Comment by xkww3n** [comment]
> 你好，你把你出现问题的音频传上来，或者发送到我的邮箱：[zhongyang219@hotmail.com](mailto:zhongyang219@hotmail.com)，以便我调试问题。

图片中的3首出错歌曲（出现问题的不止3首，但就调试而言3首应该足够了）：<https://c-t.work/s/b1a50a7ee74142>

**Comment by zhongyang219** [comment]
感谢你的反馈，经过调试，问题终于解决了，确实是我的识别FLAC标签的代码有问题，如下图所示：
![image](https://user-images.githubusercontent.com/30562462/79065784-90634000-7ce5-11ea-8c2e-2629822bf45d.png)
通过查看FLAC标签区域的二进制数据，其中`ARTIST=初音ミク`后面有个6，但是那两个字节`0236`代表的是后面一个标签（COMMENT）的长度为566个字节（236转换为10进制），而`ARTIST`标签的长度在“ARTIST”往前4个字节的位置，为0013，即19个字节。

下个版本发布时会解决这个问题。

**Comment by xkww3n** [comment]
嗯，希望这个软件能越做越好
