### ISSUE TITLE
软件支持开机自动启动吗

### ISSUE THREAD

**Issue by futureflsl** [zhongyang219/MusicPlayer2#49]
我看了下选项好像没有哦，建议作者加一个开机自启动

**Comment by zhongyang219** [comment]
我认为一个播放器没必要开机自启动，如果你想要它自启动，你可以在C:\Users\<用户名>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup下放一个快捷方式

**Comment by zhongyang219** [comment]
开机自启动功能已经增加。
