### ISSUE TITLE
程序窗口位置无法保存

### ISSUE THREAD

**Issue by aglent** [zhongyang219/MusicPlayer2#5]
每次打开程序 窗口自动移动到屏幕的左上角 没法保存位置
请问是什么问题？

另外有一种歌词格式无法读取，就是每个字都有时间的那种，比如
[00:53.88]各[00:54.08]自[00:54.28]盘[00:54.48]算[00:55.29]  这个有办法解决吗？

谢谢！

**Comment by zhongyang219** [comment]
目前程序没有设置窗口位置的处理，程序启动时应该是显示在屏幕正中间的，你说的问题我并没有遇到过。
目前暂时不支持每个字都有时间的歌词，后续会考虑增加这个功能。

**Comment by aglent** [comment]
我找到规律了
删除配置文件config.ini 重新配置好 最大化窗口 接着复原窗口到默认位置（屏幕中央）关闭程序
此时config.ini里的window_width和window_hight数值就不是原来的-1了 再打开程序 窗口自动移动到屏幕左上角

**Comment by zhongyang219** [comment]
你好，感谢你的反馈，尽管我按你的方法仍然没有重现出这个问题，不过我在检查代码之后发现了可能导致这个问题的原因，并且已经修正，请试一下这个：
[MusicPlayer2_V2.62.1_beta.zip](https://github.com/zhongyang219/MusicPlayer2/files/2366594/MusicPlayer2_V2.62.1_beta.zip)
看看这个问题是否仍会出现。

**Comment by aglent** [comment]
修正版正常了 非常感谢！
