### ISSUE TITLE
插拔耳机时程序不能自动切换播放设备

### ISSUE THREAD

**Issue by EngineerLeonJ** [zhongyang219/MusicPlayer2#52]
RT，开始戴耳机，拔掉耳机后，怎么按播放都不动，必须选项里手动切换播放设备才行。
系统: win10 ltsc
扬声器：Synaptics SmartAudio HD
驱动程序详细信息："此设备不需要也未加载驱动程序文件"

**Comment by zhongyang219** [comment]
新版本中这个问题应该解决了，如果还有问题，欢迎再反馈。
