### ISSUE TITLE
v2.76.1 定位歌曲时间bug?

### ISSUE THREAD

**Issue by GJKen** [zhongyang219/MusicPlayer2#538]
升级2.76.1版之后 无法用鼠标点击3分20秒之后的歌曲跳转
不同的歌曲都有这样的结果 不是规定3分20秒这个时间段, 就像是有一块东西挡住不给点击
![image](https://user-images.githubusercontent.com/69197105/234331110-4adca66b-f0e9-49ce-a4f6-e3658b428a81.png)

**Comment by GJKen** [comment]
> 我这不少歌也有类似的问题。

我刚刚发现应该是覆盖文件更新才会有这种问题
删掉旧文件保留playlist | config.ini | song_data.dat
这些是必须要保留的配置文件

**Comment by zhongyang219** [comment]
感谢反馈，现在问题已修正。
目前的问题是进度被音量调节按钮覆盖的部分会无法点击，如下图红框部分所示，即使音量调节按钮没有显示。
![image](https://user-images.githubusercontent.com/30562462/236476526-d805e863-f461-4d26-bd3b-caf17a4706d8.png)
这个bug现在已经修正，请等待下个版本更新。
