### ISSUE TITLE
点击媒体库后，会有很长一段时间处于无响应状态

### ISSUE THREAD

**Issue by ALICEOFALICE** [zhongyang219/MusicPlayer2#54]
在我点击媒体库按钮后，窗体会卡住（但是播放中的音乐还是正常了）
希望能解决一下
系统：win10 64 专业版 1909
![image](https://user-images.githubusercontent.com/41146748/80590947-5c12b200-8a4f-11ea-861a-d778799c37e3.png)

**Comment by zhongyang219** [comment]
新版本中应该已经解决了
