### ISSUE TITLE
存在一些问题

### ISSUE THREAD

**Issue by ECM-xiaokong** [zhongyang219/MusicPlayer2#540]
1.   不支持虚拟桌面，切换虚拟桌面时字幕可以一起切换，但迷你窗口不行，还停留在原来的桌面 
**--期望修复结果：切换虚拟桌面时，可以将迷你窗口一起切换**

2.   按win + D快捷键有一定几率迷你桌面会最小化,需要在任务栏里右键托盘图标点击迷你模式/还原按钮才能显示出来
**--期望修复结果：按win + D快捷键不会使窗口最小化**

3.   打开应用程序时，有几率遮住字幕和迷你窗口（应用程序最大化或者窗口化的应用程序都有几率），如果要重新让字幕和迷你窗口显示在最前端。需要最小化遮住迷你窗口的应用程序，点击迷你模式/还原按钮，最大化应用程序，在任务栏里点开软件。再次点击切换迷你模式/还原按钮。此时迷你窗口成功在最前端。在任务栏里右键托盘图标，点击两次显示/隐藏桌面歌词，此时字幕和迷你窗口都在最前端
**--期望修复结果：窗口始终在最前端**

4.   歌词对齐问题，若开启双行显示，则歌词设置里的，左对齐，右对齐，居中均无效，只会上行右对齐，下行左对齐。左对齐，右对齐，居中只对单行歌词生效 
**--期望修复结果：左对齐，右对齐，居中支持双行歌词**

以上问题希望尽快修复

**Comment by ppxx21** [comment]
你这甲方提需求呢？
