### ISSUE TITLE
现在win11还能使用任务栏歌词吗？

### ISSUE THREAD

**Issue by GuoJikun** [zhongyang219/MusicPlayer2#544]
win11 任务栏歌词选项直接是灰色的
![image](https://user-images.githubusercontent.com/21582741/236590112-b30fba12-1096-43cd-b1d8-557f97a54393.png)

操作系统版本：
Windows 11 专业版
22H2
22621.1635

**Comment by zhongyang219** [comment]
不行了，因为微软已经把搜索框砍掉了。虽然最新的Windows11中可以显示完整的搜索框，但是新版的搜索框是微软重构后的，无法找到窗口的句柄。

**Comment by GuoJikun** [comment]
> 不行了，因为微软已经把搜索框砍掉了。虽然最新的Windows11中可以显示完整的搜索框，但是新版的搜索框是微软重构后的，无法找到窗口的句柄。

有没有其它的方案呢？比如桌面歌词可以可以拖动到任务栏上且永久在最上层

**Comment by jiandan5997** [comment]
想要 +1
