### ISSUE TITLE
快捷键BUG

### ISSUE THREAD

**Issue by sbwfnhn** [zhongyang219/MusicPlayer2#56]
快捷键上一首下一首，设置了，退出软件重启也无效。
如果只设个别快捷键，很多快捷键都会乱掉。显示无。上图[https://i.ibb.co/98ttV3v/20200512093831.png](url)
https://ibb.co/p0yyRrP

**Comment by topve** [comment]
标记一下，我也是一样的问题，设置的快捷键，重启又失效了。

**Comment by usagi20** [comment]
标记一下 我也是这个问题  设置了下一首的快捷键 关应用重启后又没了

**Comment by zhongyang219** [comment]
你好，可以描述一下你详细的操作步骤吗？请尽量把你每一步操作都描述清楚，以帮助我调查你的问题。

**Comment by zhongyang219** [comment]
另外，下面的文本框里显示“无”是正常的，只要列表中显示了快捷键就表示已经设置了。

**Comment by nalabla** [comment]
同，快捷键设置不能保存，每次重启都需要重新设置。不过还是感谢（。＾▽＾）

**Comment by zhongyang219** [comment]
@nalabla 为什么我这里一直都是好的啊，是不是你们操作方法不对啊

**Comment by zhongyang219** [comment]
@nalabla 我知道了，好像如果把部分快捷键设置为“无”就会有问题

**Comment by zhongyang219** [comment]
某个快捷键设置为无之后，后面的快捷键失效的问题已经解决了，但是关于快捷键会乱掉的问题还要进一步调查。

**Comment by nalabla** [comment]
> @nalabla 我知道了，好像如果把部分快捷键设置为“无”就会有问题

抱歉，我试了一下，快捷键都设置了，但是重启后还是会恢复默认。

**Comment by sbwfnhn** [comment]
新版本的测试已无BUG，可以关闭了

**Comment by sbwfnhn** [comment]
新版本已正常
