### ISSUE TITLE
打开本地文件夹 可以支持循环打开子文件夹吗？

### ISSUE THREAD

**Issue by Hydrogx** [zhongyang219/MusicPlayer2#57]
因为我本地歌曲按照歌手/专辑名称 这样的顺序保存，目前需要手动定位到一个个文件夹，不能自动获取子文件夹的内容

**Comment by zhongyang219** [comment]
你好，在文件夹模式下不支持自动扫描子文件夹，但是在播放列表模式下可以添加一个文件夹及其子文件夹的音频文件到播放列表。
具体步骤为：
- 新建一个播放列表
- 打开刚刚新建的播放列表
- 点击播放列表上方的“添加”按钮，选择“添加文件夹”
- 在“选择文件夹”界面勾选“包含子文件夹”
另外，你还可以在“媒体库”——“文件夹浏览”中的左侧树中选中一个文件，右击鼠标右键，选择“添加到播放列表”，或“添加到新播放列表并播放”也可以将选中文件的子文件夹中的音频添加到播放列表中。

**Comment by zhongyang219** [comment]
最新版本已经支持文件夹模式下包含子文件夹
