### ISSUE TITLE
歌曲内嵌封面体积超过一定大小后会显示错误

### ISSUE THREAD

**Issue by xkww3n** [zhongyang219/MusicPlayer2#58]
下图中的歌曲的内嵌封面分辨率为1003*1003，体积为109.61kb，软件显示正常：
![image](https://user-images.githubusercontent.com/30206355/82132698-258db300-9815-11ea-8a57-632ea8ea0738.png)
![image](https://user-images.githubusercontent.com/30206355/82132737-9a60ed00-9815-11ea-811b-7cae45538bef.png)

下图中歌曲的内嵌封面分辨率为1600*1600，大小为2.35mb，显示出现色带：
![image](https://user-images.githubusercontent.com/30206355/82132732-86b58680-9815-11ea-816f-b122eb3fc7e8.png)
![image](https://user-images.githubusercontent.com/30206355/82132733-8d43fe00-9815-11ea-9591-30963c9a8ff9.png)

**Comment by zhongyang219** [comment]
你好，这个问题确实存在，我已经在下个版本中修正，请等待更新。

**Comment by zhongyang219** [comment]
问题已解决，请更新到最新版本。
