### ISSUE TITLE
不能自定义歌词下载位置

### ISSUE THREAD

**Issue by ryan5u3n** [zhongyang219/MusicPlayer2#59]
发现歌词lrc文件都是放在mp3所在的位置，这样文件管理很乱，然后设置里面的歌词文件夹即使是设置了，也一样会把下载到音乐文件位置。
建议可以自定义歌词下载的位置，方便文件管理。

**Comment by soralife** [comment]
目前版本可以实现，虽然有点绕
选项设置->歌词设置->歌词文件夹设置歌词存储路径(绝对路径)
设置之后在
选项设置->常规设置->下载设置->歌词保存位置选项
中的“保存在歌词文件夹”选项就可选了
我现在就把所有歌词堆到一起
”歌词文件夹设置歌词存储路径“这里未设置时默认值长得像是相对路径
但是实际貌似不支持相对路径 (未确认，因为不能编辑) 有误导成分

**Comment by soralife** [comment]
再补充一下
歌词保存位置选项有两处
一处在 选项设置->常规设置->下载设置->歌词保存位置选项
另一处在打开“下载选项(通过网易云音乐API)”窗口内，这里有另一个独立的下载选项
我一开始设置好了选项设置之后也没注意到
大概是为了大量导入后平时更加灵活易用？

**Comment by soralife** [comment]
彻底理清了 关于 歌词保存位置选项 总共有三处

选项设置中的 负责启用没有歌词时自动下载时 “没有歌词时自动下载” 的位置
“下载选项(通过网易云音乐API)”窗口中的
“歌词批量下载(通过网易云音乐API)”窗口中的

这三个保存位置选项相互独立互不影响
