### ISSUE TITLE
无法关闭歌词内的罗马音

### ISSUE THREAD

**Issue by Chairowell** [zhongyang219/MusicPlayer2#591]
**不知道如何关闭歌词罗马音**
**有没有什么方法调整歌词里罗马音的显示，或者关闭罗马音？**

迷你窗口模式下，想看歌词却是显示的是罗马音
![image](https://github.com/zhongyang219/MusicPlayer2/assets/64683147/d753181e-fcba-44e7-bb47-4c0cb47e83ee)
标准窗口模式下，罗马音高亮（想要译文高亮）
![image](https://github.com/zhongyang219/MusicPlayer2/assets/64683147/d72f21aa-0922-4a9f-8e28-20521ecab49d)

**Comment by lrisora** [comment]
现在并没有支持显示罗马音，
按ctrl+shift+E打开歌词编辑，其中“ / ”前面的部分被视为歌词，后面的被视为翻译
翻译显示可以关闭，只有歌词才有进度高亮
这个歌词不是MusicPlayer2下载的使用了不一样的结构保存

不影响其他程序使用的话或许可以用歌词编辑窗口编辑菜单的“交换歌词原文和翻译”选项

**Comment by Chairowell** [comment]
好的，感谢
问题已解决

**Comment by GRFTSOL** [comment]
请问这个罗马音是用什么添加的？网易云下载的歌词吗？

**Comment by Chairowell** [comment]
> 请问这个罗马音是用什么添加的？网易云下载的歌词吗？

使用lx-music下载的lrc文件

**Comment by GRFTSOL** [comment]
> > 请问这个罗马音是用什么添加的？网易云下载的歌词吗？
> 
> 使用lx-music下载的lrc文件

lx-music可以直接把歌词嵌入本地文件么，还是可以下载歌词手动嵌入？

**Comment by Chairowell** [comment]
在下载设置中勾选：如果有罗马音下载到歌词文件（新的歌词文件）
并不支持直接嵌入已有的本地文件，需要手动嵌入
