### ISSUE TITLE
希望在查找文件窗口添加下一首播放的功能

### ISSUE THREAD

**Issue by odlove** [zhongyang219/MusicPlayer2#594]

**Comment by odlove** [comment]
control+f的那个界面

**Comment by lrisora** [comment]
MusicPlayer2受播放逻辑结构限制，下一首播放只能用于“已存在于当前播放的列表中”的歌曲
具体参考 #412 
请使用一个够大的列表以避免体验不佳
或者先将所选歌曲先加入当前列表（但是这个行为会复位已设置的下一曲播放队列）
