### ISSUE TITLE
MusicPlayer与windows窗口刷新问题

### ISSUE THREAD

**Issue by aglent** [zhongyang219/MusicPlayer2#6]
你好，我这里每天都会有一个奇怪的问题，不知道是不是bug。
运行程序，加载播放列表，播放一段时间 或者只要点击播放后暂停一段时间 windows窗口刷新变慢
具体现象：比如打开资源管理器 打开计算器或其他程序 整个界面不是一次性出现 而是从上到下刷出来的 有迟滞现象
关闭MusicPlayer 这种现象消失  （打开程序 不播放也不会出现这个问题）

不确定是我自己的缘故还是程序的bug

**Comment by zhongyang219** [comment]
我最近解决了一个由于GDI对象泄漏导致程序崩溃的问题，你的问题可能和这个有关，你可以试试这个：[MusicPlayer2_V2.62.1(beta).zip](https://github.com/zhongyang219/MusicPlayer2/files/2608132/MusicPlayer2_V2.62.1.beta.zip)
再看看问题是否依然存在。

**Comment by aglent** [comment]
@zhongyang219 
正在试 1个多小时了 还没有出现问题

**Comment by aglent** [comment]
好几个小时 一切正常 应该是解决了 非常感谢
