### ISSUE TITLE
万分感谢！！  ^_^

### ISSUE THREAD

**Issue by hold88888888** [zhongyang219/MusicPlayer2#600]
~@^_^@~

**Comment by hold88888888** [comment]
这就是我要找的播放器，哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by hold88888888** [comment]
![是你-梦然 mp3 - MusicPlayer2 2023_8_18 12_44_37](https://github.com/zhongyang219/MusicPlayer2/assets/105548184/b51bf5cb-36dc-41c2-8ca6-12a2b594912e)

**Comment by hold88888888** [comment]
![MusicPlayer2 2023_8_18 12_47_28](https://github.com/zhongyang219/MusicPlayer2/assets/105548184/15317518-ea43-4f32-8d8d-8a1b971a7ccd)

**Comment by hold88888888** [comment]
![a w  - hymn for the weekend - MusicPlayer2 2023_8_18 13_10_42](https://github.com/zhongyang219/MusicPlayer2/assets/105548184/69331e57-6c53-48bc-a053-cdb775485412)

**Comment by leangjia** [comment]
全屏歌词就更完美了
