### ISSUE TITLE
没有找到歌词

### ISSUE THREAD

**Issue by taxi2006** [zhongyang219/MusicPlayer2#611]
新系统Win11，想下载歌词但是“没有找到歌词”，无论什么歌的歌词都找不到。之前的系统没有问题。请问是因为什么原因连接不到网易云API吗？

**Comment by lrisora** [comment]
MusicPlayer2网络连接使用系统代理，
可以先试试浏览器能否直接访问api `http://music.163.com/api/search/get/?s=搜索内容&limit=30&type=1&offset=0`
网易的api接口使用某些国家的ip会出问题 #180

**Comment by taxi2006** [comment]
![163](https://github.com/zhongyang219/MusicPlayer2/assets/145529397/ffb0821a-b1ef-40ad-8041-d772047629b3)
@lrisora 是这样的吗？

**Comment by lrisora** [comment]
是这样的，这说明api是正常的，我觉得可能是系统代理配置有问题导致的连不上网
可以开启“启动时检查更新”看看启动软件1~2分钟后软件目录下的error.log有没有新增`http get **********Error code: ****`
来确认
如果error.log已经大的难以打开就先删掉，有错误输出会重新创建

**Comment by taxi2006** [comment]
![settings](https://github.com/zhongyang219/MusicPlayer2/assets/145529397/2a728670-80eb-430e-8b9e-1a55a6c90eeb)
是这个设置吗？开了但是重开之后没有error.log在目录里。就算我“在线查看“已存在”的歌曲，也显示找不到歌曲
![404](https://github.com/zhongyang219/MusicPlayer2/assets/145529397/fb555ebf-f568-4145-a26f-a82088ee38a3)
谢谢您抽空帮忙解决问题

**Comment by lrisora** [comment]
![圖片](https://github.com/zhongyang219/MusicPlayer2/assets/43085437/0b50b341-11ad-429b-8c40-c318ab9502f7)
这个设置，会检查软件更新

error.log不在音频目录，在MusicPlayer2.exe旁边，如果你设置了（现在好像是默认值）保存到Appdata目录
那么error.log会保存到Appdata\Roaming\MusicPlayer2\
可以点击“打开配置文件所在目录”按钮打开（我之前忘记这个了）

**Comment by taxi2006** [comment]
![files](https://github.com/zhongyang219/MusicPlayer2/assets/145529397/d9b29514-8f8e-4b7f-96c0-d24adf98e34e)
检查更新是开了，但是点击“打开配置文件所在目录”按钮之后，里面没有error.log

**Comment by lrisora** [comment]
[MusicPlayer2.zip](https://github.com/zhongyang219/MusicPlayer2/files/12708378/MusicPlayer2.zip)
试试这个，这个版本启用了网络请求开启时的log，
程序会在发起网络请求时写一行log，
一般的版本只在出错时写log，
注意windows的网络超时好像是30s，发起的log之后30s后才会写失败的log

我觉得多半还是系统代理的问题，看看“设置”->“网络和internet”->“代理”里面是什么样的

**Comment by taxi2006** [comment]
有log了，但是没用代理，人在北美，需要代理吗
![proxy](https://github.com/zhongyang219/MusicPlayer2/assets/145529397/e5d1adc7-0d83-4cbb-b8f2-9e9b4006caf4)
[error.log](https://github.com/zhongyang219/MusicPlayer2/files/12733596/error.log)

**Comment by lrisora** [comment]
确实用美国ip就既不报错也没有结果（我上次试好像还没问题来着我记得，不过不是现在的ip）
我找到问题了，现有的代码靠字符串查找解析json，北美的api的json有些键的顺序变了导致解析失败
不过即使这个问题解决了还是“不可用”的状态，因为用北美ip浏览器访问api，仔细观察结果
[http://music.163.com/api/search/get/?s=%E4%B8%8E%E6%88%91%E6%97%A0%E5%85%B3&limit=30&type=1&offset=0](http://music.163.com/api/search/get/?s=%E4%B8%8E%E6%88%91%E6%97%A0%E5%85%B3&limit=30&type=1&offset=0)
虽然有返回不过实际上返回结果完全不对，不知道他在搜索什么
这一点我不知道如何解决，可能在北美网易的api不是这个？还是要对“搜索内容”做某种编码？我不清楚

你可能需要一个回国代理把系统代理访问126.net,163.com的流量路由回国

**Comment by taxi2006** [comment]
不是很懂，但是谢谢帮忙解决，虽然最近有点问题但是一直很好用！

**Comment by CarterAli** [comment]
看来意大利IP也有这个问题 xD 刚知道这个软件。确实很好用。我看看怎么想办法解决xD

**Comment by silencer1127** [comment]
> 确实用美国ip就既不报错也没有结果（我上次试好像还没问题来着我记得，不过不是现在的ip） 我找到问题了，现有的代码靠字符串查找解析json，北美的api的json有些键的顺序变了导致解析失败 不过即使这个问题解决了还是“不可用”的状态，因为用北美ip浏览器访问api，仔细观察结果 http://music.163.com/api/search/get/?s=%E4%B8%8E%E6%88%91%E6%97%A0%E5%85%B3&limit=30&type=1&offset=0 虽然有返回不过实际上返回结果完全不对，不知道他在搜索什么 这一点我不知道如何解决，可能在北美网易的api不是这个？还是要对“搜索内容”做某种编码？我不清楚
> 
> 你可能需要一个回国代理把系统代理访问126.net,163.com的流量路由回国
> 
> 我有一个美国ip不行，一个归属的加拿大ip（广播到日本）却可以，还是很碰运气

用 POST 请求可以拿到正常的数据。随便找一个线上REST测试平台，比如 https://reqbin.com. 输入上面的这个URL: `https://music.163.com/api/search/get/?s=%E4%B8%8E%E6%88%91%E6%97%A0%E5%85%B3&limit=30&type=1&offset=0`, 然后在下面数据窗口输入 （text 模式）
```
limit=10
type=1
offset=0
```
发送这个请求就可以得到正确的 json。

在 `InternetCommon.cpp` ~495行 `int rtn = CInternetCommon::HttpPost(wstring(url), search_result);`，虽然调用的 HttpPost，但是实际 POST 的数据没有传到第100行 `int CInternetCommon::HttpPost(const wstring & str_url, wstring & result, string& body, wstring& headers, bool custom_ua)` 第三个参数 `body` 里面。
