### ISSUE TITLE
推广下自己的纯本地音乐播放器：Loop Sound Player

### ISSUE THREAD

**Issue by Violexjj** [zhongyang219/MusicPlayer2#616]
功能肯定没有这个MusicPlayer2全面丰富，因为我主打的是UI美观，毕竟我是一个十分业余、十分业余、十分业余的爱好者而已，以至于我编辑歌词和封面都是用的MusicPlayer2。
介绍视频在b站，下载地址在b站简介里面，欢迎体验！
https://www.bilibili.com/video/BV1or4y1X7hc/?spm_id_from=333.337.search-card.all.click&vd_source=1d647b5242d169c0c81dea749c37bf1d

**Comment by Violexjj** [comment]
有什么问题最好在b站评论，因为github我不一定会及时收到消息。

**Comment by xkonglong** [comment]
如果没有放在github, 就不要到这里推广了.

**Comment by Violexjj** [comment]
> 如果没有放在github, 就不要到这里推广了.

你怎么知道我没放呢，只不过不经常更新github里面的，所以就没放。
