### ISSUE TITLE
对歌单的一点建议

### ISSUE THREAD

**Issue by chenjiarui31** [zhongyang219/MusicPlayer2#619]
# 首先歌单这个功能真的非常重要

但是在播放已经编辑好了的歌单时，打开另外一首歌， __这首歌就会被加到编辑好了的歌单里__ ，但有时候我只是 __单纯__ 地想要听一下另外一首歌而已 

希望在已编辑的歌单里打开另一首歌时，将其添加到 __默认播放列表__ ，而不是 __当前的歌单__

**Comment by lrisora** [comment]
播放列表模式下拖放音频文件到窗口被视为向播放列表添加歌曲
直接在资源管理器双击打开/右键打开（如果MusicPlayer2是对应格式的默认打开方式的话）是添加到默认播放列表播放
资源管理器多选右键打开目前有bug，已在#598修正

**Comment by chenjiarui31** [comment]
thank you！
