### ISSUE TITLE
播放列表问题

### ISSUE THREAD

**Issue by eail-zh** [zhongyang219/MusicPlayer2#63]
使用过程中发现软件在打开后其播放列表为[**默认**]，而非软件在上次关闭时所处的播放列表。<br/><br/>
软件有两个默认的播放列表：[**默认**]、[**我喜欢的音乐**]，
- 当媒体库的播放列表仅有这两个默认的播放列表且当前打开的列表为[**我喜欢的音乐**]时，关闭软件再打开，当前所处播放列表为[**默认**]
- 当媒体库有用户添加的播放列表，即播放列表数大于等于 3 时，打开软件时所处的播放列表就是关闭时的播放列表。

**Comment by Purmap** [comment]
另外，播放列表切换起来有点麻烦，要到媒体库里面选中，能否选用下拉列表形式？
