### ISSUE TITLE
播放列表可以自定义顺序吗？

### ISSUE THREAD

**Issue by Joackk** [zhongyang219/MusicPlayer2#636]
默认的排序似乎只有，文件名、音轨什么的这些排序，请问大佬可以自己拖动或者指定播放顺序吗？

**Comment by lrisora** [comment]
播放列表模式下歌曲条目可以自由排序，文件夹模式下不行
选中歌曲右键有`上移（ctrl+↑）` `下移（ctrl+↓）`菜单项
选项设置->媒体库->播放列表->禁用播放列表拖放排序 未选中时允许拖放排序选中项

文件夹模式无法保存自定义的顺序所以不提供任意排序功能

**Comment by Joackk** [comment]
> 播放列表模式下歌曲条目可以自由排序，文件夹模式下不行 选中歌曲右键有`上移（ctrl+↑）` `下移（ctrl+↓）`菜单项 选项设置->媒体库->播放列表->禁用播放列表拖放排序 未选中时允许拖放排序选中项
> 
> 文件夹模式无法保存自定义的顺序所以不提供任意排序功能

大佬，这个播放列表模式和文件夹啥区别哇？是我把文件夹的音乐都添加到播放列表？试了下把文件夹的音乐都加入了播放列表，然后我该怎么开那个播放列表模式啊？

**Comment by Joackk** [comment]
> 播放列表模式下歌曲条目可以自由排序，文件夹模式下不行 选中歌曲右键有`上移（ctrl+↑）` `下移（ctrl+↓）`菜单项 选项设置->媒体库->播放列表->禁用播放列表拖放排序 未选中时允许拖放排序选中项
> 
> 文件夹模式无法保存自定义的顺序所以不提供任意排序功能

找到了，感谢大佬

**Comment by Joackk** [comment]
> 播放列表模式下歌曲条目可以自由排序，文件夹模式下不行 选中歌曲右键有`上移（ctrl+↑）` `下移（ctrl+↓）`菜单项 选项设置->媒体库->播放列表->禁用播放列表拖放排序 未选中时允许拖放排序选中项
> 
> 文件夹模式无法保存自定义的顺序所以不提供任意排序功能

大佬播放界面的UI，有集中下载的地方吗？

**Comment by lrisora** [comment]
媒体库窗口的前两个标签页可以切换
文件夹模式可以理解打开时根据文件夹内容实时生成的播放列表，
如文件夹有新增歌曲那么下次打开就会包含，也不能排除文件夹中的部分歌曲
播放列表模式歌曲需要手动添加但可以自定义含有哪些歌曲以及排序

release的应该就是所有了（现在ui1和ui2内嵌到了程序内，可以在[这里](https://github.com/zhongyang219/MusicPlayer2/tree/master/MusicPlayer2/skins)下载）

**Comment by Joackk** [comment]
> 媒体库窗口的前两个标签页可以切换 文件夹模式可以理解打开时根据文件夹内容实时生成的播放列表， 如文件夹有新增歌曲那么下次打开就会包含，也不能排除文件夹中的部分歌曲 播放列表模式歌曲需要手动添加但可以自定义含有哪些歌曲以及排序
> 
> release的应该就是所有了（现在ui1和ui2内嵌到了程序内，可以在[这里](https://github.com/zhongyang219/MusicPlayer2/tree/master/MusicPlayer2/skins)下载）

soga，感谢大佬
