### ISSUE TITLE
纯中文歌词在主页面无法分行，歌词文件为正常

### ISSUE THREAD

**Issue by RxBlazeWave** [zhongyang219/MusicPlayer2#647]
<img width="828" alt="2023-12-14_112853" src="https://github.com/zhongyang219/MusicPlayer2/assets/136913696/d65d9528-a071-4cbb-bd85-98098378b445">
<img width="417" alt="2023-12-14_112900" src="https://github.com/zhongyang219/MusicPlayer2/assets/136913696/93c7091c-820b-4420-9a20-9f4841bd50da">

**Comment by lrisora** [comment]
https://www.ruanyifeng.com/blog/2006/04/post_213.html
应该是这个问题，你的歌词是MAC系统下制作的，
可以复制到一个稍微好一点的编辑器里改一下
这里MusicPlayer2应该兼容的，我之后会加上（等现在的patch03完成之后）

**Comment by RxBlazeWave** [comment]
> https://www.ruanyifeng.com/blog/2006/04/post_213.html 应该是这个问题，你的歌词是MAC系统下制作的， 可以复制到一个稍微好一点的编辑器里改一下 这里MusicPlayer2应该兼容的，我之后会加上（等现在的patch03完成之后）

啊啊确实是这样，我使用Ultra Edit全选后选择“使用换行符换行”保存后重新关联歌词文件就正常了
