### ISSUE TITLE
连接蓝牙耳机时播放异常

### ISSUE THREAD

**Issue by eail-zh** [zhongyang219/MusicPlayer2#65]
今天打开软件用蓝牙耳机听歌时发现耳机内没声音，但用其它播放器播放时却没有问题。

测试结果如下：
1. 打开蓝牙 --> 连接蓝牙耳机 --> 打开软件 --> 开始播放，无异常。
2. 打开软件 --> 打开蓝牙 --> 连接蓝牙耳机 --> 开始播放，蓝牙耳机无声音，软件使用的是笔记本电脑自带的扬声器播放。

测试过程中还发现了另外一个与之相关的问题：<br />使用先打开蓝牙、连接蓝牙耳机，再打开软件的方式播放音乐，能够正常听歌，但在此时关闭蓝牙（或断开蓝牙耳机连接），歌曲将保持当前播放进度无法改变，切换其它歌曲其进度也将保持为 **0:00** ，即便重新打开蓝牙并连接上蓝牙耳机也没用

**Comment by zhongyang219** [comment]
你好，现在已经更新到2.70.1版本，这个问题应该已经解决了，如果仍然遇到这个问题，可以在主菜单”工具“中选择”重新初始化播放器“（快捷键Ctrl+Q）即可解决。
