### ISSUE TITLE
多个艺术家的歌曲只能显示一个

### ISSUE THREAD

**Issue by cheliox** [zhongyang219/MusicPlayer2#66]
歌曲有多个艺术家时，只会显示最后一个艺术家。

**Comment by cheliox** [comment]
多个艺术家一般是用分号隔开的

**Comment by zhongyang219** [comment]
你好，请提供一下有问题的音频文件以帮助我调查这个问题

**Comment by cheliox** [comment]
> 你好，请提供一下有问题的音频文件以帮助我调查这个问题

选了一首 https://cheliox.lanzous.com/imrMidpebgj

**Comment by zhongyang219** [comment]
问题已解决，请等待下个版本更新
