### ISSUE TITLE
音乐播放进度条问题

### ISSUE THREAD

**Issue by Cody-Travers** [zhongyang219/MusicPlayer2#669]
如题，进度条到大概1/8左右及以后的位置就无法点击跳转到了，但是由别的位置拖动到这里可以。

https://github.com/zhongyang219/MusicPlayer2/assets/139093182/6f3bc9ad-fdc2-4825-b1c4-7c2d6b94df04

**Comment by Cody-Travers** [comment]
很奇怪，调成迷你小窗模式在里面点进度条都没这问题，就只有主界面点击才有，大佬有时间可以看下麻烦了。

**Comment by lrisora** [comment]
#538 
在代码中已修正，不过还没Release
可以在Action下载新版

**Comment by Cody-Travers** [comment]
解决了，感谢大佬！！
