### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by qijianjun** [zhongyang219/MusicPlayer2#7]
发现跟编辑器常用的ctrl+shift+left/right冲突了，似乎没有更改设置快捷键的地方。

**Comment by zhongyang219** [comment]
谢谢反馈，预计后续版本会增加可自定义快捷键的功能

**Comment by zhongyang219** [comment]
你好，新版本V2.63已经发布了，增加了全局快捷键设置的功能。

**Comment by qijianjun** [comment]
谢谢，已下载并设置。
不过尝试设置ctrl+shift+numpad4这样的键位时，不能成功，似乎不支持numpad的数字键。

**Comment by zhongyang219** [comment]
不能设置“Ctrl+Shift+数字小键盘”的键位似乎是系统的限制，并非程序的问题，你可以使用“Ctrl+Alt+数字小键盘”的键位。

**Comment by qijianjun** [comment]
谢谢，已经设置了。
