### ISSUE TITLE
封面图片问题

### ISSUE THREAD

**Issue by soralife** [zhongyang219/MusicPlayer2#70]
[封面样本.zip](https://github.com/zhongyang219/MusicPlayer2/files/4808992/default.zip)
封面图片均来自网易云音乐下载 有的是内嵌封面提取
其中_孤独的乐章.jpg_分辨率过大 
程序对大部分操作没反应直到使用多媒体键暂停 同时cpu单线程满载同时内存使用超过300M
_AlbumCover - 曲婉婷 - Love Birds.jpg_与_AlbumCover - 王心凌 - 远在眼前的你.jpg_使用CMYK颜色模式
无法正常缩放
详见

![批注 2020-05-24 011348](https://user-images.githubusercontent.com/43085437/85218389-77a19580-b3cc-11ea-9b73-83b4fbcf8e64.png)

![批注 2020-06-20 222150](https://user-images.githubusercontent.com/43085437/85218397-86884800-b3cc-11ea-95cc-6b21c2771a81.png)

或许这些都是异常的封面图片但也需要兼容一下

**Comment by Nydxsst** [comment]
实测无法显示m4a格式音乐的自带封面（音乐标签里集成的），如果不设置自动下载网络上的封面就没有封面，而用网易云音乐或者用手机的“Aplayer”app都可以显示，麻烦作者大大了

**Comment by zhongyang219** [comment]
感谢你的反馈，目前正在调查中。目前确实存在封面图片过大导致程序卡顿的问题，正在想办法解决。

**Comment by SplitGemini** [comment]
同m4a封面无法显示
