### ISSUE TITLE
播放出错

### ISSUE THREAD

**Issue by pengweizhong** [zhongyang219/MusicPlayer2#700]
播放《321-对不起 徐良，小凌》时报错。提示：播放出错。  
请协助一下，谢谢。
![image](https://github.com/zhongyang219/MusicPlayer2/assets/48546556/d07b5960-0a91-44f9-866f-4e3818fb64c8)

**Comment by lifegpc** [comment]
可以的话，发一下歌曲文件

**Comment by pengweizhong** [comment]
[](url)，无法发送，提示附件格式不支持。

**Comment by lifegpc** [comment]
压缩成 zip 或者你直接丢个网盘链接也行

**Comment by lifegpc** [comment]
或者有错误日志也行。然后你用的是什么内核，播放设置是怎样的。啥都没有的话，很难找到问题根源的。

**Comment by pengweizhong** [comment]
不好意思，这两天忙，稍后我压缩一下文件

**Comment by pengweizhong** [comment]
附件在这里
[321对不起.zip](https://github.com/zhongyang219/MusicPlayer2/files/15144587/321.zip)

**Comment by pengweizhong** [comment]
> 附件在这里 [321对不起.zip](https://github.com/zhongyang219/MusicPlayer2/files/15144587/321.zip)

似乎所有的m4a格式都是这样，下面是我的系统信息：
![image](https://github.com/zhongyang219/MusicPlayer2/assets/48546556/d239391e-649c-4a54-ace1-7dc0fe54d1d0)

**Comment by pengweizhong** [comment]
太长时间没有响应
