### ISSUE TITLE
播放器打不开

### ISSUE THREAD

**Issue by Cody-Travers** [zhongyang219/MusicPlayer2#714]
点击播放一个mp3文件后就变成这样了，不知道问题出现在哪，大佬有时间可以看看

https://github.com/zhongyang219/MusicPlayer2/assets/139093182/166ea296-1431-469f-9c75-6102e636759c

**Comment by Cody-Travers** [comment]
![image](https://github.com/zhongyang219/MusicPlayer2/assets/139093182/91dbe4bf-9373-464b-849a-391d75a053ed)

**Comment by Cody-Travers** [comment]
> 我需要上面说的dmp文件，zip压缩后发到这里，以及生成dmp文件时你用的哪个Action版本 如果操作可以复现最好能用最新的Action版本

昨天确实弹出这个错误提示了，今天我试图复现就彻底进不去程序了，和上面那段视频一样白一下就闪退，temp也没有相关文件

**Comment by lrisora** [comment]
先备份一下当前状态（把整个文件夹复制一下/压缩也行）
之后删除config.ini
看看好了没有
如果方便的话可以二分删除config.ini的内容，测试是哪一条的问题

我猜你可能倒退了程序版本，新exe产生的配置/媒体库dat不保证能够被旧版读取
倒退exe的话需要当时的那套附属文件

**Comment by Cody-Travers** [comment]
> 先备份一下当前状态（把整个文件夹复制一下/压缩也行） 之后删除config.ini 看看好了没有 如果方便的话可以二分删除config.ini的内容，测试是哪一条的问题
> 
> 我猜你可能倒退了程序版本，新exe产生的配置/媒体库dat不保证能够被旧版读取 倒退exe的话需要当时的那套附属文件

按您说的删除config.ini后进入会弹错误提示了，temp文件我放下面。我是先在release里下载2.76.1版本解压，然后下载fork里最新操作生成的附件里面的MusicPlayer2.x64文件再加压到之前的2.76.1文件夹里进行替换来更新的，不知道这样操作对不对
[20240601154154_MusicPlayer2.exe.dmp](https://github.com/user-attachments/files/15520910/20240601154154_MusicPlayer2.exe.dmp)

**Comment by lrisora** [comment]
多半修好了，是我的问题
媒体库目录”D:\“长度太短，-6之后无符号数溢出了

**Comment by Cody-Travers** [comment]
> 多半修好了，是我的问题 目录”D:\“长度太短，-6之后无符号数溢出了

问题修复了，感谢大佬！！

**Comment by Cody-Travers** [comment]
> 多半修好了，是我的问题 目录”D:\“长度太短，-6之后无符号数溢出了

问题解决了，感谢大佬！！
