### ISSUE TITLE
wav格式音频属性获取失败

### ISSUE THREAD

**Issue by 0x738A** [zhongyang219/MusicPlayer2#72]
![image](https://user-images.githubusercontent.com/43438471/86690739-c725c980-c03a-11ea-91ce-129da1c19c8b.png)

**Comment by zhongyang219** [comment]
你好，当前版本暂时不支持获取wav格式的音频信息，会在后续版本中优化。

**Comment by zhongyang219** [comment]
问题已解决，请更新到V2.71版本
