### ISSUE TITLE
 打开文件位置并不会选中指定文件

### ISSUE THREAD

**Issue by sjhsbhqf** [zhongyang219/MusicPlayer2#723]
在foobar中我右键菜单中打开文件位置能够在资源管理器中选中指定文件，我能够立即看到这个音乐文件并对其重命名等操作

但是目前music player在打开文件位置后，只是打开了这个目录，而没有找到并选中这个文件。

这样导致我还需要增加一个查找步骤，非常麻烦

**Comment by lrisora** [comment]
应该不是这样，我这里是正常的，可能有什么特殊的问题
MusicPlayer2的做法等价于cmd执行
```
explorer /select,"文件绝对路径"
```
这是会选中文件的（至少在我的windows上），
如果cmd命令可以MusicPlayer2不行的话请提供一下有那些不同之处

**Comment by sjhsbhqf** [comment]
@lrisora 
非常感谢您的回复！

我刚刚发现cmd命令可以选中，但是musicplayer不行。

不知道您说的不同之处是指？

**Comment by lrisora** [comment]
需要看看，能录一个出问题的GIF或者mp4吗，尽量完整一些
是所有文件还是某些文件，全英文的路径+文件名试试
音乐文件的存储位置，是电脑本机吗，文件系统之类的
MusicPlayer2程序的位置
MusicPlayer2版本是哪个，换成Action的版本也是吗
Windows版本，有什么特殊的吗，是最近变成这样的还是一直是
Windows有附加能改变explorer的程序吗
Windows语言，有转区之类的吗
多半是Windows的问题，或者文件名编码之类的？我不确定

**Comment by sjhsbhqf** [comment]
@lrisora 非常感谢您的指引！

刚刚我测试了一个不带中文路径的音乐文件，发现没问题。

所以您看还需要其他信息吗？其他方面，没有什么特殊的。

**Comment by sjhsbhqf** [comment]
测试多了之后，再也难以复现了，很奇怪。
