### ISSUE TITLE
请求添加对本地vtt格式的歌词文件的支持

### ISSUE THREAD

**Issue by freecube0209** [zhongyang219/MusicPlayer2#728]
如题，请求对本地vtt格式的歌词文件的支持。

**Comment by lrisora** [comment]
这个可以有 ~终于有一个有文档的格式了~
方便发一些样本（最好有10+）吗，我有些不确定的地方，想看看实例
比如富文本支持肯定是是没有的，声音标签不知道要不要保留

**Comment by freecube0209** [comment]
> 这个可以有 ~终于有一个有文档的格式了~ 方便发一些样本（最好有10+）吗，我有些不确定的地方，想看看实例 比如富文本支持肯定是是没有的，声音标签不知道要不要保留

嘶，手头的vtt文件似乎都被我删了（因为用不了），我得去看看有没有别的资源

**Comment by lrisora** [comment]
主要是重叠时轴（如果有）的话如何处理（最好没有），
因为很明显MusicPlayer2不是视频播放器，不支持重叠时轴

以及这个格式如何处理翻译，是分不同文件还是有办法在一个文件内描述

**Comment by lrisora** [comment]
搓好了（可能有bug），不过还不清楚这个格式如何支持翻译，我也没有可以测试的文件
标签只支持了[时间戳标签](https://developer.mozilla.org/zh-CN/docs/Web/API/WebVTT_API#%E6%97%B6%E9%97%B4%E6%88%B3%E6%A0%87%E7%AD%BE)

https://github.com/zhongyang219/MusicPlayer2/actions/runs/9974107264

**Comment by freecube0209** [comment]
> 搓好了（可能有bug），不过还不清楚这个格式如何支持翻译，我也没有可以测试的文件 标签只支持了[时间戳标签](https://developer.mozilla.org/zh-CN/docs/Web/API/WebVTT_API#%E6%97%B6%E9%97%B4%E6%88%B3%E6%A0%87%E7%AD%BE)
> 
> https://github.com/zhongyang219/MusicPlayer2/actions/runs/9974107264

我去找了一个带vtt文件的音频文件进行测试，目前表现良好。再次感谢您的回应与开发！
