### ISSUE TITLE
播放设备变化问题

### ISSUE THREAD

**Issue by lz373877666** [zhongyang219/MusicPlayer2#73]
当音乐正播放时，插入/拔掉耳机，需要到播放设备中输出设备里重新调节，才能正常播放声音，希望可以在播放设备变化时，自动感应切换~

**Comment by zhongyang219** [comment]
这个似乎是播放内核的限制，暂时无法解决，如果遇到这个问题，在菜单栏中选择“工具”——“重新初始化播放器”可以解决这个问题。

**Comment by zhongyang219** [comment]
新版本中这个问题应该解决了，如果还有问题，欢迎再次反馈。
