### ISSUE TITLE
重载播放列表

### ISSUE THREAD

**Issue by wangshuai330508** [zhongyang219/MusicPlayer2#74]
问下，播放列表里设置的关联文件夹，如果文件夹里面新增了歌曲，我重载播放列表后，歌曲的数量不变，还是原来的，新添加的歌曲没有显示进去，希望能让它显示进来（暂时是这样的，如果是歌曲列表关联的文件夹里新增了歌曲，我是先清空列表，然后再设置一次关联文件夹，歌曲就更新了）

**Comment by zhongyang219** [comment]
播放器并没有“播放列表关联文件夹”的功能，在播放列表模式下，你可以将硬盘中任意位置的歌曲添加到播放列表，选择将文件夹添加到播放列表并不会将文件夹和播放列表关联，它仅仅只是将文件夹中的文件添加到播放列表而已，如果你想播放文件夹里的歌曲，请使用文件夹模式。在“媒体库”的“文件夹”标签下选择一个文件夹，或点击“打开新文件夹”按钮可以进入文件夹模式。在主菜单中选择“文件”——“打开文件夹”也将进入文件夹模式。关于播放列表的文件夹模式请参考[帮助页面](https://github.com/zhongyang219/MusicPlayer2/blob/master/Documents/Introduction.md)中“文件夹模式和播放列表模式”章节。
