### ISSUE TITLE
按功能分割源代码

### ISSUE THREAD

**Issue by cpupg** [zhongyang219/MusicPlayer2#744]
我是搞java和react的，代码会按功能放到不同目录，然后用`import`关键字导入，刚才看了下这个项目，musicplayer2下放着全部源代码切没有分割。没搞过cpp，不了解这个生态里的方案，想了解下

**Comment by zhongyang219** [comment]
因为Visual Studio创建的工程默认就是不分文件夹的，但是可以在“解决方案管理器”中创建筛选器，将文件按功能放在不同的筛选器下，筛选器被定义在`MusicPlayer2.vcxproj.filters`文件里。
![image](https://github.com/user-attachments/assets/0c7d7d72-feb2-447c-a23c-f28e8e8dd500)
