### ISSUE TITLE
软件内歌词显示 无法更换颜色

### ISSUE THREAD

**Issue by Lanmer** [zhongyang219/MusicPlayer2#748]
软件内歌词显示 无法更换颜色

**Comment by zhongyang219** [comment]
MusicPlayer2没有单独设置歌词颜色的功能，歌词的颜色是跟随主题颜色的，要更改主题颜色，可以到设置-外观设置-主题颜色中更改

**Comment by Lanmer** [comment]
> MusicPlayer2没有单独设置歌词颜色的功能，歌词的颜色是跟随主题颜色的，要更改主题颜色，可以到设置-外观设置-主题颜色中更改
非常感谢解答，只是因为在歌词设置中存在颜色选项，选择后未成功修改，遂来提交BUG
