### ISSUE TITLE
歌词两行的问题

### ISSUE THREAD

**Issue by huct08** [zhongyang219/MusicPlayer2#75]
首先先谢谢作者大大！
歌词两行的时候，第一行结束马上歌词就变了，能不能实现，第二行歌词结束的时候，第一行歌词才开始变，就和网易云音乐的两行歌词一样？

**Comment by zhongyang219** [comment]
我大概知道你的意思，但是我觉得并没有出现你说的问题。可能是我对你问题的理解有问题，你能再详细描述一下吗，最好能附上截图。

**Comment by SamToki** [comment]
@huct08 传统的卡拉OK两行歌词，就是一行结束后马上变掉的（变成第二行的下一行）。可以参见一些MTV歌词的样子。
