### ISSUE TITLE
媒体库选中歌曲中添加喜欢列表时，会重复加入，未做判断

### ISSUE THREAD

**Issue by Lanmer** [zhongyang219/MusicPlayer2#759]
媒体库选中歌曲中添加喜欢列表时，会重复加入，在目标歌单显示同一首歌的两个条目。在媒体库加入歌单时动作未做判断，应判断目标歌单是否存在此首歌，

**Comment by Lanmer** [comment]
可否考虑添加喜欢快捷键[https://github.com/zhongyang219/MusicPlayer2/issues/720](url)

**Comment by Lanmer** [comment]
可否考虑重构播放列表逻辑，加入临时播放歌单策略，点击某一歌单时会默认将该歌单全部加入临时播放列表，将播放和歌单解耦合，不随点击的歌单切换播放列表，目前在切换歌单时会切换播放列表，并暂停当前正在播放的歌曲，并切换到最近切换歌单的最后播放的歌曲中。解耦合后，方便用户在不同歌单寻找想听的歌曲并加入临时播放歌单。；例如听歌时会因为想听某一首且未在喜欢歌单中需要点击媒体库选择全部曲目 搜索某一首，并加入我的喜欢，加入后再在我的喜欢中选择下一首。解耦合后可以在任意歌单切换，不会更改现在的临时播放列表，且在每一个歌单或全部曲目列表，最近播放列表中加入下一首播放选项，方便用户选择最近想听的歌。

**Comment by lrisora** [comment]
虽然不完全一样，可以看看以下用法能否替代

大部分时候播放一个非常全的列表（现在可以用 媒体库的所有曲目）
这能够保证“下一曲播放”总是可用的
之后可以在媒体库窗口以任意方式检索&选择歌曲再“下一曲播放”
搭配下面这点也算是很自由了

> 目前在切换歌单时会切换播放列表，并暂停当前正在播放的歌曲

关于这一点不全是这样，勾选“播放设置->切换列表时继续播放”
能够在切入的播放列表存在当前播放曲目时 稍微卡一下的 维持播放状态
而不是上次播放的曲目
（我正打算修改成不用 稍微卡一下 就能切换列表）（工程量很大，需要时间）

下一曲播放几乎所有位置都有提供，没有明说的是其可用的条件是选择曲目必须全部已存在于当前播放列表
原因是MusicPlayer2从最初开始就没有使用播放队列的概念（类似你描述的行为）
也就是没有默认使用一个自动调整内容的列表作为播放实体（我很喜欢这一点，播放内容总是已知可控的）

**Comment by Lanmer** [comment]
> 虽然不完全一样，可以看看以下用法能否替代
> 
> 大部分时候播放一个非常全的列表（现在可以用 媒体库的所有曲目） 这能够保证“下一曲播放”总是可用的 之后可以在媒体库窗口以任意方式检索&选择歌曲再“下一曲播放” 搭配下面这点也算是很自由了
> 
> > 目前在切换歌单时会切换播放列表，并暂停当前正在播放的歌曲
> 
> 关于这一点不全是这样，勾选“播放设置->切换列表时继续播放” 能够在切入的播放列表存在当前播放曲目时 稍微卡一下的 维持播放状态 而不是上次播放的曲目 （我正打算修改成不用 稍微卡一下 就能切换列表）（工程量很大，需要时间）
> 
> 下一曲播放几乎所有位置都有提供，没有明说的是其可用的条件是选择曲目必须全部已存在于当前播放列表 原因是MusicPlayer2从最初开始就没有使用播放队列的概念（类似你描述的行为） 也就是没有默认使用一个自动调整内容的列表作为播放实体（我很喜欢这一点，播放内容总是已知可控的）

感谢回复“播放设置->切换列表时继续播放”解决了很大一部分问题，上方还有一个BUG和使用建议，小BUG可以用户通过后期去重或“导入歌单时自动去重”的功能解决，优先级并不高。从用户视角看，添加喜欢快捷键是呼声较高的，虽然不懂得代码，但是我从config.ini中找到show_hide_desktop_lyric这个关键词搜索项目中代码，似乎在定义快捷键处链接喜欢的函数可以轻松（或开发者视角很困难）解决

**Comment by Lanmer** [comment]
![图片](https://github.com/user-attachments/assets/cf785afc-9f18-4cb5-9784-c9a723bf1e0b)
和播放 暂停 声音加减不同，因显示桌面歌词是应用内功能，喜欢快捷键构造方式同显示桌面歌词大体差不多？ 感觉自己像讨厌的产品经理了hhhhhh

**Comment by zhongyang219** [comment]
> 可否考虑添加喜欢快捷键https://github.com/[/issues/720](https://github.com/zhongyang219/MusicPlayer2/issues/720)

这个功能已经加上了，请更新到V2.77版本：
![image](https://github.com/user-attachments/assets/b95cf89d-8449-43d7-ad11-2eaa795a0410)

**Comment by Lanmer** [comment]
2.76.版本复现步骤：在媒体库全部歌曲，选中一首我的喜欢存在的歌曲，加入我的喜欢歌单，我的喜欢歌单中会重复出现
不过更新过最新版本后是不存在这个问题了，通过提示框提示该播放列表已存在该歌曲，不过再这个提示框后，媒体库全部歌曲选择某一首歌时准备加入我的喜欢，我的喜欢选项却是灰的。我的更新方式是通过覆盖原文件夹，之前action版本中的2.76版本也是通过覆盖原文件夹进行更新，不知道是否是我的更新方式有问题
![图片](https://github.com/user-attachments/assets/8945937d-0000-486a-898c-d05768ffc6fc)

**Comment by Lanmer** [comment]
![图片](https://github.com/user-attachments/assets/7b54e366-d81d-465d-859c-8fe7734f7b67)
刚才截图没有截好，重启过软件后。想要尝试复现没能复现成功

**Comment by zhongyang219** [comment]
找到这个bug的复现方法了：
* 在“我喜欢的音乐”列表中随便选择一首歌曲右键添加到播放列表，此时由于这首曲目已经存在于“我喜欢的音乐”，因此是灰色的
* 在“所有曲目”中选择一首歌曲右键添加到播放列表，“我喜欢的音乐”仍然是灰色的，菜单的状态没有重置

**Comment by zhongyang219** [comment]
> 刚才截图没有截好，重启过软件后。想要尝试复现没能复现成功，现在是正常颜色，可以将歌曲加入我喜欢的歌曲歌单了 不过似乎上图可以可以看出BUG的存在，下一首播放的按钮是灰的，应该是控制下一首播放和加入播放列表》我的喜欢的某一个程序出现了问题

下一首播放目前是这样的，下一首播放的功能目前只对存在于当前播放列表中的曲目有效

**Comment by zhongyang219** [comment]
> 找到这个bug的复现方法了：
> 
> * 在“我喜欢的音乐”列表中随便选择一首歌曲右键添加到播放列表，此时由于这首曲目已经存在于“我喜欢的音乐”，因此是灰色的
> * 在“所有曲目”中选择一首歌曲右键添加到播放列表，“我喜欢的音乐”仍然是灰色的，菜单的状态没有重置

暂时可以通过如下方法解决：
* 在播放列表选中一首歌曲点击鼠标右键
* 再到所有曲目中点击鼠标右键，此时添加到播放列表下的菜单项就正常了

**Comment by Lanmer** [comment]
> > 找到这个bug的复现方法了：
> > 
> > * 在“我喜欢的音乐”列表中随便选择一首歌曲右键添加到播放列表，此时由于这首曲目已经存在于“我喜欢的音乐”，因此是灰色的
> > * 在“所有曲目”中选择一首歌曲右键添加到播放列表，“我喜欢的音乐”仍然是灰色的，菜单的状态没有重置
> 
> 暂时可以通过如下方法解决：
> 
>     * 在播放列表选中一首歌曲点击鼠标右键
> 
>     * 再到所有曲目中点击鼠标右键，此时添加到播放列表下的菜单项就正常了

重启解决99%问题哈哈哈哈哈哈

**Comment by Lanmer** [comment]
留下issue作为todolist还是？ 刚想关闭突觉不对

**Comment by zhongyang219** [comment]
> 留下issue作为todolist还是？ 刚想关闭突觉不对

先留着，这确实是个bug，等我解决再关
