### ISSUE TITLE
反馈各小问题，关于打开网络共享文件夹中的音乐

### ISSUE THREAD

**Issue by Zheny918** [zhongyang219/MusicPlayer2#764]
我的所有音乐都在网络文件夹上，网络也不慢，但是没次切歌或者打开的时候，都需要等1分钟左右才可以正常使用。相当于听一首歌要等一分钟。

**Comment by lrisora** [comment]
有cue吗
另外不要用文件夹模式，改用播放列表模式，应该能好不少
如果没有，这是个什么网络文件夹，怎样使用的

**Comment by Zheny918** [comment]
没有错误提示，也没有用文件夹模式。我所有音乐文件都是存在一台NAS上的，使用共享路径访问，比如\\192.168.10.10\音乐，使用媒体库将这个文件夹里的所有音乐加入媒体库然后播放。没有其他操作。但是每次打开和切换因为都很卡，一直转圈

**Comment by lrisora** [comment]
点下一曲也卡吗
在资源管理器映射网络驱动器，让文件路径有一个盘符试试
具体是什么协议，

你的音乐文件能在资源管理器读到"修改时间"这个属性吗

**Comment by Zheny918** [comment]
点下一曲也卡；使用的是Windows SMB 协议，就是网络共享文件夹。在音乐文件夹可以看到修改时间属性
![image](https://github.com/user-attachments/assets/5036ab7c-21b4-42e1-8154-e6ad324fcee0)

**Comment by lrisora** [comment]
你的NAS是机械硬盘吗
关掉”歌词设置->歌词模糊匹配“
设置一个”歌词文件夹“（最好在固态硬盘，用不了多少空间），把所有lrc放到里面
会好点吗

**Comment by Zheny918** [comment]
没试过，我试试不显示歌词是不是好点

**Comment by lrisora** [comment]
不显示歌词没意义，一定要关掉”歌词设置->歌词模糊匹配“
应该是你一个文件夹下太多歌词导致的

每首音乐第二次播放应该就正常了

**Comment by Zheny918** [comment]
恩，关闭了歌词模糊匹配确实好很多了。没有设置一个”歌词文件夹“的情况下

**Comment by Zheny918** [comment]
已解决，感谢
