### ISSUE TITLE
fps 5是正常现象吗？掉帧问题

### ISSUE THREAD

**Issue by specked2527** [zhongyang219/MusicPlayer2#769]
https://github.com/zhongyang219/MusicPlayer2/issues/237#issuecomment-903524392
>设置里界面刷新间隔调到10ms，关掉用GDI+绘制封面
>在选项设置-外观设置中去掉显示背景可以提高帧率，但是界面看起来会变丑
>专辑封面和背景都关闭的话可以大幅提高帧率。

关闭
- 显示背景
- GDI+绘制封面，设置里界面刷新间隔调到10ms

fps为24，但在有歌词时 fps为15
![20240822203733](https://github.com/user-attachments/assets/deadf880-b859-4a74-abcc-25c3ad74219f)

相反，
打开
- 显示背景
- GDI+绘制封面

fps为5
![20240822203246](https://github.com/user-attachments/assets/cfab9fca-a7a6-4302-93d2-17a2dfd917bb)

**Comment by zhongyang219** [comment]
不要最大化，把窗口缩小一点，会流畅很多

**Comment by zhongyang219** [comment]
还有，不要勾选“专辑封面使用GDI+绘制”也能提高帧数，其实使用GDI+绘制大多数情况下差别不太，如果帧数较低不建议勾选。

**Comment by zhongyang219** [comment]
还有，不要使用圆角风格，绘制圆角矩形会占用更多CPU资源，导致帧数降低
