### ISSUE TITLE
WIN11系统桌面歌词显示翻译时，会出现中文显示不全，不知道是不是缩放问题 

### ISSUE THREAD

**Issue by Lanmer** [zhongyang219/MusicPlayer2#774]
![图片](https://github.com/user-attachments/assets/b7ad164b-175c-44ca-b6ae-90bf200789b4)
翻译时存在问题，两行中文没问题
![图片](https://github.com/user-attachments/assets/9a28c26d-ef50-4f18-833e-b38e2a1e1623)
![图片](https://github.com/user-attachments/assets/4baa9a61-bc0c-45c6-9545-1dd65653bc09)

**Comment by lrisora** [comment]
关掉”歌词背景穿透“，在窗口范围显示以后把歌词窗口稍微调大一点，
这个窗口大小装不下这个字号的歌词

歌词双行和歌词+翻译 两种状态使用的行距不同

**Comment by Lanmer** [comment]
已解决
