### ISSUE TITLE
播放快结束的时候有的歌会卡住

### ISSUE THREAD

**Issue by DSmegumi** [zhongyang219/MusicPlayer2#78]
暂停再播放会后退一秒但还会在那卡住，点后面的进度也还会弹回到卡住的位置。设置里的遇到错误停止播放，这个选项并没有打开。

**Comment by zhongyang219** [comment]
你好，可以提供一个有问题的音频文件吗？以帮助我调查问题所在。

**Comment by DSmegumi** [comment]
https://share.weiyun.com/irzPcPk7

**Comment by eail-zh** [comment]
我也碰到过这个问题，不过我把出了问题的音频文件用其它播放器播放的时候同样出了问题，所以应当是音频文件的问题
