### ISSUE TITLE
闪屏

### ISSUE THREAD

**Issue by yezongjun** [zhongyang219/MusicPlayer2#79]
最新版win10 当鼠标在搜索框（已经修改为MusicPlayer）边缘来回滑动时，会闪现出：本来的搜索框画面=”在这里输入你要搜索的内容“  有录制视频：https://jun7033.lanzous.com/iOLrIeyjpxa
喜欢这个工具的我有一个小小的建议：
一般使用 MusicPlayer这种美化工具的人，基本上也会把任务栏设置透明，但是这个播放界面无法调透明。能不能辛苦您看一 
       下，有空稍微改一下
当没有歌词的时候能不能什么也不显示，或者显示自定义文字

**Comment by zhongyang219** [comment]
你好，你说这个问题是正常的，目前只能做到这样，建议没事不要鼠标在搜索框边缘来回移动呢😂
你说的播放界面无法调透明是什么意思，可以详细描述一下吗？
当没有歌词的时候是显示播放曲目名称的，为什么要它什么也不显示呢？另外自定义显示文字我觉得并没有意义，因为我觉得一个播放没有必要要提供自定义搜索框文字的功能。

**Comment by zhongyang219** [comment]
你是想说希望播放器的界面也做成透明的吗？很抱歉这个我目前还做不到呢。如果要做到这一点，可能要使用新的界面技术，整个代码框架可能需要大幅调整。这个软件只是我利用业余时间编写的个人软件，在某些方面肯定比不上企业级别的软件，因此希望不要要求太高。
