### ISSUE TITLE
有一个flac文件的时长无法获取

### ISSUE THREAD

**Issue by Leoongithub** [zhongyang219/MusicPlayer2#794]
文件可以正常播放，但由于无法获取时长，导致进度条失效。
附件为ffmpeg切的前10s（`ffmpeg.exe -i input.flac -t 10 sample.flac`），同样无法获取时长。
[sample.zip](https://github.com/user-attachments/files/17178591/sample.zip)

**Comment by lrisora** [comment]
![圖片](https://github.com/user-attachments/assets/841e939c-0497-447d-9a68-5fe81f74ab65)
文件没有问题，一切正常，BASS和FFMPEG内核都是
无法获取时长又能够播放是不可能的，可能是显示方面的问题？
右键“重新载入播放列表”试试，这会重新获取文件元数据
不行的话我想看看具体是什么表现

**Comment by Leoongithub** [comment]
重新载入播放列表可以正常获取时长，并且再次添加同样的文件也正常了（之前即使从播放列表中删除再添加还是不行），可能是第一次读取文件metadata失败并缓存了这一结果？总之目前问题解决了。
