### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by smaragdus** [zhongyang219/MusicPlayer2#8]
MusicPlayer2 seems to be a very nice audio player- small, portable, many audio formats supported. However I cannot test and use it because it is available (as of version [2.62](https://github.com/zhongyang219/MusicPlayer2/releases/tag/V2.62)) only in Chinese. Any chance to translate the program into English?

**Comment by zhongyang219** [comment]
Thank you for your support, I do have the plan to add the English language support. But it would be a large project, it may take some time. English translation will be added in the next version, please focus on the update message of the program.

**Comment by zhongyang219** [comment]
Hello, the new version (V2.63) of MusicPlayer2 has been released. I have add the English language support, welcome to download.

**Comment by smaragdus** [comment]
@zhongyang219 

Hello,

Thank you very much for the English translation of MusicPlayer2.

I finally found some time to write a short review about the program at The Portable Freeware Forum- you can find it [here](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24533). If I have missed something essential please tell me.

I have a question- I like more the old GUI (version [2.63](https://github.com/zhongyang219/MusicPlayer2/releases/tag/V2.63)) with controls on top- would it be possible that you release it as an optional skin?

**Comment by smaragdus** [comment]
@zhongyang219 

I have several suggestions- shall I post them here or it would be better to open new issues?

**Comment by zhongyang219** [comment]
Hello,
You said you like more the old GUI with buttons on the top, but I'm sorry, I have deleted the code and It is hard to add an option to change to the old GUI. And It will looks weird with controls both on the top and bottom.
You can open new issues if you have other question or suggestions with MusicPlayer2.
