### ISSUE TITLE
[Upgrade] 推荐引入这个全网下载器

### ISSUE THREAD

**Issue by xx-zhang** [zhongyang219/MusicPlayer2#80]
参考 https://www.52pojie.cn/thread-960393-1-1.html

可以添加在线的媒体库

**Comment by zhongyang219** [comment]
暂时没有做歌曲下载的计划，因为这可能引起版权纠纷。

**Comment by xx-zhang** [comment]
> 暂时没有做歌曲下载的计划，因为这可能引起版权纠纷。

有道理，谢谢。
