### ISSUE TITLE
媒体库存在大量重复文件

### ISSUE THREAD

**Issue by Sh1kaCodAyo** [zhongyang219/MusicPlayer2#813]
如图，媒体库中存在大量重复文件，这些文件只在路径对应的盘符大小写有区别
切到艺术家/唱片集等tab也有类似情况
但并非所有文件都有重复现象

![QQ截图20241211161903](https://github.com/user-attachments/assets/411e6009-ed90-45d3-921d-dcc30defa003)
![QQ截图20241211163228](https://github.com/user-attachments/assets/0ee871ea-87af-4c34-9979-d068945ced50)

**Comment by lrisora** [comment]
我不知道这些小写盘符的条目是如何加入的，
暂时只想到打开过其他播放列表且这个播放列表使用了这种小写盘符这种可能性

清除方法很明确，先将所有要保留的条目的目录添加到 选项设置->媒体库标签页->媒体库目录列表
**之后点“确定”或“应用”，将设置应用**
一定要先应用，再打开这里，使用“清理媒体库”，清理范围选“不在媒体库目录中的文件”即可
由于一些bug，使用清理媒体库之后有些特定操作会闪退（多半不会触发），可以重开一下程序

例如你可以添加 E:\Users\Ftwrjh\Music 到媒体库目录以保留所有路径以此开头的条目
我不了解你的文件分布，一定要按需添加你所需要的所有目录
~或者备份 song_data.dat 文件~

**Comment by Sh1kaCodAyo** [comment]
> 我不知道这些小写盘符的条目是如何加入的， 暂时只想到打开过其他播放列表且这个播放列表使用了这种小写盘符这种可能性
> 
> 清除方法很明确，先将所有要保留的条目的目录添加到 选项设置->媒体库标签页->媒体库目录列表 **之后点“确定”或“应用”，将设置应用** 一定要先应用，再打开这里，使用“清理媒体库”，清理范围选“不在媒体库目录中的文件”即可 由于一些bug，使用清理媒体库之后有些特定操作会闪退（多半不会触发），可以重开一下程序
> 
> 例如你可以添加 E:\Users\Ftwrjh\Music 到媒体库目录以保留所有路径以此开头的条目 我不了解你的文件分布，一定要按需添加你所需要的所有目录 ~或者备份 song_data.dat 文件~

感谢！已解决。我的确是打开过之前自己在别处创建的m3u播放列表，估计应该就是从这些列表里来的。
