### ISSUE TITLE
最新commit的代码将部分歌曲标签信息中的英文字识别为小写，以及对封面加载方式的建议

### ISSUE THREAD

**Issue by xkww3n** [zhongyang219/MusicPlayer2#82]
我clone了当前的整个代码库（commit hash:`a952af1`）并在VS 2019，Windows 10 SDK `10.0.18362.0`版本使用`Release x64`配置文件编译，在使用自编译的主程序刷新播放列表后发现部分歌曲标签的英文全部变成了小写：（红色框起的部分为错误信息，绿色框起的部分为正常信息）

![image](https://user-images.githubusercontent.com/30206355/88881184-5b153a80-d261-11ea-87e6-b165208a365f.png)

部分出现问题的歌曲文件：https://cowtransfer.com/s/a8e823046a454a
（出问题的全是FLAC格式的文件）
望修复，感谢大佬~
另外，目前的代码对于高分辨率封面的处理方式可能会导致切歌或者启动程序时卡顿。关于这点我有个建议：添加歌曲读取信息时先创建所有封面的低分辨率版本（如512px*512px）并保存在某个位置，切换歌曲时先播放音频并显示低分辨率封面，再加载音频内嵌的高分辨率版本封面。不知这样是否可行？

**Comment by zhongyang219** [comment]
非常感谢你的反馈，目前正在调查这个问题

**Comment by zhongyang219** [comment]
你好，这个问题已经解决了，你可以拉取最新的代码再编译一下。关于高分辨率专辑封面导致卡顿的问题，你的建议很好，我会想办法解决这个问题。
