### ISSUE TITLE
贡献两个磁贴

### ISSUE THREAD

**Issue by 2450038651** [zhongyang219/MusicPlayer2#83]
![椭圆 1](https://user-images.githubusercontent.com/67503875/88971158-1b446680-d2e6-11ea-853e-479d89333a0f.png)
![musicplayer2](https://user-images.githubusercontent.com/67503875/88971159-1c759380-d2e6-11ea-9c11-cae056f322cb.png)
很喜欢作者大大的这个播放器 兴起自己做了俩个图标  一个绿背景 一个透明背景方便用户diy
效果如图
![20200731042839](https://user-images.githubusercontent.com/67503875/88971444-7bd3a380-d2e6-11ea-8ff4-b812646b049f.png)

**Comment by zhongyang219** [comment]
非常感谢，其实我本来已经做好了一个磁贴图片，如图所示：
![image](https://user-images.githubusercontent.com/30562462/89098377-8c386b00-d419-11ea-9a7d-a4dd9430eb08.png)
不过感觉还是你的好看一些。

**Comment by soralife** [comment]
![批注 2020-08-01 194933](https://user-images.githubusercontent.com/43085437/89102145-e85eb780-d438-11ea-8d3f-1b12a6d3fb70.png)

![批注 2020-08-01 194933](https://user-images.githubusercontent.com/43085437/89102145-e85eb780-d438-11ea-8d3f-1b12a6d3fb70.png)

最近微软win10预览版更新了全屏幕开始菜单，把原来的主题色改成半透明，效果还是很不错的。
我平时是开启透明效果用暗色的，但是透明磁贴大概还需要准备一个黑色的来适应背景，不然就会像网易云音乐UWP版一样对比度太小。

**Comment by zhongyang219** [comment]
突然看到你也玩osu!，告诉你MusicPlayer2的一个隐藏功能，它支持播放osu!中的歌曲，选择“文件”>“打开文件夹”，然后选择osu!目录下的“Songs”文件夹，它就会自动扫描该目录下的音乐，并能从*.osu文件读取歌曲信息。

**Comment by soralife** [comment]
这个功能对osu!的支持基本上完美了没有问题，只是对歌词仍然使用原本的歌词方案有些奇怪。
触发条件：设置默认将歌词保存在歌词文件夹
因为OSU的歌绝大部分文件名是`Audio.mp3`，导致每一首匹配后试图保存的歌词都叫`Audio.lrc`之后许多歌抢一个歌词的位置。下一首发现上一首的歌词捡起来就用也不管是不是自己的，只能手动删除。
已经顺利从`*.osu`解析出歌曲名了，把默认歌词改成 `歌手-歌曲名.lrc` 应该就解决了。

![批注 2020-08-01 222735](https://user-images.githubusercontent.com/43085437/89104145-a427e300-d449-11ea-81e5-167a7d08143b.png)

**Comment by zhongyang219** [comment]
@soralife 确实有这个问题，下个版本会修正这个问题，目前建议在下载osu的歌词时选择将歌词保存到歌曲所在目录。

**Comment by Landius** [comment]
@soralife 第一张背景很好看，能指个路嘛😁

**Comment by soralife** [comment]
原始出处[https://yande.re/post/show/507843](https://yande.re/post/show/507843)不过我是从这里下载的->发布地址 [https://share.dmhy.org/topics/view/511898_LoliHouse_LoliHouse_2nd_Anniversary_Gift_Part_1_Wallpaper_Part.html](https://share.dmhy.org/topics/view/511898_LoliHouse_LoliHouse_2nd_Anniversary_Gift_Part_1_Wallpaper_Part.html) ~~还有一个三周年版本不过太大我的电脑装不下~~
由于使用 ` Waifu2X` 处理壁纸比原图更加清晰
![yande re 507843](https://user-images.githubusercontent.com/43085437/89529637-a611ed80-d81f-11ea-95a8-1529e5e951e1.png)
歪楼更加严重了🤔

magnet:?xt=urn:btih:YFCFAWUWMPWSVJZ457756GHCKTF5P4FV&dn=&tr=http%3A%2F%2F104.238.198.186%3A8000%2Fannounce&tr=udp%3A%2F%2F104.238.198.186%3A8000%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker4.itzmx.com%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.prq.to%2Fannounce&tr=http%3A%2F%2Fopen.acgtracker.com%3A1096%2Fannounce&tr=https%3A%2F%2Ft-115.rhcloud.com%2Fonly_for_ylbud&tr=http%3A%2F%2Fbtfile.sdo.com%3A6961%2Fannounce&tr=http%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftr.bangumi.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ft.nyaatracker.com%2Fannounce&tr=http%3A%2F%2Fopen.nyaatorrents.info%3A6544%2Fannounce&tr=http%3A%2F%2Ft2.popgo.org%3A7456%2Fannonce&tr=http%3A%2F%2Fshare.camoe.cn%3A8080%2Fannounce&tr=http%3A%2F%2Fopentracker.acgnx.se%2Fannounce

**Comment by zhongyang219** [comment]
@soralife 老哥，你提供的地址里的壁纸包真是太赞了👍

**Comment by zhongyang219** [comment]
我今天重新设计了一下应用程序的图标，如图所示：
![2020-08-09 (3)](https://user-images.githubusercontent.com/30562462/89733508-88938c80-da88-11ea-844b-c88135c55b71.png)
然后开始屏幕磁贴也修改了一下：
![image](https://user-images.githubusercontent.com/30562462/89733550-c0023900-da88-11ea-9826-7fe5fe2973f7.png)

**Comment by soralife** [comment]
基于新图标改
![MusicPlayer2 150x150Logo](https://user-images.githubusercontent.com/43085437/89803616-a682ef00-db65-11ea-8a14-30d545a500de.png)
就在这里⬆边缘没有加黑色阴影
只改了白色版本，windows会自动适应黑白
个人更习惯图标居中(在不与文字重叠的情况下)

![屏幕截图 2020-08-10 222325](https://user-images.githubusercontent.com/43085437/89803730-cfa37f80-db65-11ea-9666-4cf91dc62971.png)

![屏幕截图 2020-08-10 222404](https://user-images.githubusercontent.com/43085437/89803803-e21db900-db65-11ea-9546-58755ebffb60.png)
