### ISSUE TITLE
长时间熄屏随机播放后界面出现问题+csv导出不符合标准

### ISSUE THREAD

**Issue by soralife** [zhongyang219/MusicPlayer2#84]
[紫咲ほたる - Re_TrymenT - MusicPlayer2 2020-08-06 08-23-00.zip](https://github.com/zhongyang219/MusicPlayer2/files/5032051/-.Re_TrymenT.-.MusicPlayer2.2020-08-06.08-23-00.zip)

4月15日的Releases版本没有此问题，昨天电脑腾出些空间，把卸载已久的VS装回来。用VS2019编译了“鼠标提示更新”版本源码，试用几个小时感觉没问题就覆盖了原本的exe。昨晚用蓝牙耳机在播放列表随机播放，之后合上笔记本屏幕(合上屏幕设置为不采取任何操作)此时正常播放，放了一晚上今早醒来的时候播放仍然正常。此时我没有确认合上的笔记本屏幕内容直接关闭了蓝牙耳机，之后打开笔记本屏幕看到了上视频内容。虽然视频只录了10秒但是实际上是无限持续，切过的歌曲明显超过了一晚所能播放的量。由于蓝牙耳机的关系没能确定此时播放是否正常，也没确定是蓝牙断开导致还是重新点亮屏幕导致。
不知道最近三次更新修复了这个问题没有，更多信息有待复现可能需要很长时间测试。

播放列表卡顿问题已经修复。
cue编码已兼容UTF-8 with BOM，UTF-16LE with BOM，ANSI(简中默认是GBK)已经比fb2000多一种。

关于“播放时间统计”~~虽然可能没什么人用~~
导出csv的函数有问题，不能正确处理字段中含有半角逗号，以下复制自 [wiki](https://zh.wikipedia.org/wiki/%E9%80%97%E5%8F%B7%E5%88%86%E9%9A%94%E5%80%BC)
> **进行中的标准化**
> 
> “CSV”格式中大量变体的存在说明并没有一个“CSV标准”。[5][6]在常见用法中，几乎任何定界符分隔的文本数据都可以被统称为“CSV”文件。不同的CSV格式可能不会兼容。
> 不过，RFC 4180是一个将CSV正式化的努力。它定义了互联网媒体类型“text/csv”，并且采用它的规则的CSV文件将会具有广泛的可移植性。它有如下要求：
>    -  以（CR/LF）字符结束的DOS风格的行（最后一行可选）。
>    - 一条可选的表头记录（没有可靠的方式来检测它是否存在，所以导入时必须谨慎）。
>    - 每条记录“应当”包含同样数量的逗号分隔字段。
>    - 任何字段都可以被包裹（用双引号）。
>    - 包含换行符、双引号和/或逗号的字段应当被包裹。（否则，文件很可能不能被正确处理）。
>    - 字段中的一个（双）引号字符必须被表示为两个（双）引号字符。
> 这个格式很简单，可以被大部分声称可以读取CSV文件的程序处理。例外是（a）程序可以不支持在被包裹的字段中换行，（b）程序可以将可选的表头当作数据，或者将第一个数据行当作可选的表头。 

![批注 2020-08-03 105934](https://user-images.githubusercontent.com/43085437/89485233-ebf49480-d7d2-11ea-95f4-8781c7706caa.png)

本地有41首含有半角逗号，有20首含有半角双引号，暂时未见同时含有这两个符号的歌曲

**Comment by zhongyang219** [comment]
我昨天提交的代码修正了一处注册表句柄泄漏的问题，你的问题很可能与此有关，请取一下最新代码重新编译一下再试试。

**Comment by soralife** [comment]
今早问题仍然在相同条件下复现，推测是某次UI代码更新引起。
问题发生时cpu使用与平时一致，内存使用12.6M左右，磁盘较高有1.4M左右平时播放时稳定0.1M

**Comment by soralife** [comment]
刚刚又发生一次，看滑动条表现状态是不断下一曲，1400+的播放列表轮一圈都不停下来。
还差确认合上笔记本盖子播放与蓝牙连接断开哪个是或者同时发生才是触发条件。
这个bug不会在正常使用时发生。大概

**Comment by zhongyang219** [comment]
@soralife 你看一下你的“选项设置”>“播放设置”中的“出现错误时停止播放”有没有勾上，如果没有，勾上再试试看。

**Comment by zhongyang219** [comment]
@soralife 根据你的描述，有可能跟我之前提交的在CPlayer::SongIsOver()添加的一段代码有关，我现在注释掉了那段代码，你再试试看。

**Comment by soralife** [comment]
出现错误时停止播放勾上了
明确是蓝牙断开导致的，正常播放时关掉蓝牙耳机立刻出现
不断下一曲的过程是可以使用 播放暂停键控制的
重新初始化播放器就好了
修改后代码确定不能复现那个视频内容。
播放器会停下来但是没有触发UI更新(比如正在播放不会变成已暂停或播放出错)，和以前一致
