### ISSUE TITLE
打开应用后播放的第一首歌问题

### ISSUE THREAD

**Issue by nalabla** [zhongyang219/MusicPlayer2#86]
打开应用后，播放的第一首歌出现问题：只有专辑图片与音频文件符合，1显示的歌曲名以及歌手名是其他歌曲的，2此时歌词无法显示，或者显示的是其他歌曲的歌词。不影响使用，但是能解决更好😘。（另，无论是否勾选“程序启动时自动播放”，都会自动播放）

**Comment by zhongyang219** [comment]
这个问题我也曾经遇到过，我记得我应该已经解决了。我临时编译了一个最新版本，你试试看问题是否解决：
[MusicPlayer2_2.69.1_x64_beta.zip](https://github.com/zhongyang219/MusicPlayer2/files/5047608/MusicPlayer2_2.69.1_x64_beta.zip)

**Comment by nalabla** [comment]
这个版本，播放第一首歌时显示的问题已经解决了。除此之外指定图片为专辑封面也可以使用，使用专辑封面作为背景时也不会影响看歌词。👍（不过快捷键还是需要每次重新设置，确定每个快捷键都设置了）
