### ISSUE TITLE
通过MP3TAG写入的歌曲信息无法被读取

### ISSUE THREAD

**Issue by ALICEOFALICE** [zhongyang219/MusicPlayer2#87]
![image](https://user-images.githubusercontent.com/41146748/89705678-d4afd580-d991-11ea-9dd8-5c6ae1d95b1f.png)
![image](https://user-images.githubusercontent.com/41146748/89705679-d8dbf300-d991-11ea-9bf8-4b9f495722d4.png)
![image](https://user-images.githubusercontent.com/41146748/89705697-e5f8e200-d991-11ea-9fcb-1dad199608f8.png)

通过MP3TAG写入的歌曲信息无法被读取

**Comment by soralife** [comment]
这个问题与MP3TAG无关，是播放器暂不支持识别wav格式的歌曲信息（元数据）
目前临时解决可以选择将wav转码为支持的格式
#72

**Comment by soralife** [comment]
@ALICEOFALICE 作者 @zhongyang219 大佬已经在新版源码里解决了这个问题(至少我测试没有发现问题)
不过当前支持到ID3v2.3，请写入ID3v2.3版本的元数据。
以下引自 [ID3 wiki](https://zh.wikipedia.org/wiki/ID3)

>在最新版ID3v2.4，总共宣告了83种数据帧架[8]，而用户也可以自定义属于自己的数据帧架。标准的数据帧架有量测音乐速度、著作权、歌词、任意文字和URL数据等等。ID3v2总共有三种版本：
>**ID3v2.2**
>    v2.2是ID3v2的第一个公开版本。他使用3个字符作为数据帧架标识符，而非4个（举例来说，其使用TT2而非T1T2）。v2.3和v2.4中大多数的数据帧架都在v2.2中有着相似的框架。这个标准已经被认为过时[9]。
>**ID3v2.3**
>    v2.3将数据帧架标识符扩展到4个字符，并且加入了一些新的数据帧架。一个框架可以包含复数值，由空字符分隔。这是目前最广泛使用的ID3v2标签[10]。
>**ID3v2.4**
>    v2.4出版于2000年11月1日，至今仍是最新的版本。其允许文字数据以早期常用（因为它比起UTF-16而言有许多显著的优点）但非标准的标签编码UTF-8写入。另外一项新功能是可以选择是否在文件末端、其他标签前面加入标签，就像ID3v1那样[11]。
>    没有任何版本的Windows资源管理器和Windows Media Player──甚至是最新的Windows 10和WMP 12──都无法正确的解读ID3v2.4标签，不过依然能解读v2.3或是更早的版本[12][13]。

**Comment by ALICEOFALICE** [comment]
好的，已经了解，非常感谢
