### ISSUE TITLE
当窗口处于后台且未播放时不刷新界面的问题

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#88]
这个功能我也想反馈加上，毕竟不播放时还占用cpu不合适。
目前的问题是当窗口处于后台时通过多媒体键/全局快捷键进行暂停操作时UI有大概率不会更新。
也就是“正在播放”字样有可能不会变成“已暂停”，同时播放暂停键图标可能不会更新，这两项不一定同时出现。
反过来暂停变成播放时一直是正常的。
或许可以延时一会再停止刷新
我遇到过的最低FPS是3，延时500ms应该够了

**Comment by zhongyang219** [comment]
你好，确实有这个问题，这个问题应该是我将绘图的处理移到后台线程中导致的，应该在执行“播放”、“暂停”、“停止”操作时强制刷新一次界面。

**Comment by zhongyang219** [comment]
问题已解决。

**Comment by soralife** [comment]
问题还是没有改变，是在窗口没有焦点时出现，如图，我的直观感觉是没能完成一次刷新
![图片](https://user-images.githubusercontent.com/43085437/89905639-012b5200-dc1d-11ea-9808-7a9d90416a13.png)

**Comment by zhongyang219** [comment]
我这边测试下来是没问题的，你拿最新的版本再编译一下试试

**Comment by soralife** [comment]
程序初始默认`config.ini`确实不会出现这个问题了(更新：偶尔还会)，但是我一直用的`config.ini`还是有，待我再研究研究是哪个选项。
更新：我的理解有问题了，这个问题不应这样描述，也不是很严重的问题
因为在出现问题时只要点击一下窗口(或做出任何会触发窗口刷新的操作)错误的旧字样就会更新为正常的已暂停。
多次实验发现规律(猜的)：暂停->播放->暂停，其中播放时长为尽可能精准的1s(或许是整数秒)时最有可能复现。

另一个问题和这个很像如下图
在暂停时进行诸如 重启资源管理器 右键桌面->查看->显示桌面图标 等等操作时出现。
同样只要触发窗口刷新就会恢复。

![屏幕截图 2020-08-11 221744](https://user-images.githubusercontent.com/43085437/89971445-d6c5ad00-dc8d-11ea-9d17-a4f6396148af.png)

**Comment by zhongyang219** [comment]
你说的问题是指当窗口未激活时，通过全局快捷执行“播放/暂时”时，界面上的播放状态显示没有刷新是吧，这个问题我这边测试下来确实已经好了呀。
另外，你上面提到的资源管理器重启时界面不刷新的问题刚刚已经解决了。

**Comment by zhongyang219** [comment]
你拿我编译的版本再试试
[MusicPlayer2_V2.69.1_beta_20200812.zip](https://github.com/zhongyang219/MusicPlayer2/files/5060516/MusicPlayer2_V2.69.1_beta_20200812.zip)

**Comment by soralife** [comment]
没有变化，就是在窗口未激活时执行暂停出现。我现在已经能够几乎准确把握节奏复现这个问题了(一开始不熟悉时差不多100次能按到一次)。明确与时间有关系。
不排除是我用的Windows预览版本身的问题

**Comment by soralife** [comment]
不是完全没有刷新，是刷新未完成，按下暂停之后两道竖杠的暂停键已经变成三角形的播放键了，但是此时正在播放字样没有变成已暂停。

**Comment by zhongyang219** [comment]
我试了很多次，终于复现了这个问题。我注意到图标是正常的，只有文字不正确。目前找不出问题出在哪里。

**Comment by soralife** [comment]
一般伴随着FPS值短时间极高大于60，以我的电脑是绝对达不到的，前台播放时FPS不会飘得如此离谱
