### ISSUE TITLE
一些不影响使用的小问题&建议

### ISSUE THREAD

**Issue by lrisora** [zhongyang219/MusicPlayer2#89]
以下问题&建议不急需，不绝对必要，只是提供一个想法，如果作者大佬也觉得这个可以有的话还望更新添加。

**问题**
 - 播放列表模式下将单选或多选文件其中不含有任何音频文件拖入主窗口处理逻辑问题。
 应当先识别没有任何有效文件的情况特殊处理报错，现在会出现播放失败+所有项目完全添加失败的报错信息，还会使当前播放歌曲不显示封面。例如拖入一个`jpg/txt`文件之后的反应。不过对于复数文件中含有部分无效文件是能够正常跳过的。
 - 执行清空播放列表不会自动关闭对当前播放歌曲的占用(无法在资源管理器内重命名/删除)，更换播放列表之后才会解除占用。一首一首或多选之后从播放列表删除之后是会解除占用的。
 - 在选项设置的媒体库标签页内部 当鼠标位于 `group box` 内部时可以使用笔记本触控板的双指手势正常滚动界面，当鼠标位于其外部时触控板的双指滚动手势失效。选项设置的其他标签页均不存在此问题，若使用鼠标滚轮滚动则媒体库标签页也是正常的。
 更新复现条件：
   1. 当选项设置窗口打开默认标签页是媒体库时不会出现（此时换到其他标签页再换回来即可出现）
   2. 出现时对媒体库标签页内部选项复选框做出改变(点击一下不用保存)滚动即可恢复正常(此时换到其他标签页再换回来又会出现)
   3. 一定要用触控板手势才会发生，鼠标滚轮一直是正常的
 可能与之相关：当通过点击使媒体库标签页->播放列表->播放列表显示方式拥有焦点时再将光标移至/点击媒体库标签页内部`group box`外区域时不会使播放列表显示方式下拉列表失焦，此时使用触控板双指滚动会改变选项。

**建议**
 - 为*重新初始化播放器*安排一个一只手能按到的快捷键，作为蓝牙耳机用户这个按钮使用频率太高，对于不用常用鼠标的我来说有些难点到。(或者实现那个菜单栏隐藏时按一下alt键临时显示菜单栏也可以，不必显示横条那个，只要实现按alt像点击那个三道杠的菜单图标一样就好)
 - 打开下载歌词对话框后自动进行一次搜索。
 - 播放列表排序方式添加*按文件修改时间排序*在资源管理器里属性叫修改日期(不是创建日期)在已经按其他方式排序后希望找到最近下载的文件时十分有用。(可以给文件夹模式也加上)
 - 播放模式为随机播放时将通过手动点击播放的歌曲压入历史播放，使其在按上一曲时会出现，下一曲时仍然进行随机播放。
 - 桌面歌词启用*歌词背景穿透*之后拖动歌词时窗口边界不可见，希望在拖动时鼠标按下期间暂时取消*歌词背景穿透*以显示那个半透明的白框来表示桌面歌词窗口整体位置大小，以解决想移动窗口却不知窗口大小的问题。
 - 托盘图标左键单击改为当窗口处于后台时设为前台，处于前台时根据设置(新增设置最小化时是否最小化到通知区,此设置对主窗口最小化按钮同样生效)选择最小化/最小化到通知区。
 - 增加对wav文件的RIFF元数据支持

**Comment by zhongyang219** [comment]
问题1、2已经解决了。
重新初始化播放器功能快捷键已经加上了，快捷键为Ctrl+Q。其实之前的版本中这个命令是有快捷键的，后来觉得这个功能应该不怎么常用就删掉了。我有空的话再研究一下能不能实现自动执行重新初始化的操作吧。
另外关于随机播放回溯的功能已经支持了啊，你难道没发现吗。

**Comment by soralife** [comment]
感谢更新，关于随机播放：
随机播放回溯只会回溯随机播放产生的播放历史，也就是只有自然播放或按下一曲会被记录。而如果通过手动双击播放列表内曲目进行指定歌曲播放，连续指定两首及以上则上一曲时不会记得放过这些歌。
例如：随机播放到曲目1，播放中手动双击播放曲目2，在曲目2未播放完前双击播放曲目3，则此时按上一曲不会记得曾经播放过曲目2会直达由随机播放选定的曲目1

**Comment by zhongyang219** [comment]
关于随机播放的问题，我觉得将手动播放的曲目也放到随机播放的历史中并不一定合理。随机播放时记录的是随机播放的历史，但是手动播放的记录是否也应该作为随机播放的历史还需要讨论一下。有没有其他支持这个功能的播放器，看看它们的逻辑是怎么样的？

**Comment by zhongyang219** [comment]
@soralife 我刚刚想到了另一种办法，就是使用随机播放时，给当前播放列随机表生成一个新的顺序，随机播放时按照这个顺序播放，这样就可以完美解决你的问题，也不用再保存随机播放历史了，而且可以确保随机播放时播放列表中每首歌曲都能被播放到。

**Comment by soralife** [comment]
> 下文不讨论random()是伪随机函数的技术问题，称之为真随机
> 下文不考虑那些自以为知道我想听什么试图给我更好"用户体验"的随机方案

 - 随机分随机播放与乱序播放两种，这是按照如何决定下一曲是什么区分的。
 - 现在播放器使用的是随机播放，网易云音乐UWP使用的是乱序播放。
 - 随机播放在按下一曲时使用random选择一个，乱序播放则是在开启乱序播放与更换歌单时就预先随机出一个固定播放列表之后进行列表循环。(具体实现可能有许多细节关于如何处理上一曲、播放历史与点击播放。)
 - **随机播放** 用random决定下一曲
   - fb2k的随机播放简单粗暴，干脆不允许上一曲，只能按下一曲，不会随机到当前播放。
   - MusicPlayer2随机播放是能够随机到当前播放曲目的，我个人喜欢现在的做法，这才是随机播放(在2400+的播放列表里随机，下一曲又是当前播放的情况大概几天能出现一次，如果又是想听的歌很有惊喜感。如果播放列表很小只有几首歌那么更应采用随机播放而不是听多了能背下来的乱序播放。)
 - **乱序播放** 大部分播放器使用的方案，实现较简单也不用顾虑上一曲的问题，乱序播放本质是对乱序播放列表的列表循环，使用乱序时会生成乱序列表，之后上一曲下一曲都是对乱序列表的列表循环，会在手动指定播放时重置乱序列表。
 
突然想到为什么一定要限定是"随机播放的历史"而不是"播放历史"，下面描述我希望的最佳方案。(代码实现可能略为困难)
还在写
等等再发
这种方法叫乱序播放
先说我的倾向：支持真随机播放，不反对乱序播放，可以共存，历史记录功能强化
请参考 [https://www.zhihu.com/question/19730811](https://www.zhihu.com/question/19730811)

**Comment by zhongyang219** [comment]
确实，随机播放和无序播放其实是两个不同的模式，我之前一直没有注意它们的区别。目前大多数播放器所谓的“随机播放”其实是“无序播放”。现在我把这两种模式都加上了。

**Comment by zhongyang219** [comment]
现在，在随机播放模式下，手动播放的曲目也支持上一曲回溯

**Comment by zhongyang219** [comment]
现在崩溃的问题应该已经解决了，你再试一下。

**Comment by soralife** [comment]
崩溃问题已经不会发生了，虽然选项设置内还不会自动更新，需要ctrl+Q
如果那个错误代码5不影响的话可能需要重新注释

**Comment by zhongyang219** [comment]
我并不清楚是我哪次更改造成了你说的问题，解决错误代码5并不会导致播放设备选择的问题。播放设备一直都是不会自动更新的，目前也无法做到自动更新，如果你的播放设备发生了变化，就必须按Ctrl + Q 才能继续播放。

**Comment by soralife** [comment]
我指的是这个，是原来的那个问题
![图片](https://user-images.githubusercontent.com/43085437/91001520-81c75680-e5fe-11ea-9ca9-1b2ac7929494.png)

**Comment by zhongyang219** [comment]
那行应该也不会影响播放设备的问题啊，那我还是注释掉它吧。

**Comment by soralife** [comment]
这两个不相关，只是我的error.log已经750+了

现在这样就足够了，ctrl+Q也不是很费劲

**Comment by zhongyang219** [comment]
好的，了解了。

**Comment by zhongyang219** [comment]
播放设备变化时无法继续播放的问题终于解决了，现在不用再按Ctrl+Q，它会自动执行重新初始化播放器的操作。你再试试看有还没有其他问题。

**Comment by soralife** [comment]
播放设备数量变化时确实正常重新初始化了，不过播放设备数量变化不是默认播放设备改变的前提条件，从下图这里更改是不需要改变播放设备数量的(不用断开蓝牙，我平常的用法)。
在选项设置->播放设备 设置为默认播放设备时 检测的应当是默认设备是否改变而不是播放设备数量是否改变。
c++我也看不懂，不知道有没有参考意义 [链接](https://www.lagou.com/lgeduarticle/108311.html)

![图片](https://user-images.githubusercontent.com/43085437/91027281-77bd4c00-e62e-11ea-845d-75ff6a4f66b1.png)

**Comment by zhongyang219** [comment]
这次主要还是解决插拔耳机等设备时无法播放的问题，要响应默认播放设备变化还是比较困难，目前你的这种情况还是手动Ctrl+Q吧。

**Comment by soralife** [comment]
其实这次更新之后我也可以通过开关蓝牙耳机曲线实现自动切换了，一年前的旧win10还不行，当时win10兼容性不好连一次蓝牙十分不易舍不得断开，现在蓝牙自动连接比手机还快。

**Comment by SplitGemini** [comment]
暗中注视两位讨论，我也提供一些资料吧。
默认设备变化：[https://docs.microsoft.com/en-us/windows/win32/coreaudio/device-events](https://docs.microsoft.com/en-us/windows/win32/coreaudio/device-events)
参考[DefaultAudioChanger](https://github.com/sgiurgiu/DefaultAudioChanger)
