### ISSUE TITLE
媒体库相关

### ISSUE THREAD

**Issue by soralife** [zhongyang219/MusicPlayer2#90]
我还没有用过媒体库内细致的功能，一直在用播放列表，一大原因是大片大片的未知艺术家、未知专辑影响使用体验。下面详述我猜的原因，如有问题还请指出。

 1. 未知艺术家、未知专辑几乎不会在使用全新程序测试时发现(由于我的"用户\music"目录内歌曲全部有可识别标签)，问题的90%以上出自 `song_data.dat` 只进不出的特性。我推测对于媒体库对话框来说"所有歌曲"的概念直接对应 `song_data.dat` 内缓存的曲目以及曲目信息，"媒体库"本身只会读取其中信息而不会修改或刷新信息。
 `song_data.dat` 文件直接受选项设置->媒体库内选项影响。歌曲信息缓存进此文件大概有两种途径，一种是通过资源管理器等直接打开，另一种是将歌曲所在目录添加到'选项设置->媒体库->媒体库目录'这个列表之后进行媒体库自动更新。而相对的想要删除歌曲信息需要移除原文件再进行清理数据文件操作，换句话就是有许多音频(例如C:\Windows\Media)只要进入缓存就没办法移除。如果作为默认播放器使用势必会放一些奇怪的非歌曲音频文件(例如游戏拆包~~Songs文件夹~~)而这些一般都没有元数据可供识别也不会常听，目前却无法移除这些文件信息。
 我的思路是在'选项设置->媒体库->媒体库选项'内添加复选框'更新媒体库时移除媒体库目录外的音频文件的缓存'以实现启动时清理(需要一个更好的名称)
 并且加一个独立按钮执行此功能(类似清理数据文件)，以此实现将位于媒体库目录外的音频文件的缓存信息一并清空。大概需要告知用户需要将想要保留的部分先添加进媒体库目录，以及之外的文件缓存会连同播放历史一同清除。
 不想删除 `song_data.dat` 来临时解决问题，舍不得播放历史，这个逐渐变大的文件已经3.38MB。
2. 这里显示有152条比特率为0~~目前在整理原因~~已完成，已知的有
   - Songs文件夹内有大量内容只有RIFF标签时长为0的wav文件(我曾经把Songs加入过媒体库目录，由于上面的问题现在也无法移除)，资源管理器识别RIFF标签给出了这些时长0的文件的比特率。我不确定允许这些时长0的文件进入 `song_data.dat`是否合适。
   - 没有音轨的mp4文件，个人认为这些文件一开始就应该被排除不进入 `song_data.dat`。
   - cue文件被归类为比特率0，或者说整个媒体库对于cue的处理显得很奇怪，会把cue文件单纯作为没有元数据的音频文件(因为cue是有TITLE、REM GENRE与PERFORMER等字段的，也可以用对应音频的比特率不过标题我不知如何解决)，~~对应的音频文件也被视为独立的文件处理~~<-这是下一个问题。
   - 被当作一般音频文件处理的有cue对应的音频文件，经测试通过双击直接播放有cue对应的音频文件已不会使其进入`song_data.dat`但是启动时自动更新媒体库好像忘记跳过这些文件了所以当有cue的目录位于媒体库目录列表时发生自动更新cue与对应整轨音频能够同时进入`song_data.dat`。与此同时如果在媒体库双击这个整轨音频会进入临时播放列表并附带许多bug，例如整轨仍会被切分，不过比特率显示0，轨道最后一首时间会溢出出错。
 3. 对与cue文件在媒体库如何处理一般我能想到两种思路，第一就是独立cue作为一种文件类型为其显示属性并且忽略其附带音频文件的存在，第二是忽略cue将被切分好的音频作为一首首独立歌曲来处理。我觉得现在正在实现第一种方案。

我希望能够在保留我的"用户\music"目录播放历史的情况下清除任何其他音频文件相关记录来让`song_data.dat`稍稍变干净些再继续。

![图片](https://user-images.githubusercontent.com/43085437/90465442-f7847b80-e141-11ea-9a9f-21a28faef851.png)

其他小问题与建议会继续更新

**Comment by soralife** [comment]
1. 上文2.4我的测试不足认识有问题，实际是双击播放不在媒体库目录的cue时对应音频文件不会获得比特率如图，需要直接再双击播放那个音频才能使其获得比特率属性(可能需要重启程序？)。未经绝对确认->相对通过添加到媒体库目录自动更新得到的结果是正常的。

![屏幕截图 2020-08-19 154144](https://user-images.githubusercontent.com/43085437/90612894-3d713a80-e23b-11ea-8691-007056a880dd.png)

 2. 上文2.4描述的症状使用新程序仍然出现具体步骤：双击播放一个/累计多个cue(要求cue对应音频还没有获得比特率)则可在媒体库复现上图状态(图用的是清理媒体库之前的，积攒了很多，已确认新程序可以复现)此时双击播放任意没有比特率的音频则进入下图所示临时播放列表。

![屏幕截图 2020-08-19 153806](https://user-images.githubusercontent.com/43085437/90613071-76a9aa80-e23b-11ea-953f-1d78c0d3b59f.png)

 3. 媒体库内进行按比特率排序时使用的是字符串比较，表现为0<1000<128<1411<192<2822<320<999等

**Comment by zhongyang219** [comment]
选项设置>媒体库中新增了媒体库功能，原来的清理数据文件功能只能清理不存在的文件，现在增加了更多清理选项：
![image](https://user-images.githubusercontent.com/30562462/90720827-f68e4e00-e2e9-11ea-8e4f-d8e79c339e8e.png)

**Comment by soralife** [comment]
播放cue完全正常，要去媒体库特意点那个附带的音频文件才会触发
这个清理功能改的很好，也解决了用户交互的问题
关于我之前说的启动时清理媒体库外的缓存，后来我想起来还有Songs文件夹这个特殊情况，我提出的这条不合理

**Comment by zhongyang219** [comment]
关于播放cue关联的音频文件没有获取长度和比特率的问题应该是解决了，你再试一下。

**Comment by soralife** [comment]
感谢修复，目前可以了，问题不会再出现

**Comment by zhongyang219** [comment]
之前版本中从媒体库中打开cue文件时还是有问题，现在修正了。
