### ISSUE TITLE
部分歌曲内嵌封面读取不完全

### ISSUE THREAD

**Issue by xkww3n** [zhongyang219/MusicPlayer2#94]
emmmm...内嵌专辑封面功能又出问题了，似乎与封面体积无关，像下面这样：

![image](https://user-images.githubusercontent.com/30206355/90975637-9b1dc380-e568-11ea-8b7d-107932f7969a.png)

![image](https://user-images.githubusercontent.com/30206355/90975646-affa5700-e568-11ea-9838-1d5d4a563479.png)

且其他播放器（如PotPlayer）能够正常读取：

![image](https://user-images.githubusercontent.com/30206355/90975693-2e56f900-e569-11ea-8b4f-0476159b3f27.png)

![image](https://user-images.githubusercontent.com/30206355/90975698-36af3400-e569-11ea-8d9a-0285ab381b20.png)

部分出现问题的歌曲：https://cowtransfer.com/s/72944b05657942

**Comment by zhongyang219** [comment]
新版本改成了使用taglib库获取歌曲信息和专辑封面，这个问题已经解决了，请等待下一个版本更新。
