### ISSUE TITLE
有三首歌的元数据无法读取

### ISSUE THREAD

**Issue by xkww3n** [zhongyang219/MusicPlayer2#95]
使用commit `33458da`编译的软件中有三首歌的元数据没法读取，全部信息都是未知：

![image](https://user-images.githubusercontent.com/30206355/91126655-18ffdd00-e6d7-11ea-915f-42478a4d9641.png)

![image](https://user-images.githubusercontent.com/30206355/91126663-1b623700-e6d7-11ea-8bb0-b87c489c3aa9.png)

![image](https://user-images.githubusercontent.com/30206355/91126696-30d76100-e6d7-11ea-9f06-114fbe8811a0.png)

元数据肯定是好的，其他软件也能识别。
其中两首歌的文件在此（图中`洛天依 - 风的祈求者.flac`是付费专辑中的歌曲，恕不提供）：https://cowtransfer.com/s/3828be0d9d534d

**Comment by zhongyang219** [comment]
感谢反馈，问题已解决。
