### ISSUE TITLE
歌曲随机播放bug相关

### ISSUE THREAD

**Issue by usagi20** [zhongyang219/MusicPlayer2#96]
你好，我这边有个问题，我默认播放列表有5533首歌曲，但是在我无数次点击下一首的尝试后，发现随机的范围最多只会到第3298首歌曲左右，3298到5533首这之间的歌曲完全不会被随机到，大佬能否查查看随机播放是否有bug orz
3298-5533我手动播放是可以正常播放的 都是正常的MP3文件....
如果确实有问题的话可不可以让随机播放逻辑变成播放列表所有歌曲里的随机一首_(:з」∠)_...感谢

**Comment by zhongyang219** [comment]
你好，感谢你的反馈，正在调查这个问题。

**Comment by zhongyang219** [comment]
你好，这个问题已经解决了。这是我临时编译的版本：[MusicPlayer2_V2.70.1_x64_beta.zip](https://github.com/zhongyang219/MusicPlayer2/files/5134688/MusicPlayer2_V2.70.1_x64_beta.zip)

**Comment by usagi20** [comment]
辛苦了，捐个3R请开发喝可乐

**Comment by usagi20** [comment]
辛苦了，捐个3R请开发喝可乐
