### ISSUE TITLE
列表发生错乱

### ISSUE THREAD

**Issue by eail-zh** [zhongyang219/MusicPlayer2#98]
> 软件版本 2.70.1版（x64）

> 我的媒体库中有一个文件夹 `music` ，两个播放列表 `[默认]` 、 `[我喜欢的音乐]` 。 `music` 里面有六百多首音乐， `默认` 里面没有音乐， `我喜欢的音乐` 里面有一百多首音乐。

今天在使用的过程当中想要将 `music` 里面的一首歌添加到 `[我喜欢的音乐]` ，于是在 `music` 中右键选中的曲目，*添加到播放列表*，*我喜欢的音乐*，弹窗提示*文件已存在于播放列表中*，点击*确认*。然后发现顶端 *媒体库* 按钮左边显示当前位置为 **播放列表：*[我喜欢的音乐]*** ，但下方的列表里面显示的仍是 `music` 文件夹里的曲目，而且此时因为位于 `[我喜欢的音乐]` 内，没法切换回 `[我喜欢的音乐]` ，只能先在媒体库内切换到 `music` 内，再切换到 `[我喜欢的音乐]` 。

而后在测试错误状况的时候发现明明应该为空的 `[默认]` 列表和 `[我喜欢的音乐]` 列表的曲目发生了同步。清空 `[默认]` ，切换到 `[我喜欢的音乐]` ，再切换回 `[默认]` ，发现其又恢复到了和 `[我喜欢的音乐]` 相同的状态；清空 `[我喜欢的音乐]` ，切换到 `[默认]` ，`[默认]` 也为空，再切换回 `[我喜欢的音乐]` ， `[我喜欢的音乐]` 又回复到了清空前的状态。

**Comment by soralife** [comment]
问题存在，条件：
 - 处于文件夹模式(任意文件夹，包括Songs)
 - 目标播放列表此次程序启动后未被打开过
 - 选择歌曲后右键选择新建播放列表是正常的
 - 通过右键(打♥不会出问题)单选或多选文件添加到目标播放列表(任意播放列表，且与播放列表内容无关，即不在意是否确实"文件已存在")
此时问题发生，表现(同时发生)：
 - 弹出文件已存在对话框
 - 播放模式变为播放列表模式，播放目标播放列表刚刚试图添加曲目
 - 目标播放列表被完全覆写，内容变为刚刚播放的文件夹内所有歌曲，且会以"标题"排序

注：从文件夹模式向播放列表添加歌曲时，当播放列表未打开过时检查文件是否已存在机制可正常工作

暂未发现播放列表间互相影响

**Comment by zhongyang219** [comment]
@soralife 我按你的步骤死活复现不出来，可能是我的操作不对，可以帮忙录个动图嘛

**Comment by zhongyang219** [comment]
@soralife 我复现出来了，我看成目标播放列表“未被打开过”了

**Comment by zhongyang219** [comment]
问题已经解决了，复现这个问题的步骤为：
* 打开一个播放列表
* 切换到文件夹模式下
* 添加一个文件到刚刚打开的播放列表
只有在文件夹模式下会出现。
这个问题是2.70版本开始出现的，之前的版本应该是好的。
